### ISSUE TITLE
shadow_client : segmentation fault in log message

### ISSUE THREAD

**Issue by cbr-rc** [FreeRDP/FreeRDP#10869]
Hello,
In server/shadow/shadow_client.c:BitmapUpdateProxyEx:71, I get a segmentation fault at WLog_Print. 
I am using FreeRDP 3.9.0.

```c
const BOOL rc = IFCALLRESULT(FALSE, update->BitmapUpdate, context, &cur);
if (!rc)
{
	WLog_Print(WLog_Get(TAG), WLOG_ERROR, line, file, fkt,
			         "BitmapUpdate[%" PRIu32 "] failed", x);
	return FALSE;
}
``` 
```
#1  0x00007dffc2924ad6 in WLog_PrintMessageVA
    (log=0x7dff98021140, type=0, level=4, line=71, file=0x7dffc30e09f8 "freerdp/server/shadow/shadow_client.c", function=0x7dffc30e1cc0 <__func__.108> "BitmapUpdateProxyEx", args=0x7dff9f1fec50) at freerdp/winpr/libwinpr/utils/wlog/wlog.c:368
#2  0x00007dffc292505c in WLog_PrintMessage
    (log=0x7dff98021140, type=0, level=4, line=71, file=0x7dffc30e09f8 "freerdp/server/shadow/shadow_client.c", function=0x7dffc30e1cc0 <__func__.108> "BitmapUpdateProxyEx") at freerdp/winpr/libwinpr/utils/wlog/wlog.c:424
#3  0x00007dffc30cbc98 in BitmapUpdateProxyEx
    (update=0x7dffa802d100, context=0x7dffa8001190, bitmap=0x7dff9f1fee90, file=0x7dffc30e09f8 "freerdp/server/shadow/shadow_client.c", line=1823, fkt=0x7dffc30e20c0 <__func__.42> "shadow_client_send_bitmap_update") at freerdp/server/shadow/shadow_client.c:71
```

**Comment by akallabeth** [comment]
@cbr-rc thx for the report, looks like the wrong log function was called (or with wrong arguments at least)
