### ISSUE TITLE
Segfault in v1.1

### ISSUE THREAD

**Issue by Ignotus** [FreeRDP/FreeRDP#1676]
Hi,

I have built from the github branch stable-1.1.

How to reproduce:
mkdir build && cmake ../ && sudo make install

Create /etc/winpr/SAM by winpr/tools/hash/winpr-hash

```
/usr/local/bin/xfreerdp /u:"USER" /v:NAME /g:GATEWAY /f
```

And do something about 3-4 minutes :)

Backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeeeb4700 (LWP 11153)]
0x00007ffff3df1b47 in ArrayList_Add () from /usr/local/bin/../lib64/libwinpr-utils.so.0.1
(gdb) bt
#0  0x00007ffff3df1b47 in ArrayList_Add () from /usr/local/bin/../lib64/libwinpr-utils.so.0.1
#1  0x00007ffff6679b3a in rpc_write () from /usr/local/bin/../lib64/libfreerdp-core.so.1.1
#2  0x00007ffff6677ffc in TsProxySendToServer () from /usr/local/bin/../lib64/libfreerdp-core.so.1.1
#3  0x00007ffff6679557 in tsg_write () from /usr/local/bin/../lib64/libfreerdp-core.so.1.1
#4  0x00007ffff666e9d0 in transport_write () from /usr/local/bin/../lib64/libfreerdp-core.so.1.1
#5  0x00007ffff666b3ba in rdp_send_data_pdu () from /usr/local/bin/../lib64/libfreerdp-core.so.1.1
#6  0x00007ffff6670303 in update_send_suppress_output () from /usr/local/bin/../lib64/libfreerdp-core.so.1.1
#7  0x00007ffff7b4e29a in xf_event_process () from /usr/local/bin/../lib64/libxfreerdp-client.so.1.1
#8  0x00007ffff7b55637 in xf_process_x_events () from /usr/local/bin/../lib64/libxfreerdp-client.so.1.1
#9  0x00007ffff7b56372 in xf_thread () from /usr/local/bin/../lib64/libxfreerdp-client.so.1.1
#10 0x00007ffff244f0db in start_thread () from /lib64/libpthread.so.0
#11 0x00007ffff176a90d in clone () from /lib64/libc.so.6
```

If a developer needs more info, please tell.

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
