### ISSUE TITLE
Crash with TS Gateway after E_PROXY_RAP_ACCESSDENIED error

### ISSUE THREAD

**Issue by nalimilan** [FreeRDP/FreeRDP#1728]
Seeing this with git master. This is similar to what I reported at #1589, except that now it crashes. The problem has been introduced over the last 4 months in git master.

```
xfreerdp /v:CLUSTER /d:DOMAIN /u:USER /p:PASSWD /g:GW /gd:DOMAIN /gu:USER /gp:PASSWD
[...]

Sending PDU (length: 132)
rpc_vers: 5
rpc_vers_minor: 0
ptype: PTYPE_REQUEST (0)
pfc_flags (0x03) = { PFC_FIRST_FRAG PFC_LAST_FRAG }
packed_drep[4]: 10 00 00 00
frag_length: 132
auth_length: 16
call_id: 5
0000 05 00 00 03 10 00 00 00 84 00 10 00 05 00 00 00 ................
0010 54 00 00 00 00 00 04 00 00 00 00 00 cc a8 e9 cd T...............
0020 91 bc fa 46 b7 8a 60 35 e9 fd 91 d1 00 00 02 00 ...F..`5........
0030 01 00 00 00 00 00 00 00 00 00 00 00 03 00 3d 0d ..............=.
0040 01 00 00 00 04 00 02 00 0c 00 00 00 00 00 00 00 ................
0050 0c 00 00 00 31 00 30 00 2e 00 39 00 32 00 2e 00 ....1.0...9.2...
0060 33 00 2e 00 31 00 30 00 36 00 00 00 0a 05 00 00 3...1.0.6.......
0070 00 00 00 00 01 00 00 00 93 07 be 6f 52 15 86 ac ...........oR...
0080 03 00 00 00                                     ....

RPC Fault PDU:
status: E_PROXY_RAP_ACCESSDENIED (0x800759DA)
TsProxyCreateChannel: error reading response
Error: protocol security negotiation or connection failure
*** Error in `[Thread 0x7fffe7fff700 (LWP 31233) exited]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffed16b700 (LWP 31229)]
0x000000336bc35c39 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) ba
#0  0x000000336bc35c39 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x000000336bc37348 in __GI_abort () at abort.c:89
#2  0x000000336bc75d04 in __libc_message (do_abort=do_abort@entry=2, 
    fmt=fmt@entry=0x336bd7c528 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#3  0x000000336bc7cff8 in malloc_printerr (ptr=<optimized out>, 
    str=0x336bd7c600 "double free or corruption (!prev)", action=3)
    at malloc.c:4930
#4  _int_free (av=0x336bfb8760 <main_arena>, p=<optimized out>, have_lock=0)
    at malloc.c:3782
#5  0x000000336bc8069e in __GI___libc_realloc (oldmem=0x617e90, bytes=0)
    at malloc.c:2925
#6  0x00007ffff4eedad9 in StreamPool_Return (pool=0x617df0, s=0x7fffe8099d50)
    at /home/milan/Dev/FreeRDP/winpr/libwinpr/utils/collections/StreamPool.c:183
#7  0x00007ffff4eedc3b in Stream_Release (s=0x7fffe8099d50)
    at /home/milan/Dev/FreeRDP/winpr/libwinpr/utils/collections/StreamPool.c:240
#8  0x00007ffff746e7d7 in transport_check_fds (transport=0x6178b0)
    at /home/milan/Dev/FreeRDP/libfreerdp/core/transport.c:958
#9  0x00007ffff7468cdb in rdp_check_fds (rdp=0x609640)
    at /home/milan/Dev/FreeRDP/libfreerdp/core/rdp.c:1184
#10 0x00007ffff7460c36 in rdp_client_connect (rdp=0x609640)
    at /home/milan/Dev/FreeRDP/libfreerdp/core/connection.c:277
#11 0x00007ffff744e996 in freerdp_connect (instance=0x604000)
    at /home/milan/Dev/FreeRDP/libfreerdp/core/freerdp.c:95
#12 0x00007ffff7d74c28 in xf_thread (param=0x604000)
    at /home/milan/Dev/FreeRDP/client/X11/xf_client.c:1455
#13 0x000000336c407f33 in start_thread (arg=0x7fffed16b700)
    at pthread_create.c:309
#14 0x000000336bcf4ded in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by nalimilan** [comment]
As I said on https://github.com/FreeRDP/FreeRDP/issues/1589, it no longer happens with git master.
