### ISSUE TITLE
segmentation fault on long command line

### ISSUE THREAD

**Issue by dafinchi** [FreeRDP/FreeRDP#2085]
if command line is too long freerdp dies with a segfault.
shortening the target server name helped to get it working in my special case.

````
#0  0x00007ffff71d30ca in strlen () from /lib64/libc.so.6
#1  0x00007ffff37e234d in freerdp_addin_replace_argument_value (args=args@entry=0x676d10, previous=0x2e616469612e3131 <Address 0x2e616469612e3131 out of bounds>, option=option@entry=0x7ffff792e2e1 "sys", 
    value=0x2e616469612e3131 <Address 0x2e616469612e3131 out of bounds>) at /var/tmp/paludis/net-misc-freerdp-1.1.0_beta1_p20130710-r1/work/freerdp-1.1.0_beta1_p20130710/libfreerdp/common/settings.c:114
#2  0x00007ffff7910f26 in freerdp_client_old_process_plugin (settings=settings@entry=0x60aa30, args=args@entry=0x676d10)
    at /var/tmp/paludis/net-misc-freerdp-1.1.0_beta1_p20130710-r1/work/freerdp-1.1.0_beta1_p20130710/client/common/compatibility.c:159
#3  0x00007ffff7910ffa in freerdp_client_old_command_line_pre_filter (context=context@entry=0x60aa30, index=15, index@entry=14, argc=argc@entry=25, argv=argv@entry=0x7fffffffdab8)
    at /var/tmp/paludis/net-misc-freerdp-1.1.0_beta1_p20130710-r1/work/freerdp-1.1.0_beta1_p20130710/client/common/compatibility.c:278
#4  0x00007ffff50c937f in CommandLineParseArgumentsA (argc=argc@entry=25, argv=argv@entry=0x7fffffffdab8, options=options@entry=0x7ffff7b3b940 <old_args>, flags=flags@entry=1068, context=context@entry=0x60aa30, 
    preFilter=preFilter@entry=0x7ffff7910f40 <freerdp_client_old_command_line_pre_filter>, postFilter=postFilter@entry=0x7ffff7910be0 <freerdp_client_old_command_line_post_filter>)
    at /var/tmp/paludis/net-misc-freerdp-1.1.0_beta1_p20130710-r1/work/freerdp-1.1.0_beta1_p20130710/winpr/libwinpr/utils/cmdline.c:88
#5  0x00007ffff79113d4 in freerdp_client_parse_old_command_line_arguments (argc=argc@entry=25, argv=argv@entry=0x7fffffffdab8, settings=settings@entry=0x60aa30)
    at /var/tmp/paludis/net-misc-freerdp-1.1.0_beta1_p20130710-r1/work/freerdp-1.1.0_beta1_p20130710/client/common/compatibility.c:374
#6  0x00007ffff790f156 in freerdp_client_parse_command_line_arguments (argc=argc@entry=25, argv=argv@entry=0x7fffffffdab8, settings=settings@entry=0x60aa30)
    at /var/tmp/paludis/net-misc-freerdp-1.1.0_beta1_p20130710-r1/work/freerdp-1.1.0_beta1_p20130710/client/common/cmdline.c:1022
#7  0x00007ffff790d89f in freerdp_client_parse_command_line (context=context@entry=0x605580, argc=argc@entry=25, argv=argv@entry=0x7fffffffdab8)
    at /var/tmp/paludis/net-misc-freerdp-1.1.0_beta1_p20130710-r1/work/freerdp-1.1.0_beta1_p20130710/client/common/client.c:111
#8  0x0000000000401b6a in main (argc=25, argv=0x7fffffffdab8) at /var/tmp/paludis/net-misc-freerdp-1.1.0_beta1_p20130710-r1/work/freerdp-1.1.0_beta1_p20130710/client/X11/cli/xfreerdp.c:56
```

**Comment by akallabeth** [comment]
Any news on this one?

**Comment by giox069** [comment]
It's very old. I never had a similar problem in the last 1.5 years. I think you can close it.
