### ISSUE TITLE
Problems under Mac OS X 10.5.8 Leopard/PPC (inverted colors without NLA, transport failed with NLA)

### ISSUE THREAD

**Issue by czo** [FreeRDP/FreeRDP#2520]
Hi,

Fresh compilation from current master with OS X Leopard 10.5.8 fails to connect to my Windows 7 box. 

When non NLA clients allowed, colors seems to be inverted (screenshot: homokozo.czo.hu/xfreerdp.png ). Googled around it, and fount this message: http://sourceforge.net/p/freerdp/mailman/message/29015196/ , but i can't find the patch. It's merged?

When NLA is requred, i can't connect because:
tornado:~ czo$ xfreerdp /v:172.16.30.252 
[00:42:24:740] [12130:f0081000] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: czo
[00:42:24:879] [12130:f0081000] [ERROR][com.freerdp.client.x11] - Property 174 does not exist
Password: 
[00:42:27:225] [12130:f0081000] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[00:42:27:236] [12130:f0081000] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1

Anyone has any idea how to make it work? 

versions:
xcode: 3.1.4
cmake: 2.8.12.2
openssl: 1.0.2a 19 Mar 2015

configured with: cmake -DCMAKE_CXX_COMPILER=g++-4.2 -DCMAKE_C_COMPILER=gcc-4.2 -DWITH_X11=ON .

**Comment by bmiklautz** [comment]
@czo what version of FreeRDP dis you try with?

**Comment by czo** [comment]
1.2.0-beta1+android9 from releases. Current master also has this problem, checked it five minutes ago.

current master:
tornado:~ czo$ xfreerdp /version
This is FreeRDP version 1.2.1-dev (git 879ed36)

previous compilation from 1.2.0-beta1+android9
tornado:~ czo$ xfreerdp.old /version
This is FreeRDP version 1.2.1-dev (git n/a)

If u need, i can provide any logs.

**Comment by czo** [comment]
I forgot the arch, i'm trying it on my old PowerPC based notebook.

**Comment by bmiklautz** [comment]
@czo ah ok. Then my guess would be that it is a problem with byte order.
I'm not sure if anyone tested on PowerPC :(.

**Comment by czo** [comment]
That was my first thought when i first see the color inversion. Login with enabled Network Level Auth is caused by byte ordering, or it's seems to another problem?

**Comment by bmiklautz** [comment]
@czo not sure about NLA but it's possible that this is caused by some byte order problem as well.

**Comment by hardening** [comment]
@czo if you activate DEBUG_NLA perhaps that could give us a tip of where is the byte ordering problem...

**Comment by czo** [comment]
Now, i have time to play with it:

build with:
cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-4.2 -DCMAKE_C_COMPILER=/usr/bin/gcc-4.2 -DWITH_X11=ON -DWITH_DEBUG_ALL=ON -DCMAKE_BUILD_TYPE=Debug .

bash-3.2$ ./xfreerdp /version
This is FreeRDP version 1.2.4-dev (git ca274b6)

bash-3.2$ WLOG_LEVEL=debug ./xfreerdp /u:Administrator /v:172.16.30.252 /p:almafa /sec:nla
[16:24:00:148] [17914:a0b2e820] [DEBUG][com.freerdp.client.common.cmdline] - windows: 0/1 posix: -1000/0 compat: -1000/0
[16:24:00:172] [17914:f0081000] [ERROR][com.freerdp.client.x11] - Property 174 does not exist
[16:24:00:173] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
[16:24:00:173] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: FALSE
[16:24:00:173] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: FALSE
[16:24:00:173] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: FALSE
[16:24:00:173] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
[16:24:00:173] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
[16:24:00:173] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
[16:24:00:173] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - Attempting NLA security
[16:24:00:177] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - RequestedProtocols: 3
[16:24:00:179] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - RDP_NEG_RSP
[16:24:00:179] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - selected_protocol: 2
[16:24:00:179] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_FINAL
[16:24:00:179] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - Negotiated NLA security
[16:24:00:179] [17914:f0081000] [DEBUG][com.freerdp.core.nego] - nego_security_connect with PROTOCOL_NLA
[16:24:00:203] [17914:f0081000] [DEBUG][com.winpr.sspi] - InitSecurityInterfaceExA
[16:24:00:203] [17914:f0081000] [DEBUG][com.winpr.sspi] - QuerySecurityPackageInfoA: SEC_E_OK (0x0000)
[16:24:00:203] [17914:f0081000] [DEBUG][com.winpr.sspi] - AcquireCredentialsHandleA: SEC_E_OK (0x0000)
[16:24:00:203] [17914:f0081000] [DEBUG][com.winpr.sspi] - InitializeSecurityContextA: SEC_I_CONTINUE_NEEDED (0x90312)
[16:24:00:203] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - Sending Authentication Token
[16:24:00:203] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0000 4e 54 4c 4d 53 53 50 00 01 00 00 00 b7 82 08 e2 NTLMSSP.........
[16:24:00:204] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
[16:24:00:204] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0020 06 01 b1 1d 00 00 00 0f                         ........
[16:24:00:206] [17914:f0081000] [DEBUG][com.winpr.sspi] - InitializeSecurityContextA: SEC_I_COMPLETE_NEEDED (0x90313)
[16:24:00:206] [17914:f0081000] [DEBUG][com.winpr.sspi] - CompleteAuthToken: SEC_E_OK (0x0000)
[16:24:00:207] [17914:f0081000] [DEBUG][com.winpr.sspi] - QueryContextAttributesA: SEC_E_OK (0x0000)
[16:24:00:207] [17914:f0081000] [DEBUG][com.winpr.sspi] - EncryptMessage: SEC_E_OK (0x0000)
[16:24:00:207] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - Sending Authentication Token
[16:24:00:207] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0000 4e 54 4c 4d 53 53 50 00 03 00 00 00 18 00 18 00 NTLMSSP.........
[16:24:00:207] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0010 80 00 00 00 92 00 92 00 98 00 00 00 00 00 00 00 ................
[16:24:00:207] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0020 58 00 00 00 1a 00 1a 00 58 00 00 00 0e 00 0e 00 X.......X.......
[16:24:00:207] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0030 72 00 00 00 10 00 10 00 2a 01 00 00 35 a2 88 e2 r.......*...5...
[16:24:00:207] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0040 06 01 b1 1d 00 00 00 0f f5 ac f0 f4 76 13 3a ac ............v.:.
[16:24:00:209] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0050 f5 00 07 ca 2d d5 99 ff 00 41 00 64 00 6d 00 69 ....-....A.d.m.i
[16:24:00:209] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0060 00 6e 00 69 00 73 00 74 00 72 00 61 00 74 00 6f .n.i.s.t.r.a.t.o
[16:24:00:209] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0070 00 72 00 74 00 6f 00 72 00 6e 00 61 00 64 00 6f .r.t.o.r.n.a.d.o
[16:24:00:209] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0080 ac 82 1c 07 4f 69 92 c3 c1 8e af 08 ae 8f 32 f9 ....Oi........2.
[16:24:00:210] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0090 3f 22 96 d9 3c 8e 68 f0 aa eb e3 cf fa 59 63 25 ?"..<.h......Yc%
[16:24:00:210] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 00a0 21 fa 13 36 9f 94 be 08 01 01 00 00 00 00 00 00 !..6............
[16:24:00:210] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 00b0 01 d0 99 51 f0 7f 00 00 3f 22 96 d9 3c 8e 68 f0 ...Q....?"..<.h.
[16:24:00:210] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 00c0 00 00 00 00 00 06 00 04 00 00 00 02 00 0a 00 10 ................
[16:24:00:211] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 00d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
[16:24:00:211] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 00e0 00 09 00 2a 00 54 00 45 00 52 00 4d 00 53 00 52 ...*.T.E.R.M.S.R
[16:24:00:211] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 00f0 00 56 00 2f 00 31 00 37 00 32 00 2e 00 31 00 36 .V./.1.7.2...1.6
[16:24:00:211] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0100 00 2e 00 33 00 30 00 2e 00 32 00 35 00 32 00 00 ...3.0...2.5.2..
[16:24:00:212] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0110 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
[16:24:00:212] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0120 00 00 00 00 00 00 00 00 00 00 5a db 28 58 68 cf ..........Z.(Xh.
[16:24:00:212] [17914:f0081000] [DEBUG][com.freerdp.core.nla] - 0130 29 3b 53 87 d0 fd 16 05 86 ba                   );S.......
[16:24:00:218] [17914:f0081000] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[16:24:00:218] [17914:f0081000] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
[16:24:00:231] [17914:a0b2e820] [DEBUG][com.winpr.sspi] - DeleteSecurityContext: SEC_E_OK (0x0000)

**Comment by hardening** [comment]
@awakecoding I gave a quick look at the code but I haven't seen anything obvious that would not be endian safe in the NLA code. Would you mind give a look ?

**Comment by niutech** [comment]
Does the color inversion on big endian still exist? I wanted to build FreeRDP on my Mac PPC, but if it is not fixed, it will be a waste of time.

**Comment by czo** [comment]
Yes, it's currently still exists.

But it's seems more strange than i see it before. When i try to connect to Windows XP SP3 with rdp without NLA, with the following command:
xfreerdp /u:czo /p:******* /v:192.168.1.11
The logon process stopping with invalid password error, and my username displaying boxes instead of readable characters: http://homokozo.czo.hu/freerdp-xpsp3-logon.png
When i type my username via the keyboard, i can logon to this system. Standard GUI colors seems fine, only the colors from images are garbaged. So i think, not only the display has problems with endianess, something in the authentication codes is also broken (maybe, this affecting NLA?)

I can send/attach any debug log (with NLA or without), but because it's seems to contain sensitive data, i don't want to paste it here.

**Comment by ondrejholy** [comment]
It seems that freerdp doesn't work properly on big-endian architectures (tested on ppc64 and s390x). I built several xfreerdp versions (stable-1.0, stable-1.1, 1.2.0-beta1+android9, master), some of them crash, or exit with some error, rest of them have problems with colors and nla... 

I have no idea why nla doesn't work, but --no-nla (--sec rdp|--sec tla) usually works as workaround. I am going to debug what is wrong. However it seems that a code in color.h/.c is not endian-safe and thus the colors are corrupted. Actually xfreerdp -a 32 (--gdi hw) works for me, but -a 8/16/24, nor --gdi sw doesn't work.

Following patch might be applied for freerdp-1.0 to fix -a 16 --gdi hw (change for master would be more complicated), but I am not sure what is right approach there. Big-endian versions of color conversion macros in color.h might be another solution. Don't you have in mind some better approach? Maybe also some gdi.c changes are needed to fix --gdi sw.
```
@@ -574,11 +575,11 @@ uint8* freerdp_image_convert_16bpp(uint8* srcData, uint8* dstData, int width, in
                for (i = width * height; i > 0; i--)
                {
-                       pixel = *src16;
+                       pixel = htole16(*src16);
                        src16++;
                        GetBGR16(red, green, blue, pixel);
                        pixel = (clrconv->invert) ? RGB32(red, green, blue) : BGR32(red, green, blue);
-                       *dst32 = pixel;
+                       *dst32 = le32toh(pixel);
                        dst32++;
                }
                return dstData;
```

**Comment by hardening** [comment]
Does it work better with last master ?

**Comment by ondrejholy** [comment]
I've just retested with FreeRDP master on RHEL 6.7 ppc64.The behavioral seems to be even worse.

I see following warnings during build (see [buildlog](https://gist.github.com/ondrejholy/1300a49fd71ecfb28dd8)):
> warning: cast from pointer to integer of different size

Consequently xfreerdp /sec:nla segfaults with following backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xfffb10df130 (LWP 5655)]
0x000000801918b0b8 in .strcmp () from /lib64/power6/libc.so.6
#0  0x000000801918b0b8 in .strcmp () from /lib64/power6/libc.so.6
#1  0x00000fffb7aa94bc in sspi_GetSecurityFunctionTableAByNameA (Name=0xffffffffb7af47a0 <Address 0xffffffffb7af47a0 out of bounds>)
    at /root/FreeRDP/winpr/libwinpr/sspi/sspi_winpr.c:510
#2  0x00000fffb7aac0cc in winpr_InitializeSecurityContextA (phCredential=0xfffac06d29c, phContext=0x0, 
    pszTargetName=0xfffac06d4a0 "TERMSRV/lab-windows7-1.gsslab.rdu2.redhat.com", fContextReq=50, Reserved1=0, TargetDataRep=16, pInput=0x0, Reserved2=0, 
    phNewContext=0xfffac06d268, pOutput=0xfffac06d2e8, pfContextAttr=0xfffac06d290, ptsExpiry=0xfffac06d2a4) at /root/FreeRDP/winpr/libwinpr/sspi/sspi_winpr.c:1230
#3  0x00000fffb7c249ac in nla_client_begin (nla=0xfffac06d250) at /root/FreeRDP/libfreerdp/core/nla.c:341
#4  0x00000fffb7caf600 in transport_connect_nla (transport=0x100344f0) at /root/FreeRDP/libfreerdp/core/transport.c:202
#5  0x00000fffb7c2c428 in nego_security_connect (nego=0x10045760) at /root/FreeRDP/libfreerdp/core/nego.c:210
#6  0x00000fffb7c2c1ac in nego_connect (nego=0x10045760) at /root/FreeRDP/libfreerdp/core/nego.c:183
#7  0x00000fffb7c8fe70 in rdp_client_connect (rdp=0x100267f0) at /root/FreeRDP/libfreerdp/core/connection.c:270
#8  0x00000fffb7c665c0 in freerdp_connect (instance=0x10021000) at /root/FreeRDP/libfreerdp/core/freerdp.c:99
#9  0x00000fffb7f49720 in xf_client_thread (param=0x10021000) at /root/FreeRDP/client/X11/xf_client.c:1507
#10 0x00000fffb7a942a8 in thread_launcher (arg=0x10084e30) at /root/FreeRDP/winpr/libwinpr/thread/thread.c:315
#11 0x00000080192cc62c in start_thread (arg=0xfffb10df130) at pthread_create.c:303
#12 0x00000080191fefdc in .__clone () from /lib64/power6/libc.so.6
```

Also xfreerdp /sec:rdp segfaults with another backtrace, but the problem is probably same, there is something wrong with types according the warnings...

**Comment by hardening** [comment]
@ondrejholy any chance that you would recompile with valgrind helpers activated and that you give a try with xfreerdp running under valgrind ?

**Comment by bmiklautz** [comment]
@ondrejholy @hardening if I'm not mistaken there are known issues on ppc regarding byte order. There was (is) a patch floating around from the debian folks but I'm not sure if everything is working.

**Comment by ondrejholy** [comment]
@hardening see [valgrind log](https://gist.github.com/ondrejholy/d904cfcba5500357b9fd) from master

@bmiklautz don't you have more info about the patch? However thanks to you notice, I've looked in freerdp source package for debian and found [one usefull patch](http://anonscm.debian.org/cgit/collab-maint/freerdp.git/tree/debian/patches/1004_64-bit-architectures.patch). It fixes the types (at least the warnings disappeared), however xfreerdp still doesn't work:

```
# xfreerdp /u:U /p:P /v:V
[06:41:07:515] [13769:13770] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error
[06:41:07:515] [13769:13770] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[06:41:07:516] [13769:13770] [ERROR][com.freerdp.client.x11] - Freerdp connect error exit status 1
```

```
# xfreerdp /v:V /sec:rdp
[06:41:57:885] [13772:13773] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: root
[06:42:07:950] [13772:13773] [ERROR][com.freerdp.locale] - Unable to detect time zone
[06:42:14:782] [13772:13773] [ERROR][com.freerdp.core] - Decompression failure!
[06:42:14:782] [13772:13773] [ERROR][com.freerdp.core.fastpath] - bulk_decompress() failed
[06:42:14:782] [13772:13773] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[06:42:14:782] [13772:13773] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[06:42:14:782] [13772:13773] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[06:42:14:782] [13772:13773] [INFO][com.freerdp.client.x11] - Network disconnect!
[06:42:14:782] [13772:13773] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
```

**Comment by bmiklautz** [comment]
@ondrejholy that's the patch I was talking about. I thought the type fix does the trick. If not it might be related to the byte order. We don't have any ppc development or test machine therefore it's not really tested.

**Comment by akallabeth** [comment]
@ondrejholy There is nearly no conversion done for integer types from network to host byte order and vice versa. You could start to have a look at ```Stream_Read_*``` and ```Stream_Write_*``` functions and try to add conversion there, but it would only be a starting point. No idea how much work it would really be to make the whole lib endianess aware.

**Comment by hardening** [comment]
@akallabeth from the log it looks like Stream_XXX functions are quite safe as @ondrejholy managed to pass the negociation steps. @ondrejholy perhaps you could give a try without compression activated...

**Comment by ondrejholy** [comment]
@hardening Good point, -compression fixes /sec:rdp case though colors are still corrupted. Result with /sec:nla is same as before...
