### ISSUE TITLE
I still get error “Unfortunately, aFreeRDP has stopped.”

### ISSUE THREAD

**Issue by amater2048** [FreeRDP/FreeRDP#3253]
Hi, 
Thanks a lot for your nice application.
I need to make some change to your app to for many users (add some bookmarks and configurations by default).

1.	I download and install aFreeRDP to use it for Android Devices from Google Play:
https://play.google.com/store/apps/details?id=com.freerdp.afreerdp
I test our service, everything was ok.

2.	I download source from GitHub:
https://github.com/FreeRDP/FreeRDP/
and use option «Open an existing Android Studio project» to import it to «Android Studio».
Path ($FreeRDP-master>>client>>Android>>Studio)

3.	I try to compile it (without any changes) and run on a Device (a real device and a AVD)

4.	But every time I try to run it, app close suddenly with error “Unfortunately, aFreeRDP has stopped.”

This is my system information

System		
	Processor	Intel Core2 Quad
	CPU	Q9550  @ 2.83GHz, 4 Core
	Physical Memory (RAM)	8.00 GB
Operating System		
	System Type	x64-based PC
	OS Name	Microsoft Windows 10 Enterprise
	Version	10.0.10586 Build 10586
Programing Software		
	java version	1.8.0_72
	Android Studio	Android Studio 1.5.1
Build #AI-141.2456560, Build on December 1, 2015
JRE: 1.8.0_45-b14 amd64
JVM: Java Hotspot 64-Bit Server VM by Oracle Corporation
	Android SDK	Android SDK Manager Revision 24.4.1
Android SDK Platform-tools 23.1
Android SDK Build-tools 23.0.2
	Android NDK	r10d (64-bit)
	AVD	Nexus 4 (4.7", 768x1280xhdpi)
Android 4.2.2 -API Level 17
ARM (armeabi-v7a)
RAM 1024MB, VM Heap 64MB
Internal Storage 512MB
Use Host GPU ==> YES

I found some bugs 
1.	When I try to build app I get error iCCP error:

AAPT err(Facade for 1001587523): $AndroidStudio\freeRDPCore\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

This Error is about files bellow:
$AndroidStudio\aFreeRDP\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_ab_share_pack_holo_dark.9.png
$AndroidStudio\aFreeRDP\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_ab_share_pack_holo_light.9.png
$AndroidStudio\aFreeRDP\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_spinner_mtrl_am_alpha.9.png
$AndroidStudio\aFreeRDP\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-mdpi\abc_ab_share_pack_holo_dark.9.png
$AndroidStudio\aFreeRDP\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-xhdpi\abc_ab_share_pack_holo_dark.9.png
$AndroidStudio\aFreeRDP\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-xhdpi\abc_ab_share_pack_holo_light.9.png
$AndroidStudio\freeRDPCore\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_ab_share_pack_holo_dark.9.png
$AndroidStudio\freeRDPCore\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_ab_share_pack_holo_light.9.png
$AndroidStudio\freeRDPCore\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_spinner_mtrl_am_alpha.9.png
$AndroidStudio\freeRDPCore\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-mdpi\abc_ab_share_pack_holo_dark.9.png
$AndroidStudio\freeRDPCore\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-xhdpi\abc_ab_share_pack_holo_dark.9.png
$AndroidStudio\freeRDPCore\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-xhdpi\abc_ab_share_pack_holo_light.9.png

I use this commands to solve the problem:
pngcrush -ow -rem allb -reduce >>$FileName$<<
and
mogrify >>$FileName$<<

It works well :D

2.	I get error:
«ro.sf.lcd_density must be defined as a build property»

I try to use your app on a real device, its gone may be Emulator problem!

3.	I try to find error but every time I found nothing! So, I open your APK file as a zip and saw inside.
There is a different, your APK that I download from google play contain a Folder (>>lib >>armeabi-v7a) that contains File (>> libfreerdp-android.so)
But when I compile and make APK from (>> Build >> Build APK) there is not such a folder or file!

This is my error report on Android Studio >> Android Monitor

03-19 17:11:57.170 661-661/? E/ActivityThread: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d1a908 that was originally bound here
                                               android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d1a908 that was originally bound here
                                                   at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
                                                   at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
                                                   at android.app.ContextImpl.bindService(ContextImpl.java:1418)
                                                   at android.app.ContextImpl.bindService(ContextImpl.java:1407)
                                                   at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
                                                   at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
                                                   at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
                                                   at com.android.emailcommon.service.ServiceProxy.test(ServiceProxy.java:191)
                                                   at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1850)
                                                   at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
                                                   at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
                                                   at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                   at java.lang.Thread.run(Thread.java:856)
03-19 17:11:57.170 661-661/? E/StrictMode: null
                                           android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d1a908 that was originally bound here
                                               at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
                                               at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
                                               at android.app.ContextImpl.bindService(ContextImpl.java:1418)
                                               at android.app.ContextImpl.bindService(ContextImpl.java:1407)
                                               at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
                                               at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
                                               at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
                                               at com.android.emailcommon.service.ServiceProxy.test(ServiceProxy.java:191)
                                               at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1850)
                                               at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
                                               at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
                                               at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                               at java.lang.Thread.run(Thread.java:856)
03-19 17:11:57.190 661-661/? E/ActivityThread: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d00c90 that was originally bound here
                                               android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d00c90 that was originally bound here
                                                   at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
                                                   at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
                                                   at android.app.ContextImpl.bindService(ContextImpl.java:1418)
                                                   at android.app.ContextImpl.bindService(ContextImpl.java:1407)
                                                   at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
                                                   at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
                                                   at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
                                                   at com.android.emailcommon.service.AccountServiceProxy.getDeviceId(AccountServiceProxy.java:116)
                                                   at com.android.exchange.ExchangeService.getDeviceId(ExchangeService.java:1249)
                                                   at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1856)
                                                   at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
                                                   at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
                                                   at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                   at java.lang.Thread.run(Thread.java:856)
03-19 17:11:57.210 661-661/? E/StrictMode: null
                                           android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d00c90 that was originally bound here
                                               at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
                                               at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
                                               at android.app.ContextImpl.bindService(ContextImpl.java:1418)
                                               at android.app.ContextImpl.bindService(ContextImpl.java:1407)
                                               at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
                                               at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
                                               at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
                                               at com.android.emailcommon.service.AccountServiceProxy.getDeviceId(AccountServiceProxy.java:116)
                                               at com.android.exchange.ExchangeService.getDeviceId(ExchangeService.java:1249)
                                               at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1856)
                                               at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
                                               at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
                                               at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                               at java.lang.Thread.run(Thread.java:856)
03-19 17:12:09.321 37-436/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-19 17:12:09.501 941-941/? E/AndroidRuntime: FATAL EXCEPTION: main
                                               java.lang.UnsatisfiedLinkError: Native method not found: com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new:(Landroid/content/Context;)I
                                                   at com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new(Native Method)
                                                   at com.freerdp.freerdpcore.services.LibFreeRDP.newInstance(LibFreeRDP.java:114)
                                                   at com.freerdp.freerdpcore.application.GlobalApp.createSession(GlobalApp.java:128)
                                                   at com.freerdp.freerdpcore.presentation.SessionActivity.connect(SessionActivity.java:661)
                                                   at com.freerdp.freerdpcore.presentation.SessionActivity.processIntent(SessionActivity.java:651)
                                                   at com.freerdp.freerdpcore.presentation.SessionActivity.access$1400(SessionActivity.java:64)
                                                   at com.freerdp.freerdpcore.presentation.SessionActivity$5.onGlobalLayout(SessionActivity.java:470)
                                                   at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:655)
                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1748)
                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:562)
                                                   at android.view.Choreographer.doFrame(Choreographer.java:532)
                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
                                                   at android.os.Handler.handleCallback(Handler.java:725)
                                                   at android.os.Handler.dispatchMessage(Handler.java:92)
                                                   at android.os.Looper.loop(Looper.java:137)
                                                   at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                   at java.lang.reflect.Method.invoke(Method.java:511)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                   at dalvik.system.NativeStart.main(Native Method)
03-19 17:12:11.360 37-83/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-19 17:12:11.541 37-83/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-19 17:12:47.241 661-661/? E/ActivityThread: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d2da20 that was originally bound here
                                               android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d2da20 that was originally bound here
                                                   at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
                                                   at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
                                                   at android.app.ContextImpl.bindService(ContextImpl.java:1418)
                                                   at android.app.ContextImpl.bindService(ContextImpl.java:1407)
                                                   at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
                                                   at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
                                                   at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
                                                   at com.android.emailcommon.service.AccountServiceProxy.getDeviceId(AccountServiceProxy.java:116)
                                                   at com.android.exchange.ExchangeService.getDeviceId(ExchangeService.java:1249)
                                                   at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1856)
                                                   at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
                                                   at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
                                                   at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                   at java.lang.Thread.run(Thread.java:856)
03-19 17:12:47.261 661-661/? E/StrictMode: null
                                           android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d2da20 that was originally bound here
                                               at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
                                               at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
                                               at android.app.ContextImpl.bindService(ContextImpl.java:1418)
                                               at android.app.ContextImpl.bindService(ContextImpl.java:1407)
                                               at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
                                               at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
                                               at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
                                               at com.android.emailcommon.service.AccountServiceProxy.getDeviceId(AccountServiceProxy.java:116)
                                               at com.android.exchange.ExchangeService.getDeviceId(ExchangeService.java:1249)
                                               at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1856)
                                               at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
                                               at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
                                               at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                               at java.lang.Thread.run(Thread.java:856)
03-19 17:12:47.270 661-661/? E/ActivityThread: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d450c8 that was originally bound here
                                               android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d450c8 that was originally bound here
                                                   at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
                                                   at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
                                                   at android.app.ContextImpl.bindService(ContextImpl.java:1418)
                                                   at android.app.ContextImpl.bindService(ContextImpl.java:1407)
                                                   at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
                                                   at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
                                                   at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
                                                   at com.android.emailcommon.service.ServiceProxy.test(ServiceProxy.java:191)
                                                   at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1850)
                                                   at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
                                                   at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
                                                   at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                   at java.lang.Thread.run(Thread.java:856)
03-19 17:12:47.311 661-661/? E/StrictMode: null
                                           android.app.ServiceConnectionLeaked: Service com.android.exchange.ExchangeService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@40d450c8 that was originally bound here
                                               at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:969)
                                               at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:863)
                                               at android.app.ContextImpl.bindService(ContextImpl.java:1418)
                                               at android.app.ContextImpl.bindService(ContextImpl.java:1407)
                                               at android.content.ContextWrapper.bindService(ContextWrapper.java:473)
                                               at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:157)
                                               at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:145)
                                               at com.android.emailcommon.service.ServiceProxy.test(ServiceProxy.java:191)
                                               at com.android.exchange.ExchangeService$7.run(ExchangeService.java:1850)
                                               at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:551)
                                               at com.android.emailcommon.utility.Utility$2.doInBackground(Utility.java:549)
                                               at android.os.AsyncTask$2.call(AsyncTask.java:287)
                                               at java.util.concurrent.FutureTask.run(FutureTask.java:234)
                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                               at java.lang.Thread.run(Thread.java:856)

											   
											   
											   
I still get error “Unfortunately, aFreeRDP has stopped.”
What should I do??

Best Regards

**Comment by akallabeth** [comment]
@amater2048 there is a readme for android in the docs folder ;) you have to run the build script for the native libraries in the scripts folder first.

**Comment by akallabeth** [comment]
@amater2048 Does this solve your issue?

**Comment by amater2048** [comment]
Thanks for your help, but I still have problems.

My try to run build-script in a windows system was unsuccessful so I provide another system.
I install Linux Ubuntu 15.10 and do all configuration as it must be!
Then I run ./scripts/android-build-freerdp.sh
everything builds successfully!

After that, I copy whole folder and then import it to «Android Studio» in a windows system. The error has gone!

I found another error that cause services disconnect suddenly.

This Error is about files bellow:
03-27 17:29:00.252 28670-28670/? A/libc: Fatal signal 13 (SIGPIPE) at 0x00006ffe (code=0), thread 28670 (getprop)
03-27 17:29:00.317 28631-28631/? E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
03-27 17:29:00.317 28631-28631/? E/SpannableStringBuilder: SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
03-27 17:29:05.652 2128-2321/? E/Watchdog: !@Sync 4540
03-27 17:29:09.167 28631-28663/? E/com.freerdp.core.orders: [pid=28631:tid=4ef1deb8] - ORDER_TYPE_GDIPLUS_END - update_read_draw_gdiplus_end_order() failed
03-27 17:29:09.167 28631-28663/? E/com.freerdp.core.fastpath: [pid=28631:tid=4ef1deb8] - FASTPATH_UPDATETYPE_ORDERS - fastpath_recv_orders()
03-27 17:29:09.167 28631-28663/? E/com.freerdp.core.fastpath: [pid=28631:tid=4ef1deb8] - fastpath_recv_update() - -1
03-27 17:29:09.172 28631-28663/? E/com.freerdp.core.fastpath: [pid=28631:tid=4ef1deb8] - fastpath_recv_update_data() fail
03-27 17:29:09.172 28631-28663/? E/com.freerdp.core.transport: [pid=28631:tid=4ef1deb8] - transport_check_fds: transport->ReceiveCallback() - -1
03-27 17:29:09.172 28631-28663/? E/com.freerdp.core: [pid=28631:tid=4ef1deb8] - freerdp_check_fds() failed - 0
03-27 17:29:09.172 28631-28663/? E/com.freerdp.client.android: [pid=28631:tid=4ef1deb8] - Failed to check FreeRDP file descriptor
03-27 17:29:09.172 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.172 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.172 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.177 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.182 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap index: 0x3F00
03-27 17:29:09.182 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.182 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.182 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.187 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.192 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.192 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.192 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.217 28631-28726/? E/com.freerdp.cache.offscreen: [pid=28631:tid=4e778a08] - invalid offscreen bitmap at index: 0x0000
03-27 17:29:09.222 28631-28666/? E/com.freerdp.core.orders: [pid=28631:tid=4ef5bf18] - Stream_GetRemainingLength(s) < 1
03-27 17:29:09.222 28631-28666/? E/com.freerdp.core.fastpath: [pid=28631:tid=4ef5bf18] - FASTPATH_UPDATETYPE_ORDERS - fastpath_recv_orders()
03-27 17:29:09.222 28631-28666/? E/com.freerdp.core.fastpath: [pid=28631:tid=4ef5bf18] - fastpath_recv_update() - -1
03-27 17:29:09.222 28631-28666/? E/com.freerdp.core.fastpath: [pid=28631:tid=4ef5bf18] - fastpath_recv_update_data() fail
03-27 17:29:09.227 28631-28726/? A/libc: Fatal signal 11 (SIGSEGV) at 0x000000fc (code=1), thread 28726 (Thread-2751)
03-27 17:29:09.232 28631-28666/? E/com.freerdp.core.transport: [pid=28631:tid=4ef5bf18] - transport_check_fds: transport->ReceiveCallback() - -1
03-27 17:29:09.232 28631-28666/? E/com.freerdp.core: [pid=28631:tid=4ef5bf18] - freerdp_check_fds() failed - 0
03-27 17:29:09.232 28631-28666/? E/com.freerdp.core.transport: [pid=28631:tid=4ef5bf18] - freerdp_check_event_handles()
03-27 17:29:13.352 3450-3450/? E/SPPClientService: [[PushClientService]] F:false, D:false, E:false, T:false, S:true, R:false
03-27 17:29:19.692 2128-2198/? E/InputDispatcher: channel ~ Channel is unrecoverably broken and will be disposed!

Best Regards

**Comment by amater2048** [comment]
It looks happen because of screen Resolution conflict, by change the screen resolution; the error changes but still application closes suddenly every time!!!

**Comment by akallabeth** [comment]
@amater2048 android builds are currently linux only tested. feel free to provide a windows build script. as for your other issues, there are known issues with async transport. everything else build / usage related please ask on the mailing list and/or irc channel. thanks!
