### ISSUE TITLE
the apk cannot work on android device

### ISSUE THREAD

**Issue by minenlink** [FreeRDP/FreeRDP#3691]
hi,
I get the apk from "https://ci.freerdp.com/view/Builders/job/android/ws/source/client/Android/Studio/aFreeRDP/build/outputs/apk/",but it crashed on my android
device。
I have already build the code by "FreeRDP/docs/README.android",build success.but the apk still crashed.
now,I want to get a useful apk and the code,how can i do?

The crash log:

01-11 10:07:52.125 23729-23729/com.freerdp.afreerdp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      java.lang.UnsatisfiedLinkError: Native method not found: com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new:(Landroid/content/Context;)J
                                                                          at com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new(Native Method)
                                                                          at com.freerdp.freerdpcore.services.LibFreeRDP.newInstance(LibFreeRDP.java:116)
                                                                          at com.freerdp.freerdpcore.application.GlobalApp.createSession(GlobalApp.java:128)
                                                                          at com.freerdp.freerdpcore.presentation.SessionActivity.connect(SessionActivity.java:661)
                                                                          at com.freerdp.freerdpcore.presentation.SessionActivity.processIntent(SessionActivity.java:651)
                                                                          at com.freerdp.freerdpcore.presentation.SessionActivity.access$1400(SessionActivity.java:64)
                                                                          at com.freerdp.freerdpcore.presentation.SessionActivity$5.onGlobalLayout(SessionActivity.java:470)
                                                                          at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:655)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1752)
                                                                          at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:993)
                                                                          at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4359)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:779)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:592)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:562)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:765)
                                                                          at android.os.Handler.handleCallback(Handler.java:725)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                          at android.os.Looper.loop(Looper.java:137)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5039)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:511)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                          at dalvik.system.NativeStart.main(Native Method)

**Comment by akallabeth** [comment]
This is a issue tracker, for support ask on the mailing list or IRC.
Side node: Check, if the APK contains the required .so files for a start.

**Comment by bmiklautz** [comment]
@minenlink while the apks build during the integration test might work they are not intended to be used and therefore not tested in any kind.

**Comment by minenlink** [comment]
@akallabeth  thanks for your answer.but ,how can i get a useful and lastest android version?

**Comment by akallabeth** [comment]
you need to build it yourself. just follow the readme and you should have an apk ready for use.

**Comment by akallabeth** [comment]
@minenlink Oh, and don't forget to adjust the ```scripts/android-build.conf``` according your API requirements (default is API 21 which is the minimum required for the 64 bit architectures)
