### ISSUE TITLE
Segfault when using remote folder redirection after PR#3864

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#3908]
After merge of PR #3864, xfreerdp crashes with SIGSEGV when using remote disk redirection.

To reproduce, tested on ubuntu 16.04 connecting to windows 10 Pro v1607, use
```xfreerdp /v:192.168.56.2 /drive:MyRemoteDrive,/home/giovanni/Documenti /u:auser /d:thedom```

Then browse the remote drive MyRemoteDrive and try to create a folder.

xfreerdp crashes with
```
Thread 9 "xfreerdp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffde9fb700 (LWP 9385)]
0x00007ffff5dfe5b6 in FindClose (hFindFile=0x1) at /home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/generic.c:1029
1029			free(pFileSearch->lpPath);
(gdb) bt
#0  0x00007ffff5dfe5b6 in FindClose (hFindFile=0x1) at /home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/generic.c:1029
#1  0x00007ffff5dfcd32 in GetFileAttributesExA (lpFileName=0x7fffd40029b0 "/home/giovanni/Documenti", fInfoLevelId=GetFileExInfoStandard, 
    lpFileInformation=0x7fffde9fabb0) at /home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/generic.c:479
#2  0x00007ffff5dfce2e in GetFileAttributesExW (lpFileName=0x7fffd8000c10, fInfoLevelId=GetFileExInfoStandard, lpFileInformation=0x7fffde9fabb0)
    at /home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/generic.c:502
#3  0x00007ffff69f834a in drive_process_irp_query_volume_information (drive=0x7fffd8000b40, irp=0x7fffd80016e0)
    at /home/giovanni/remmina_devel/FreeRDP/channels/drive/client/drive_main.c:442
#4  0x00007ffff69f8cd9 in drive_process_irp (drive=0x7fffd8000b40, irp=0x7fffd80016e0)
    at /home/giovanni/remmina_devel/FreeRDP/channels/drive/client/drive_main.c:660
#5  0x00007ffff69f8ed3 in drive_thread_func (arg=0x7fffd8000b40) at /home/giovanni/remmina_devel/FreeRDP/channels/drive/client/drive_main.c:713
#6  0x00007ffff5e4cb47 in thread_launcher (arg=0x7fffd8001420) at /home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/thread/thread.c:320
#7  0x00007ffff53c36ba in start_thread (arg=0x7fffde9fb700) at pthread_create.c:333
#8  0x00007ffff5b0582d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
Previous commit, a2a7d71, is not affected.

Also reported by Remmina user here:  https://github.com/FreeRDP/Remmina/issues/1157

**Comment by giox069** [comment]
PR https://github.com/FreeRDP/FreeRDP/pull/3902 seems to fix it :)

**Comment by akallabeth** [comment]
@giox069 Thank you, waiting for someone to merge that pr ;)
