### ISSUE TITLE
Shadow server segfaults when starting

### ISSUE THREAD

**Issue by DamienCassou** [FreeRDP/FreeRDP#4094]
I tried freerdp-shadow-cli from the Fedora26 official repository, from my own build and from your Jenkins CI server. They all crash the same:

```
$ /opt/freerdp-nightly/bin/freerdp-shadow-cli
Segmentation fault (core dumped)
```

It happens immediately after start.

**Comment by DamienCassou** [comment]
```
$ WLOG_LEVEL=TRACE  /opt/freerdp-nightly/bin/freerdp-shadow-cli
Segmentation fault (core dumped)
```

**Comment by hardening** [comment]
Hi, could you run that with valgrind so that we have an idea of the culprid ?

**Comment by bmiklautz** [comment]
If you can provide us with the following information it would be great:
```
valgrind --leak-check=full  /opt/freerdp-nightly/bin/freerdp-shadow-cli
```
```
gdb /opt/freerdp-nightly/bin/freerdp-shadow-cli
# type 'r' to run the program
# if the crash happened type 'thread apply all bt'
```

**Comment by DamienCassou** [comment]
```session
$ valgrind --leak-check=full  /opt/freerdp-nightly/bin/freerdp-shadow-cli
==15523== Memcheck, a memory error detector
==15523== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==15523== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==15523== Command: /opt/freerdp-nightly/bin/freerdp-shadow-cli
==15523== 
==15523== Invalid read of size 8
==15523==    at 0x73E5630: RSA_generate_key_ex (in /usr/lib64/libcrypto.so.1.1.0f)
==15523==    by 0x6BE30F3: makecert_context_process (in /opt/freerdp-nightly/lib64/libwinpr-tools2.so.2.0.0)
==15523==    by 0x504CEDA: shadow_server_init (in /opt/freerdp-nightly/lib64/libfreerdp-shadow2.so.2.0.0)
==15523==    by 0x108CDC: ??? (in /opt/freerdp-nightly/bin/freerdp-shadow-cli)
==15523==    by 0x556A4D9: (below main) (in /usr/lib64/libc-2.25.so)
==15523==  Address 0x10 is not stack'd, malloc'd or (recently) free'd
==15523== 
==15523== 
==15523== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==15523==  Access not within mapped region at address 0x10
==15523==    at 0x73E5630: RSA_generate_key_ex (in /usr/lib64/libcrypto.so.1.1.0f)
==15523==    by 0x6BE30F3: makecert_context_process (in /opt/freerdp-nightly/lib64/libwinpr-tools2.so.2.0.0)
==15523==    by 0x504CEDA: shadow_server_init (in /opt/freerdp-nightly/lib64/libfreerdp-shadow2.so.2.0.0)
==15523==    by 0x108CDC: ??? (in /opt/freerdp-nightly/bin/freerdp-shadow-cli)
==15523==    by 0x556A4D9: (below main) (in /usr/lib64/libc-2.25.so)
==15523==  If you believe this happened as a result of a stack
==15523==  overflow in your program's main thread (unlikely but
==15523==  possible), you can try to increase the size of the
==15523==  main thread stack using the --main-stacksize= flag.
==15523==  The main thread stack size used in this run was 8720384.
==15523== 
==15523== HEAP SUMMARY:
==15523==     in use at exit: 155,614 bytes in 3,315 blocks
==15523==   total heap usage: 3,422 allocs, 107 frees, 180,852 bytes allocated
==15523== 
==15523== LEAK SUMMARY:
==15523==    definitely lost: 0 bytes in 0 blocks
==15523==    indirectly lost: 0 bytes in 0 blocks
==15523==      possibly lost: 0 bytes in 0 blocks
==15523==    still reachable: 155,614 bytes in 3,315 blocks
==15523==         suppressed: 0 bytes in 0 blocks
==15523== Reachable blocks (those to which a pointer was found) are not shown.
==15523== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==15523== 
==15523== For counts of detected and suppressed errors, rerun with: -v
==15523== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
```

```
$ gdb /opt/freerdp-nightly/bin/freerdp-shadow-cli
GNU gdb (GDB) Fedora 8.0-20.fc26
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/freerdp-nightly/bin/freerdp-shadow-cli...Reading symbols from /usr/lib/debug/opt/freerdp-nightly/bin/freerdp-shadow-cli.debug...done.
done.
(gdb) r
Starting program: /opt/freerdp-nightly/bin/freerdp-shadow-cli 
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.25-7.fc26.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007f529548e630 in RSA_generate_key_ex () from /lib64/libcrypto.so.1.1
Missing separate debuginfos, use: dnf debuginfo-install libX11-1.6.5-2.fc26.x86_64 libXau-1.0.8-7.fc26.x86_64 libXdamage-1.1.4-9.fc26.x86_64 libXext-1.3.3-5.fc26.x86_64 libXfixes-5.0.3-2.fc26.x86_64 libXi-1.7.9-2.fc26.x86_64 libXinerama-1.1.3-7.fc26.x86_64 libXtst-1.2.3-2.fc26.x86_64 libcap-2.25-5.fc26.x86_64 libgcc-7.1.1-3.fc26.x86_64 libgcrypt-1.7.8-1.fc26.x86_64 libgpg-error-1.25-2.fc26.x86_64 libjpeg-turbo-1.5.1-0.fc26.x86_64 libselinux-2.6-7.fc26.x86_64 libxcb-1.12-3.fc26.x86_64 libxkbfile-1.0.9-4.fc26.x86_64 lz4-libs-1.7.5-4.fc26.x86_64 openssl-libs-1.1.0f-7.fc26.x86_64 pcre-8.41-1.fc26.x86_64 systemd-libs-233-6.fc26.x86_64 xz-libs-5.2.3-2.fc26.x86_64 zlib-1.2.11-2.fc26.x86_64
(gdb) thread apply all bt

Thread 1 (Thread 0x7f5297cff8c0 (LWP 15863)):
#0  0x00007f529548e630 in RSA_generate_key_ex () from /lib64/libcrypto.so.1.1
#1  0x00007f5295c060f4 in makecert_context_process (context=context@entry=0x10022f630, argc=argc@entry=6, 
    argv=argv@entry=0x7fffffffe060) at /usr/src/debug/freerdp-nightly-2.0/winpr/tools/makecert/makecert.c:1022
#2  0x00007f529779eedb in shadow_server_init_certificate (server=0x100203040)
    at /usr/src/debug/freerdp-nightly-2.0/server/shadow/shadow_server.c:639
#3  shadow_server_init (server=0x100203040) at /usr/src/debug/freerdp-nightly-2.0/server/shadow/shadow_server.c:685
#4  0x0000000100000cdd in main (argc=1, argv=0x7fffffffe1e8) at /usr/src/debug/freerdp-nightly-2.0/server/shadow/shadow.c:79
(gdb) 
```

**Comment by bmiklautz** [comment]
@DamienCassou we think it's fixed on the current master (should be in tomorrows nightly).

**Comment by DamienCassou** [comment]
Thanks for your quick reaction, this gives a really good feeling. I pull and rebuilt. The bug disappeared. Good job.

**Comment by DamienCassou** [comment]
I reopened because I was not sure it is in your process to let users close issues. Feel free to close it.

**Comment by hardening** [comment]
We do let users close their own bugs.
