### ISSUE TITLE
xfreerdp start consume 100% CPU if trying connect to disabled RDP

### ISSUE THREAD

**Issue by NTMan** [FreeRDP/FreeRDP#4174]
```
$ xfreerdp --version
This is FreeRDP version 2.0.0-dev (git n/a)
```

How reproduce:
1) Connect to worked Windows host.
2) Enter in windows terminal command for reboot:
```shutdown /r /t 0```
3) now xfreerdp will be closed
```[02:21:30:930] [17050:17051] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.```
4) Without waiting when Windows started again try connect again.
Here got 100% CPU load and messages in terminal:
```
$ xfreerdp /v:host /u:login@domain
Password: 
[02:24:43:409] [18401:18402] [ERROR][com.winpr.timezone] - Unable to get current timezone rule
[02:24:43:463] [18401:18402] [INFO][com.freerdp.client.x11] - Logon Error Info SESSION_ID [UNKNOWN]
[02:24:43:463] [18401:18402] [INFO][com.freerdp.client.x11] - Logon Error Info SESSION_ID [UNKNOWN]
[02:24:43:463] [18401:18402] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
```

This is backtrace:
```
(gdb) thread apply all bt

Thread 2 (Thread 0x7fec587ec700 (LWP 18402)):
#0  0x00007fec62fd9bcb in __GI___poll (fds=fds@entry=0x7fec587eb8c0, nfds=nfds@entry=1, timeout=timeout@entry=0) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fec632e19c8 in poll (__timeout=0, __nfds=1, __fds=0x7fec587eb8c0) at /usr/include/bits/poll2.h:46
#2  waitOnFd (dwMilliseconds=0, mode=<optimized out>, fd=<optimized out>) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/winpr/libwinpr/synch/wait.c:197
#3  WaitForSingleObject (hHandle=0x55e6dd3d1460, dwMilliseconds=dwMilliseconds@entry=0) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/winpr/libwinpr/synch/wait.c:296
#4  0x00007fec63b6ec81 in freerdp_shall_disconnect (instance=<optimized out>) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/libfreerdp/core/freerdp.c:518
#5  0x00007fec63b8bbe2 in transport_check_fds (transport=transport@entry=0x55e6dd3af3f0) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/libfreerdp/core/transport.c:1000
#6  0x00007fec63b83908 in rdp_check_fds (rdp=rdp@entry=0x55e6dd3a1800) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/libfreerdp/core/rdp.c:1505
#7  0x00007fec63b7a900 in rdp_client_connect (rdp=rdp@entry=0x55e6dd3a1800) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/libfreerdp/core/connection.c:290
#8  0x00007fec63b6f9e0 in freerdp_connect (instance=instance@entry=0x55e6dd37b7b0) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/libfreerdp/core/freerdp.c:189
#9  0x000055e6dc5bf86f in xf_client_thread (param=0x55e6dd37b7b0) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/client/X11/xf_client.c:1473
#10 0x00007fec6331aee1 in thread_launcher (arg=0x55e6dd3e3500) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/winpr/libwinpr/thread/thread.c:320
#11 0x00007fec62888609 in start_thread (arg=0x7fec587ec700) at pthread_create.c:465
#12 0x00007fec62fe617f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fec654108c0 (LWP 18401)):
#0  0x00007fec62fd9bcb in __GI___poll (fds=fds@entry=0x7ffe2f8e2940, nfds=nfds@entry=1, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fec632e19c8 in poll (__timeout=-1, __nfds=1, __fds=0x7ffe2f8e2940) at /usr/include/bits/poll2.h:46
#2  waitOnFd (dwMilliseconds=4294967295, mode=<optimized out>, fd=<optimized out>) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/winpr/libwinpr/synch/wait.c:197
#3  WaitForSingleObject (hHandle=0x55e6dd3e3500, dwMilliseconds=4294967295) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/winpr/libwinpr/synch/wait.c:296
#4  0x000055e6dc5ad946 in main (argc=<optimized out>, argv=0x7ffe2f8e2af8) at /usr/src/debug/freerdp-2.0.0-34.20170831git3b83526.fc27.x86_64/client/X11/cli/xfreerdp.c:75
(gdb) 

```

**Comment by akallabeth** [comment]
@NTMan Thank you for your report. Could you just clarify a few things:
* You're using Fedora24 packages or some custom builds?
* Does this also occur with our nightly builds?
* Does this hang forever or does it exit after some time?

**Comment by NTMan** [comment]
This is fresh Fedora 27 installation. xfreerdp package is not custome.
$ xfreerdp --version
This is FreeRDP version 2.0.0-dev (git n/a)
This hang is ever reproducible by described above instruction.

**Comment by akallabeth** [comment]
@NTMan Ok, tried with your instructions, I don't get the logoff by user with the hang. Maybe missing some detail here? What OS version is your windows machine running? You're in a domain, right?

**Comment by NTMan** [comment]
For reproduction needed restart windows not log off. It can be possible via RDP only from cmd.
1) launch cmd
2) in teminal on Window system enter command ```shutdown /r /t 0```
after this step RPD window would be closed and for reproduction needed launch again ```xfreerdp /v:host /u:login@domain``` until windows not loaded again.
May be your Windows restart so quickly?

**Comment by akallabeth** [comment]
@NTMan Did the restart stuff. When I connect afterward I get either a negotiation error (host not up and running) or am connected to the host again. (depending if the system has already set up network or not on restart)

**Comment by akallabeth** [comment]
@NTMan I've had a fresh look at the code, could you test the procedure with our nightly builds? It is most likely a known bug that has already been fixed but did not make it to a new release so far.

**Comment by hardening** [comment]
yes that sounds like the freshly fixed bug in https://github.com/FreeRDP/FreeRDP/pull/4136

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
