### ISSUE TITLE
xfreerdp “Segmentation fault” when connecting to freerdp-shadow-cli 

### ISSUE THREAD

**Issue by daixj-shterm** [FreeRDP/FreeRDP#4291]
I am a newbie here. I am trying freerdp-shadow-cli as a rdp server, and use xfreerdp to connect it.
freerdp-shadow-cli and xfreerdp were built from the master branch.

I try to run freerdp-shadow-cli for sharing a VNC display, like this:
```
# netstat -ltnp | grep vnc
tcp        0      0 0.0.0.0:5904            0.0.0.0:*               LISTEN      60882/Xvnc          
tcp        0      0 0.0.0.0:6004            0.0.0.0:*               LISTEN      60882/Xvnc 
# freerdp-shadow-cli -auth /monitors:4
[21:00:37:555] [69326:69326] [INFO][com.freerdp.server.shadow.x11] - X11 Extensions: XFixes: 1 Xinerama: 0 XDamage: 0 XShm: 0
[21:00:37:557] [69326:69326] [INFO][com.freerdp.core.listener] - Listening on 0.0.0.0:3389
...
```
When run xfreerdp to connect it, the "Segmentation fault" happened
```
[root@localhost x264]# xfreerdp /v:127.0.0.1
[20:02:15:868] [68763:68764] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[20:02:15:868] [68763:68764] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: root
[20:02:16:145] [68763:68764] [INFO][com.freerdp.client.x11] - Property 173 does not exist
[20:02:16:268] [68763:68764] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[20:02:16:268] [68763:68764] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
Segmentation fault (core dumped)
```
More information:
```
[root@localhost x264]# gdb xfreerdp
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-100.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/bin/xfreerdp...done.
(gdb) set args /v:127.0.0.1
(gdb) run
Starting program: /usr/local/bin/xfreerdp /v:127.0.0.1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe867f700 (LWP 68792)]
[20:03:03:611] [68788:68792] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[20:03:03:612] [68788:68792] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: root
Detaching after fork from child process 68793.
Detaching after fork from child process 68794.
[20:03:03:905] [68788:68792] [INFO][com.freerdp.client.x11] - Property 173 does not exist
[20:03:04:026] [68788:68792] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[20:03:04:026] [68788:68792] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe867f700 (LWP 68792)]
0x00007ffff6633cc5 in gdi_init_primary (gdi=0x7fffe0044e50, stride=0, format=537135240, buffer=0x0, pfree=0x7ffff5e6fab0 <_aligned_free>)
    at /root/work/FreeRDP/libfreerdp/gdi/gdi.c:1152
1152		gdi->stride = gdi->primary->bitmap->scanline;
(gdb) bt
#0  0x00007ffff6633cc5 in gdi_init_primary (gdi=0x7fffe0044e50, stride=0, format=537135240, buffer=0x0, 
    pfree=0x7ffff5e6fab0 <_aligned_free>) at /root/work/FreeRDP/libfreerdp/gdi/gdi.c:1152
#1  0x00007ffff663423c in gdi_init_ex (instance=0x6ae620, format=537135240, stride=0, buffer=0x0, pfree=0x7ffff5e6fab0 <_aligned_free>)
    at /root/work/FreeRDP/libfreerdp/gdi/gdi.c:1259
#2  0x00007ffff6634017 in gdi_init (instance=0x6ae620, format=537135240) at /root/work/FreeRDP/libfreerdp/gdi/gdi.c:1225
#3  0x0000000000421eb3 in xf_post_connect (instance=0x6ae620) at /root/work/FreeRDP/client/X11/xf_client.c:1198
#4  0x00007ffff667ca02 in freerdp_connect (instance=0x6ae620) at /root/work/FreeRDP/libfreerdp/core/freerdp.c:214
#5  0x00000000004228bf in xf_client_thread (param=0x6ae620) at /root/work/FreeRDP/client/X11/xf_client.c:1458
#6  0x00007ffff5e57ce6 in thread_launcher (arg=0x6f2180) at /root/work/FreeRDP/winpr/libwinpr/thread/thread.c:319
#7  0x00007ffff53d2e25 in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff5b0b34d in clone () from /lib64/libc.so.6
(gdb) info registers 
rax            0x0	0
rbx            0x7fffe00452e0	140736951767776
rcx            0x7fffe0045400	140736951768064
rdx            0xffffffff	4294967295
rsi            0x7fffe0000030	140736951484464
rdi            0x7fffe0000020	140736951484448
rbp            0x7fffe867e8d0	0x7fffe867e8d0
rsp            0x7fffe867e8a0	0x7fffe867e8a0
r8             0x0	0
r9             0x7fffe0045490	140736951768208
r10            0x7fffe867e550	140737092511056
r11            0x7ffff5e6f646	140737318942278
r12            0x1	1
r13            0x7fffe867f9c0	140737092516288
r14            0x7fffe867f700	140737092515584
r15            0x0	0
rip            0x7ffff6633cc5	0x7ffff6633cc5 <gdi_init_primary+321>
eflags         0x10206	[ PF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) x /16i gdi_init_primary
...
   0x7ffff6633ca5 <gdi_init_primary+289>:	mov    %rdi,%r8
   0x7ffff6633ca8 <gdi_init_primary+292>:	mov    %eax,%edi
   0x7ffff6633caa <gdi_init_primary+294>:	callq  0x7ffff66145f0 <gdi_CreateBitmapEx@plt>
   0x7ffff6633caf <gdi_init_primary+299>:	mov    %rax,0x128(%rbx)
   0x7ffff6633cb6 <gdi_init_primary+306>:	mov    -0x18(%rbp),%rax
   0x7ffff6633cba <gdi_init_primary+310>:	mov    0x28(%rax),%rax
   0x7ffff6633cbe <gdi_init_primary+314>:	mov    0x128(%rax),%rax
=> 0x7ffff6633cc5 <gdi_init_primary+321>:	mov    0x10(%rax),%edx
   0x7ffff6633cc8 <gdi_init_primary+324>:	mov    -0x18(%rbp),%rax
   0x7ffff6633ccc <gdi_init_primary+328>:	mov    %edx,0x10(%rax)
   0x7ffff6633ccf <gdi_init_primary+331>:	mov    -0x18(%rbp),%rax
   0x7ffff6633cd3 <gdi_init_primary+335>:	mov    0x28(%rax),%rax
   0x7ffff6633cd7 <gdi_init_primary+339>:	mov    0x128(%rax),%rax
   0x7ffff6633cde <gdi_init_primary+346>:	test   %rax,%rax
   0x7ffff6633ce1 <gdi_init_primary+349>:	jne    0x7ffff6633ce8 <gdi_init_primary+356>
   0x7ffff6633ce3 <gdi_init_primary+351>:	jmpq   0x7ffff6633e7f <gdi_init_primary+763>
```
Here is the code:
```
1139         if (!buffer)
1140         {
1141                 gdi->primary->bitmap = gdi_CreateCompatibleBitmap(
1142                                            gdi->hdc, gdi->width, gdi->height);
1143         }
1144         else
1145         {
1146                 gdi->primary->bitmap = gdi_CreateBitmapEx(gdi->width, gdi->height,
1147                                        gdi->dstFormat,
1148                                        gdi->stride,
1149                                        buffer, pfree);
1150         }
1151 
1152         gdi->stride = gdi->primary->bitmap->scanline;
1153 
1154         if (!gdi->primary->bitmap)
1155                 goto fail_bitmap;
1156 
1157         gdi_SelectObject(gdi->primary->hdc, (HGDIOBJECT) gdi->primary->bitmap);
```
I try to fix it like this, the "Segmentation fault" do not show again.
```
diff --git a/libfreerdp/gdi/gdi.c b/libfreerdp/gdi/gdi.c
index e099ecf..af6ac5a 100644
--- a/libfreerdp/gdi/gdi.c
+++ b/libfreerdp/gdi/gdi.c
@@ -1149,11 +1149,11 @@ static BOOL gdi_init_primary(rdpGdi* gdi, UINT32 stride, UINT32 format,
                                       buffer, pfree);
        }
 
-       gdi->stride = gdi->primary->bitmap->scanline;
-
        if (!gdi->primary->bitmap)
                goto fail_bitmap;
 
+       gdi->stride = gdi->primary->bitmap->scanline;
+
        gdi_SelectObject(gdi->primary->hdc, (HGDIOBJECT) gdi->primary->bitmap);
        gdi->primary->org_bitmap = NULL;
        gdi->primary_buffer = gdi->primary->bitmap->data;
```

**Comment by bmiklautz** [comment]
@daixj-shterm thanks for the report and for your effort. Nice finding a segfault shouldn't happen in any case.  For completeness would you be so nice and add the git commit you tested with?

**Comment by daixj-shterm** [comment]
@bmiklautz Thanks for your reply. Here is the diff file, is it you want ?

[Issues4291-xfreerdp-Segfault.patch.txt](https://github.com/FreeRDP/FreeRDP/files/1513110/Issues4291-xfreerdp-Segfault.patch.txt)

**Comment by akallabeth** [comment]
@daixj-shterm I've just tried to reproduce your test environment, but currently fail to do so.
 Can you tell, by any chance, how you end up with ```gdi->primary->bitmap == NULL```?
