### ISSUE TITLE
[X11] shadow server memory corruption with /monitors:2

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#4293]
1. Compile with address sanitizer 
1. Start ```freerdp-shadow-cli -auth /port:3390 /monitors:2```

```[13:47:11:010] [1864:1864] [INFO][com.freerdp.server.shadow.x11] - X11 Extensions: XFixes: 1 Xinerama: 1 XDamage: 0 XShm: 0
=================================================================
==1864==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200000e171 at pc 0x7f598efa562d bp 0x7fffa5393ab0 sp 0x7fffa5393aa8
READ of size 1 at 0x60200000e171 thread T0
    #0 0x7f598efa562c in rdtk_font_draw_text (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x2062c)
    #1 0x7f598efa3bcd in rdtk_label_draw (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x1ebcd)
    #2 0x7f598ef9801c in shadow_client_init_lobby (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x1301c)
    #3 0x7f598ef98c1d in shadow_screen_new (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x13c1d)
    #4 0x7f598efa22be in shadow_server_start (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x1d2be)
    #5 0x5584122b8412 in main (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/freerdp-shadow-cli+0x1412)
    #6 0x7f598e7b42b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #7 0x5584122b8749 in _start (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/freerdp-shadow-cli+0x1749)

0x60200000e171 is located 0 bytes to the right of 1-byte region [0x60200000e170,0x60200000e171)
allocated by thread T0 here:
    #0 0x7f598f486ed0 in calloc (/usr/lib/x86_64-linux-gnu/libasan.so.3+0xc1ed0)
    #1 0x7f598ef99209 in shadow_surface_new (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x14209)
    #2 0x7f598ef98bd6 in shadow_screen_new (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x13bd6)
    #3 0x7f598efa22be in shadow_server_start (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x1d2be)
    #4 0x5584122b8412 in main (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/freerdp-shadow-cli+0x1412)
    #5 0x7f598e7b42b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/nin/Downloads/freerdp-2.0.0-rc1/freerdp-2.0.0-rc1/server/shadow/libfreerdp-shadow2.so.2+0x2062c) in rdtk_font_draw_text
Shadow bytes around the buggy address:
  0x0c047fff9bd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9be0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047fff9bf0: fa fa fa fa fa fa fa fa fa fa 00 00 fa fa 00 00
  0x0c047fff9c00: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fd
  0x0c047fff9c10: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 00 fa
=>0x0c047fff9c20: fa fa fd fa fa fa fd fa fa fa fd fa fa fa[01]fa
  0x0c047fff9c30: fa fa 01 fa fa fa 00 07 fa fa 00 00 fa fa 00 00
  0x0c047fff9c40: fa fa 01 fa fa fa 01 fa fa fa fd fd fa fa fd fd
  0x0c047fff9c50: fa fa 07 fa fa fa fd fd fa fa 00 fa fa fa fd fd
  0x0c047fff9c60: fa fa fd fd fa fa 00 01 fa fa fd fd fa fa fd fa
  0x0c047fff9c70: fa fa fd fa fa fa fd fd fa fa fd fd fa fa 07 fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1864==ABORTING
```

**Comment by akallabeth** [comment]
Fixed with #4294
