### ISSUE TITLE
Error only when using full path: ==3916==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x60b0000107b0 in thread T1

### ISSUE THREAD

**Issue by OriginalFlavor** [FreeRDP/FreeRDP#4431]
When I launch xfreerdp using the full path (i.e. `/opt/freerdp-nightly/bin/xfreerdp`) I receive the error `==3916==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x60b0000107b0 in thread T1`
When I navigate to the path (i.e. cd /opt/freerdp-nightly/bin) and launch xfreerdp then the application launches perfectly.

command line you have used:
/opt/freerdp-nightly/bin/xfreerdp /v:remote.hostname.com /u:username /multimon Produces the error
from the /opt/freerdp-nightly/bin directory:
xfreerdp /v:remote.hostname.com /u:username /multimon No error

To what system did you connect to? Windows Server 2008 R2 Standard
What did you expect to happen? I expected to be prompted for my password, then have a remote desktop on two monitors.

What actually happened?
I was prompted for my password, then I received the following text in the terminal:
```
/opt/freerdp-nightly/bin/xfreerdp /v:remote.hostname.com /u:username /multimon
[13:03:45:387] [3916:3917] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
Password: 
[13:03:55:010] [3916:3917] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[13:03:55:010] [3916:3917] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[13:03:55:093] [3916:3917] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
=================================================================
==3916==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x60b0000107b0 in thread T1
    #0 0x7f733a2d17b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x7f7339ed911c  (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x2611c)
    #2 0x559173a690b7  (/opt/freerdp-nightly/bin/xfreerdp+0x3d0b7)
    #3 0x7f733862d487  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x14a487)
    #4 0x7f733859f9f4  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0xbc9f4)
    #5 0x7f733866637c  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x18337c)
    #6 0x7f7338667a3b  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x184a3b)
    #7 0x7f733865d180  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x17a180)
    #8 0x7f733865dfca  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x17afca)
    #9 0x7f733867077e  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x18d77e)
    #10 0x7f733865eb0f  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x17bb0f)
    #11 0x7f73386297be in freerdp_check_fds (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x1467be)
    #12 0x7f733862b98c in freerdp_check_event_handles (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x14898c)
    #13 0x559173a7ae2e  (/opt/freerdp-nightly/bin/xfreerdp+0x4ee2e)
    #14 0x7f7337c59d41  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116d41)
    #15 0x7f73373427fb in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x77fb)
    #16 0x7f7337877b5e in clone (/lib/x86_64-linux-gnu/libc.so.6+0x114b5e)

0x60b0000107b0 is located 32 bytes inside of 104-byte region [0x60b000010790,0x60b0000107f8)
allocated by thread T1 here:
    #0 0x7f733a2d1b50 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb50)
    #1 0x7f7337c7f94c in _aligned_offset_malloc (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x13c94c)
    #2 0x559173a69715  (/opt/freerdp-nightly/bin/xfreerdp+0x3d715)
    #3 0x7f733859f9b7  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0xbc9b7)
    #4 0x7f733866637c  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x18337c)
    #5 0x7f7338667a3b  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x184a3b)
    #6 0x7f733865d180  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x17a180)
    #7 0x7f733865dfca  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x17afca)
    #8 0x7f733867077e  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x18d77e)
    #9 0x7f733865eb0f  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x17bb0f)
    #10 0x7f73386297be in freerdp_check_fds (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x1467be)
    #11 0x7f733862b98c in freerdp_check_event_handles (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x14898c)
    #12 0x559173a7ae2e  (/opt/freerdp-nightly/bin/xfreerdp+0x4ee2e)
    #13 0x7f7337c59d41  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116d41)
    #14 0x7f73373427fb in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x77fb)

Thread T1 created by T0 here:
    #0 0x7f733a22ad2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f7337c599b4  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x1169b4)
    #2 0x7f7337c5a1bf in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x1171bf)
    #3 0x559173a74eff  (/opt/freerdp-nightly/bin/xfreerdp+0x48eff)
    #4 0x559173a3b1ca  (/opt/freerdp-nightly/bin/xfreerdp+0xf1ca)
    #5 0x7f73377841c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)

SUMMARY: AddressSanitizer: bad-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8) in __interceptor_free
==3916==ABORTING
```
In contrast, this did work:
```
/opt/freerdp-nightly/bin$ xfreerdp /v:remote.hostname.com /u:userid /multimon
[13:02:41:258] [3896:3897] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
Password: 
[13:02:46:382] [3896:3897] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[13:02:46:382] [3896:3897] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[13:02:47:449] [3896:3897] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[13:03:02:342] [3896:3897] [INFO][com.freerdp.client.x11] - Closed from X11

```

freerdp version (e.g. xfreerdp --version) or package version or git commit
`This is FreeRDP version 2.0.0-dev (git n/a)`

freerdp configuration (e.g. xfreerdp --buildconfig)
```
This is FreeRDP version 2.0.0-dev (git n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RELWITHDEBINFO
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp2-GgAvPi/freerdp2-2.0.0~git201710051313=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -msse2
Compiler:            GNU, 6.3.0
Target architecture: x64

```

operating System, architecture, distribution
Ubuntu 17.10 64-bit

I posted this after seeing an answer to another similar issue, in which the response requested additional errors to be reported.

**Comment by akallabeth** [comment]
Closing as fixed, reopen if still an issue.
