### ISSUE TITLE
freerdp-2.0.0-rc2: segfault in RleDecompress16to16 / WriteFgBgImage16to16

### ISSUE THREAD

**Issue by ungifted** [FreeRDP/FreeRDP#4601]
I'm on Gentoo and with freerdp-2.0.0rc2 I have segfault, at least with w2008/w2008r2.
freerdp-2.0.0-rc1 work fine.

$ xfreerdp -version
This is FreeRDP version 2.0.0-dev3 (8cba20199)

(gdb) run /size:1820x1000 /kbd:0x00000409 /u:domain\\login /bpp:16 +compression -multitouch -wallpaper +themes +async-update +clipboard /v:w2008r2

```
Thread 10 "xfreerdp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe9326700 (LWP 13237)]
0x00007ffff693f8b6 in WriteFgBgImage16to16 (cBits=3, fgPel=63422, bitmask=82 'R', rowDelta=384, pbDest=0x7fffe4057000 "")
    at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/codec/include/bitmap.c:115
115								DESTWRITEPIXEL(pbDest, xorPixel ^ fgPel);
(gdb) bt full
#0  0x00007ffff693f8b6 in WriteFgBgImage16to16 (cBits=3, fgPel=63422, bitmask=82 'R', rowDelta=384, pbDest=0x7fffe4057000 "")
    at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/codec/include/bitmap.c:115
        xorPixel = 2113
        xorPixel = <optimized out>
#1  RleDecompress16to16 (width=384, height=0, rowDelta=384, 
    pbDestBuffer=0x7fffe40413d0 "\230e\230e\230e\230e\230e\230e\230e\230e\230e\230e\230e\230e\230eeWeWeWeWeWeWeWeWeWeWeWeWeWeWeWeWeWeWeWeWeWeWeW\377\377\377\377\377\377", cbSrcBuffer=<optimized out>, 
    pbSrcBuffer=0x55555581f5c1 "\360<\t\204\231֙֙֙\326U\002P@@@\003\236") at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/codec/include/bitmap.c:539
        fInsertFgPel = 0
        pixelB = <optimized out>
        runLength = 63422
        advance = <optimized out>
        pbSrc = 0x55555581f5c1 "\360<\t\204\231֙֙֙\326U\002P@@@\003\236"
        pbDest = 0x7fffe4056ff6 "\377\377\276", <incomplete sequence \367>
        temp = <optimized out>
        fgPel = 63422
        fFirstLine = <optimized out>
        pbEnd = 0x55555581e161 "1|1|1|1|\360s\360s\320k\320kNcU\235U\235U\235V\235"
        bitmask = 82 'R'
        pixelA = <optimized out>
        code = <optimized out>
        pbSrc = <optimized out>
        pbEnd = <optimized out>
        pbDest = <optimized out>
        temp = <optimized out>
        fgPel = <optimized out>
        fInsertFgPel = <optimized out>
        fFirstLine = <optimized out>
        bitmask = <optimized out>
        pixelA = <optimized out>
        pixelB = <optimized out>
        runLength = <optimized out>
        code = <optimized out>
        advance = <optimized out>
#2  interleaved_decompress (interleaved=0x7fffec071630, 
    pSrcData=pSrcData@entry=0x55555581dfa2 "\236\367y\366\363\344,\323(\312\307ɉʮ\333\357\273\303(\313zU\255\060\214\212R\303\020\307\071\333ޞ\367\276\367\276\367\276\367\025\005\376\016\230\337\377\276\367u\255u\255\236\367}\367\370\335O\203\333\356}\367\236\367y\316\bBa", SrcSize=SrcSize@entry=447, nSrcWidth=nSrcWidth@entry=192, nSrcHeight=nSrcHeight@entry=13, bpp=bpp@entry=16, 
    pDstData=0x7fffe40187d0 "\370\374\370\377", DstFormat=537135240, nDstStep=0, nXDst=0, nYDst=0, nDstWidth=192, nDstHeight=13, palette=0x7fffec044598)
    at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/codec/interleaved.c:331
        scanline = 384
        SrcFormat = 268502373
        BufferSize = 4992
        __FUNCTION__ = "interleaved_decompress"
#3  0x00007ffff68b6dba in gdi_Bitmap_Decompress (context=0x5555557f8b00, bitmap=0x7fffe400a670, 
    pSrcData=0x55555581dfa2 "\236\367y\366\363\344,\323(\312\307ɉʮ\333\357\273\303(\313zU\255\060\214\212R\303\020\307\071\333ޞ\367\276\367\276\367\276\367\025\005\376\016\230\337\377\276\367u\255u\255\236\367}\367\370\335O\203\333\356}\367\236\367y\316\bBa", DstWidth=192, DstHeight=13, bpp=16, length=447, compressed=1, codecId=0) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/gdi/graphics.c:156
        SrcSize = 447
        SrcFormat = <optimized out>
        gdi = 0x7fffec044550
#4  0x00007ffff68bf9c6 in gdi_bitmap_update (context=0x5555557f8b00, bitmapUpdate=0x7fffec0a08a0) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/gdi/gdi.c:495
        bitmap = 0x7fffec0a0bd8
        bmp = 0x7fffe400a670
---Type <return> to continue, or q <return> to quit---
        index = 11
#5  0x00007ffff691c538 in update_message_process_update_class (type=6, msg=0x7fffe9325e80, proxy=<optimized out>) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/core/message.c:1762
        status = 0
        status = <optimized out>
        imeId = <optimized out>
        imeState = <optimized out>
        imeConvMode = <optimized out>
#6  update_message_process_class (msgType=6, msgClass=1, msg=0x7fffe9325e80, proxy=<optimized out>) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/core/message.c:2585
        status = 0
        status = <optimized out>
#7  update_message_queue_process_message (update=update@entry=0x555555810ec0, message=message@entry=0x7fffe9325e80) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/core/message.c:2633
        status = <optimized out>
        msgClass = 1
        msgType = 6
#8  0x00007ffff691c8c3 in update_message_proxy_thread (arg=0x555555810ec0) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/core/message.c:2872
        status = 0
        update = 0x555555810ec0
        message = {id = 65542, context = 0x5555557f8b00, wParam = 0x7fffec0a08a0, lParam = 0x0, time = 93824995102864, Free = 0x0}
        __FUNCTION__ = "update_message_proxy_thread"
#9  0x00007ffff609ee01 in thread_launcher (arg=0x7fffec092440) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/winpr/libwinpr/thread/thread.c:319
        rc = 0x0
        thread = 0x7fffec092440
        fkt = 0x7ffff691c870 <update_message_proxy_thread>
        __FUNCTION__ = "thread_launcher"
#10 0x00007ffff562992a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#11 0x00007ffff5d7261f in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb) info threads
  Id   Target Id         Frame 
  1    Thread 0x7ffff7fb7d80 (LWP 13225) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
  2    Thread 0x7ffff3cfd700 (LWP 13229) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
  3    Thread 0x7ffff2bfe700 (LWP 13230) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
  4    Thread 0x7ffff23fd700 (LWP 13231) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
  5    Thread 0x7ffff1bfc700 (LWP 13232) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
  6    Thread 0x7ffff13fb700 (LWP 13233) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
  7    Thread 0x7fffeab29700 (LWP 13234) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
  8    Thread 0x7fffea328700 (LWP 13235) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
  9    Thread 0x7fffe9b27700 (LWP 13236) "xfreerdp" 0x00007ffff5d66c55 in poll () from /lib64/libc.so.6
* 10   Thread 0x7fffe9326700 (LWP 13237) "xfreerdp" 0x00007ffff693f8b6 in WriteFgBgImage16to16 (cBits=3, fgPel=63422, bitmask=82 'R', rowDelta=384, pbDest=0x7fffe4057000 "")
    at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/codec/include/bitmap.c:115
(gdb) q

```

```
Thread 10 "xfreerdp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe9326700 (LWP 13127)]
0x00007ffff693f2fd in RleDecompress16to16 (width=248, height=0, rowDelta=248, pbDestBuffer=0x7fffe40413d0 "", cbSrcBuffer=<optimized out>, pbSrcBuffer=<optimized out>)
    at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/codec/include/bitmap.c:465
465						UNROLL(
(gdb) bt full
#0  0x00007ffff693f2fd in RleDecompress16to16 (width=248, height=0, rowDelta=248, pbDestBuffer=0x7fffe40413d0 "", cbSrcBuffer=<optimized out>, pbSrcBuffer=<optimized out>)
    at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/codec/include/bitmap.c:465
        fInsertFgPel = 0
        pixelB = 65284
        runLength = <optimized out>
        advance = <optimized out>
        pbSrc = <optimized out>
        pbDest = <optimized out>
        temp = <optimized out>
        fgPel = 16936
        fFirstLine = 0
        pbEnd = 0x55555581dcee "Mk\377\377\377\377(B\006\217Mk\377\377\377\377\030\306(B\377\377\377\377\377\377\030\306(BQ\214Mk\377\377\377\377(B\a\225\064\245(B\377\377\377\377(B4\245\030\306(B\377\377\377\377\064\245\004!\377\377\377\377\030\306\064\245Q\214Mk\377\377\377\377\004!\n\205Mk4\245\377\377\377\377Mk\006\217\377\377\377\377Q\214"
        bitmask = <optimized out>
        pixelA = 752
        code = <optimized out>
        pbSrc = <optimized out>
        pbEnd = <optimized out>
        pbDest = <optimized out>
        temp = <optimized out>
        fgPel = <optimized out>
        fInsertFgPel = <optimized out>
        fFirstLine = <optimized out>
        bitmask = <optimized out>
        pixelA = <optimized out>
        pixelB = <optimized out>
        runLength = <optimized out>
        code = <optimized out>
        advance = <optimized out>
#1  interleaved_decompress (interleaved=0x7fffec071630, pSrcData=pSrcData@entry=0x55555581dbbf "\214\a\200\022(B", SrcSize=SrcSize@entry=303, nSrcWidth=nSrcWidth@entry=124, nSrcHeight=nSrcHeight@entry=13, 
    bpp=bpp@entry=16, 
    pDstData=0x7fffe4035650 "\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377\310\320\320\377"..., 
    DstFormat=537135240, nDstStep=0, nXDst=0, nYDst=0, nDstWidth=124, nDstHeight=13, palette=0x7fffec044598) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/codec/interleaved.c:331
        scanline = 248
        SrcFormat = 268502373
        BufferSize = 3224
        __FUNCTION__ = "interleaved_decompress"
#2  0x00007ffff68b6dba in gdi_Bitmap_Decompress (context=0x5555557f8b00, bitmap=0x7fffe400ba10, pSrcData=0x55555581dbbf "\214\a\200\022(B", DstWidth=124, DstHeight=13, bpp=16, length=303, compressed=1, 
    codecId=0) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/gdi/graphics.c:156
        SrcSize = 303
        SrcFormat = <optimized out>
        gdi = 0x7fffec044550
#3  0x00007ffff68bf9c6 in gdi_bitmap_update (context=0x5555557f8b00, bitmapUpdate=0x7fffec099320) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/gdi/gdi.c:495
        bitmap = 0x7fffec09ca40
        bmp = 0x7fffe400ba10
        index = 6
#4  0x00007ffff691c538 in update_message_process_update_class (type=6, msg=0x7fffe9325e80, proxy=<optimized out>) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/core/message.c:1762
        status = 0
---Type <return> to continue, or q <return> to quit---
        status = <optimized out>
        imeId = <optimized out>
        imeState = <optimized out>
        imeConvMode = <optimized out>
#5  update_message_process_class (msgType=6, msgClass=1, msg=0x7fffe9325e80, proxy=<optimized out>) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/core/message.c:2585
        status = 0
        status = <optimized out>
#6  update_message_queue_process_message (update=update@entry=0x555555810ec0, message=message@entry=0x7fffe9325e80) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/core/message.c:2633
        status = <optimized out>
        msgClass = 1
        msgType = 6
#7  0x00007ffff691c8c3 in update_message_proxy_thread (arg=0x555555810ec0) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/libfreerdp/core/message.c:2872
        status = 0
        update = 0x555555810ec0
        message = {id = 65542, context = 0x5555557f8b00, wParam = 0x7fffec099320, lParam = 0x0, time = 93824995102864, Free = 0x0}
        __FUNCTION__ = "update_message_proxy_thread"
#8  0x00007ffff609ee01 in thread_launcher (arg=0x7fffec092350) at /usr/src/debug/net-misc/freerdp-9999/freerdp-9999/winpr/libwinpr/thread/thread.c:319
        rc = 0x0
        thread = 0x7fffec092350
        fkt = 0x7ffff691c870 <update_message_proxy_thread>
        __FUNCTION__ = "thread_launcher"
#9  0x00007ffff562992a in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#10 0x00007ffff5d7261f in clone () from /lib64/libc.so.6
No symbol table info available.
(gdb) q
```

**Comment by akallabeth** [comment]
Async update is broken, I'm on mobile, so please look for the issue and pull yourself.
