### ISSUE TITLE
==21034==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f83769b85c0 at pc 0x7f837578239f bp 0x7f8367b579d0 sp 0x7f8367b579c0

### ISSUE THREAD

**Issue by Anagneia** [FreeRDP/FreeRDP#4628]
Here's the whole command line output:
```
[08:25:52:298] [21034:21035] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[08:25:52:298] [21034:21035] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[08:25:52:298] [21034:21035] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
=================================================================
==21034==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f83769b85c0 at pc 0x7f837578239f bp 0x7f8367b579d0 sp 0x7f8367b579c0
READ of size 8 at 0x7f83769b85c0 thread T3
[08:25:53:008] [21034:21036] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [gvfs] (static)
    #0 0x7f837578239e in CommandLineFindNextArgumentA (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0xb639e)
    #1 0x7f8376715f07  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x147f07)
    #2 0x7f83766bf728  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0xf1728)
    #3 0x7f83766c17ed  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0xf37ed)
    #4 0x7f83757e2b81  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116b81)
    #5 0x7f8374ed07fb in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x77fb)
    #6 0x7f8375400b5e in clone (/lib/x86_64-linux-gnu/libc.so.6+0x114b5e)
0x7f83769b85c0 is located 0 bytes to the right of global variable 'rdpsnd_fake_args' defined in '/build/freerdp-nightly-2.0.0+0~20180504014825.520~1.gbp1a27f2/channels/rdpsnd/client/fake/rdpsnd_fake.c:89:32' (0x7f83769b8580) of size 64
SUMMARY: AddressSanitizer: global-buffer-overflow (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0xb639e) in CommandLineFindNextArgumentA
Shadow bytes around the buggy address:
  0x0ff0eed2f060: f9 f9 f9 f9 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff0eed2f070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff0eed2f080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff0eed2f090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff0eed2f0a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ff0eed2f0b0: 00 00 00 00 00 00 00 00[f9]f9 f9 f9 00 00 00 00
  0x0ff0eed2f0c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff0eed2f0d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff0eed2f0e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff0eed2f0f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ff0eed2f100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
Thread T3 created by T1 here:
    #0 0x7f8377d7dd2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f83757e27f4  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x1167f4)
    #2 0x7f83757e2fff in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116fff)
    #3 0x7f83766c0cd9  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0xf2cd9)
    #4 0x7f83761b6ce7  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x150ce7)
    #5 0x7f83761cd947  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x167947)
    #6 0x7f83761e347f  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x17d47f)
    #7 0x7f83761cd380  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x167380)
    #8 0x7f83761b0c03 in freerdp_connect (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x14ac03)
    #9 0x55adbe072a06  (/opt/freerdp-nightly/bin/xfreerdp+0x4fa06)
    #10 0x7f83757e2b81  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116b81)
    #11 0x7f8374ed07fb in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x77fb)
Thread T1 created by T0 here:
    #0 0x7f8377d7dd2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f83757e27f4  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x1167f4)
    #2 0x7f83757e2fff in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116fff)
    #3 0x55adbe06d00f  (/opt/freerdp-nightly/bin/xfreerdp+0x4a00f)
    #4 0x55adbe03274a  (/opt/freerdp-nightly/bin/xfreerdp+0xf74a)
    #5 0x7f837530d1c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)
ASAN:DEADLYSIGNAL
==21034==AddressSanitizer: while reporting a bug found another one. Ignoring.
==21034==ABORTING
```
My environment:
Ubuntu 17.10
I'm using xfreerdp, the nightly builds
```
xfreerdp --version
This is FreeRDP version 2.0.0-dev
```
```
xfreerdp --buildconfig
This is FreeRDP version 2.0.0-dev (git n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RELWITHDEBINFO
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp2-jqujoY/freerdp2-2.0.0~git20170725.1.1648deb+dfsg1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -msse2
Compiler:            GNU, 7.2.0
Target architecture: x64
```
I'm trying to connect to a Windows RDS machine hosted by IT, I think it's a Windows 10 Server

**Comment by akallabeth** [comment]
Ok, you're sure the stack and output match? Nightly is installed under /opt.
Additionally the command line you use (and contents of rdp file if used) would be required to analyze

**Comment by raptorswing** [comment]
I am not OP, but I am seeing the same (or an extremely similar) issue with latest nightly 2.0.0-dev3 (1a27f28ba) on Ubuntu 16.04.

```
[12:18:54:262] [7593:7594] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[12:18:54:262] [7593:7594] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[12:18:54:262] [7593:7594] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[12:18:54:342] [7593:7594] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[12:18:54:342] [7593:7594] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[12:18:54:365] [7593:7594] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[12:18:54:391] [7593:7599] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service smartcard (static)
[12:18:54:391] [7593:7599] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer (static)
=================================================================
==7593==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7f4758925f60 at pc 0x7f4757784f7f bp 0x7f4742d88a20 sp 0x7f4742d88a10
READ of size 8 at 0x7f4758925f60 thread T7
    #0 0x7f4757784f7e in CommandLineFindNextArgumentA (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0xb1f7e)
    #1 0x7f4758695aef  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x147aef)
    #2 0x7f47586525d2  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x1045d2)
    #3 0x7f475865469b  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x10669b)
    #4 0x7f47577da471  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107471)
    #5 0x7f47570f36b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #6 0x7f475741041c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)

0x7f4758925f60 is located 0 bytes to the right of global variable 'rdpsnd_fake_args' defined in '/build/freerdp-nightly-2.0.0+0~20180504014825.520~1.gbp1a27f2/channels/rdpsnd/client/fake/rdpsnd_fake.c:89:32' (0x7f4758925f20) of size 64
SUMMARY: AddressSanitizer: global-buffer-overflow ??:0 CommandLineFindNextArgumentA
Shadow bytes around the buggy address:
  0x0fe96b11cb90: 00 00 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9
  0x0fe96b11cba0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe96b11cbb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe96b11cbc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe96b11cbd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0fe96b11cbe0: 00 00 00 00 00 00 00 00 00 00 00 00[f9]f9 f9 f9
  0x0fe96b11cbf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe96b11cc00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe96b11cc10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe96b11cc20: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0fe96b11cc30: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
Thread T7 created by T1 here:
    #0 0x7f4759ce8253 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36253)
    #1 0x7f47577da104  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107104)
    #2 0x7f47577da917 in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107917)
    #3 0x7f4758653ad9  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x105ad9)
    #4 0x7f475814ed9b  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x147d9b)
    #5 0x7f4758149d60 in freerdp_connect (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x142d60)
    #6 0x442f06  (/opt/freerdp-nightly/bin/xfreerdp+0x442f06)
    #7 0x7f47577da471  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107471)
    #8 0x7f47570f36b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Thread T1 created by T0 here:
    #0 0x7f4759ce8253 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36253)
    #1 0x7f47577da104  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107104)
    #2 0x7f47577da917 in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107917)
    #3 0x43dd8f  (/opt/freerdp-nightly/bin/xfreerdp+0x43dd8f)
    #4 0x4079b0  (/opt/freerdp-nightly/bin/xfreerdp+0x4079b0)
    #5 0x7f475732982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

==7593==ABORTING
```

Here is my .rdp file:
```
screen mode id:i:2
use multimon:i:0
desktopwidth:i:800
desktopheight:i:600
session bpp:i:32
winposstr:s:0,3,0,0,800,600
compression:i:1
keyboardhook:i:2
audiocapturemode:i:0
videoplaybackmode:i:1
connection type:i:7
networkautodetect:i:1
bandwidthautodetect:i:1
displayconnectionbar:i:1
enableworkspacereconnect:i:0
disable wallpaper:i:0
allow font smoothing:i:0
allow desktop composition:i:0
disable full window drag:i:1
disable menu anims:i:1
disable themes:i:0
disable cursor setting:i:0
bitmapcachepersistenable:i:1
full address:s:devwindows
audiomode:i:0
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
redirectclipboard:i:1
redirectposdevices:i:0
autoreconnection enabled:i:1
authentication level:i:2
prompt for credentials:i:0
negotiate security layer:i:1
remoteapplicationmode:i:0
alternate shell:s:
shell working directory:s:
gatewayhostname:s:
gatewayusagemethod:i:4
gatewaycredentialssource:i:4
gatewayprofileusagemethod:i:0
promptcredentialonce:i:0
gatewaybrokeringtype:i:0
use redirection server name:i:0
rdgiskdcproxy:i:0
kdcproxyname:s:
enablecredsspsupport:i:0
use multimon:i:1
```

My command-line:
```
/opt/freerdp-nightly/bin/xfreerdp windows.rdp
```

**Comment by Anagneia** [comment]
@akallabeth : I use Gnome Terminal 3.24.2
My rdp file looks like this (replaced confidential information by x):
```
redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:0
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:0
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:0
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:0
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:XXX.XXX.XXXXXX
workspace id:s:xxx.xxx.xxx
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.default_collecti
use multimon:i:0
desktopheight:i:1050
desktopwidth:i:1920
domain:s:xxx
username:s:xxxxxxx
```
Btw. I've updated today to the latest nightly build and it doesn't fix my issue.

**Comment by akallabeth** [comment]
@Anagneia sorry, you need to wait till the referenced pull has been merged or build from source to test this.

**Comment by Anagneia** [comment]
Ok, I've seen the label "fix-wainting-test" above and thought so. Just wanted to mention that I tried the update anyway.

**Comment by Anagneia** [comment]
Hi, updated this morning and it's working flawlessly again. Thanks for the fix!
