### ISSUE TITLE
Microphone redirection is not working on Mac with latest master(FreeRDP version 2.0.0-dev3 (1c75854a3))

### ISSUE THREAD

**Issue by thecrazyonestherebels** [FreeRDP/FreeRDP#4779]
Hi all,
I am using latest freerdp(as of now, 1c75854a3aca1b0069694d09a6eb709ed1d8cf63) from master to connect to remote windows machine from my Mac(with macOS 10.13.5, High Sierra). Basically I wanted to make Skype calls from that remote machine, but microphone redirection is not working at all, I could hear the audio from the other end though.

**Compiling from sources, and generating Mac native app(MacFreeRDP)**
i)cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" -DWITH_FFMPEG=ON . && make
ii)MacFreeRDP.app got generated under FreeRDP/client/Mac/cli/

Build log info is attached. Build_Log.txt

**To Reproduce
Steps to reproduce the behavior:**
1)Open the terminal window, change the directory to FreeRDP/client/Mac/cli/MacFreeRDP.app/Contents/MacOS
2) Run the command ../MacFreeRDP /u:username /p:paswd$ /microphone /sound /g:gateway /v:IP_Address /log-filters:com.freerdp.channels.audin.client:trace
3)Open Skype app on Remote machine and make a call.
4)Once you started speaking after the other person picked up the call, there is an error message coming on the skype window saying that Your mic isn't working. Try a different one.
Please find the attached screenshot.

And also I have the same issue with Skype for Business app as well. Event though I have correct audio settings. Please find the attached screenshot.

Expected behavior
Microphone should be working as the device is connected to the remote machine correctly.

Attached Skypecall debug info as well. 
[Build_Log.txt](https://github.com/FreeRDP/FreeRDP/files/2249845/Build_Log.txt)
[Skypecall_debug.txt](https://github.com/FreeRDP/FreeRDP/files/2249846/Skypecall_debug.txt)
<img width="1021" alt="skype" src="https://user-images.githubusercontent.com/41958166/43528170-f509dd2e-95c5-11e8-96d7-7b1adc0d4e5d.png">
<img width="714" alt="skypeforbusiness" src="https://user-images.githubusercontent.com/41958166/43528171-f536e292-95c5-11e8-8467-b3e3cefa6f76.png">

My desktop environment:
mac OS(10.13.5, High Sierra)

**Comment by akallabeth** [comment]
Ok, this is because of a buggy `ADPCM` implementation. Try enabling the FFMPEG backend, then it will work. (`WITH_DSP_FFMPEG=ON`)

**Comment by thecrazyonestherebels** [comment]
@akallabeth 
thanks for your inputs, its working fine. However I have seen few issues when I was having voice call using Skype for business.
1) Some times I see a warning "Your device is causing poor audio quality" during the call, please find the attached SS. And in few cases, Microphone stopped working, though I didn't see any errors in the logs.  
2) As the call duration progresses, I could see that the lag(i.e time to reach to other end) is getting increased. 
<img width="922" alt="screen shot 2018-08-02 at 4 56 05 pm" src="https://user-images.githubusercontent.com/41958166/43605510-2e086078-96b6-11e8-975d-bea8e5dd8e0c.png">

**Comment by akallabeth** [comment]
@thecrazyonestherebels thx for the input, the logs from freerdp (/log-level:trace) would help a bit more ;)

**Comment by thecrazyonestherebels** [comment]
@akallabeth,
I tried to reproduce the above issue#1, with 5-6 calls, but couldnt make it. Will share the log If I faced it again.
Regarding lag, I had call with Skype for business for approximately 1hour 20minutes, which has around 110MB of log data, which I couldn't upload here, but here is the dropbox link to download. https://www.dropbox.com/s/jnnhun31zpwhpey/SkypeForBusiness_Call_Log_1hour_18minutes.txt?dl=0

And also, just  checking with you that is there any plans to improve ADPCM implementation for Mac.

**Comment by akallabeth** [comment]
@thecrazyonestherebels Thx for the log, as for the codec, just use ffmpeg if available for the time being. Should prefer AAC anyway (better quality/less bandwidth)

**Comment by schadsey** [comment]
I noticed today that microphone redirection was not working with a recent daily build I was using on Xubuntu 17.10 x86_64, connecting to Windows 10 Enterprise.
Working version: 
* `freerdp-nightly_2.0.0+0~20180405014917.508~1.gbp559732_amd64.deb`
* `This is FreeRDP version 2.0.0-dev2 (55973288f)`

Failing version:
* `freerdp-nightly_2.0.0+0~20180731014836.540~1.gbp88474a_amd64.deb`
* `This is FreeRDP version 2.0.0-dev3 (88474af92)`

The compile flags are different; I've attached the /buildconfig outputs.  

[xfreerdp-buildconfig-88474af92.txt](https://github.com/FreeRDP/FreeRDP/files/2258151/xfreerdp-buildconfig-88474af92.txt)
[xfreerdp-buildconfig-55973288f.txt](https://github.com/FreeRDP/FreeRDP/files/2258152/xfreerdp-buildconfig-55973288f.txt)

**Comment by akallabeth** [comment]
@schadsey I've updated the nightly builds in #4783

**Comment by gerdneuman** [comment]
I still see this:
```console
/opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 2.0.0-dev4 (92c2d83a4)
```

which fails with the following when I start to use the microphone on Windows (before starting Skype and Mic testing, I used freerdp for 1h without problems):
```console
$ /opt/freerdp-nightly/bin/xfreerdp /u:xxx /p:xxx  /v:xxx  /sound:sys:alsa /microphone:sys:alsa /f +toggle-fullscreen +clipboard /monitors:1 /multimon
[11:38:39:006] [5919:5920] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[11:38:39:006] [5919:5920] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[11:38:39:007] [5919:5920] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[11:38:39:007] [5919:5920] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[11:38:39:513] [5919:5920] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[11:38:39:513] [5919:5920] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[11:38:39:566] [5919:5920] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[11:38:39:625] [5919:5920] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel audin
[11:38:39:625] [5919:5926] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded alsa backend for rdpsnd
[11:38:39:625] [5919:5920] [INFO][com.freerdp.channels.audin.client] - Loaded alsa backend for audin
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7963:(snd_pcm_recover) underrun occurred
=================================================================
==5919==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7fbb52b77354 at pc 0x7fbb52a79e8a bp 0x7fbb2de019d0 sp 0x7fbb2de019c0
READ of size 4 at 0x7fbb52b77354 thread T18
    #0 0x7fbb52a79e89  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x1cde89)
    #1 0x7fbb52a7afa0 in freerdp_dsp_encode (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x1cefa0)
    #2 0x7fbb52e704bc  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x7a4bc)
    #3 0x7fbb52f29192  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x133192)
    #4 0x7fbb5207dce1  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107ce1)
    #5 0x7fbb519966b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #6 0x7fbb51cb341c in clone (/lib/x86_64-linux-gnu/libc.so.6+0x10741c)

0x7fbb52b77354 is located 0 bytes to the right of global variable '*.LC6' defined in '/build/freerdp-nightly-2.0.0+0~20180802014836.542~1.gbp92c2d8/libfreerdp/codec/color.c' (0x7fbb52b77340) of size 20
  '*.LC6' is ascii string 'PIXEL_FORMAT_RGBA32'
0x7fbb52b77354 is located 44 bytes to the left of global variable '*.LC7' defined in '/build/freerdp-nightly-2.0.0+0~20180802014836.542~1.gbp92c2d8/libfreerdp/codec/color.c' (0x7fbb52b77380) of size 20
  '*.LC7' is ascii string 'PIXEL_FORMAT_RGBX32'
SUMMARY: AddressSanitizer: global-buffer-overflow ??:0 ??
Shadow bytes around the buggy address:
  0x0ff7ea566e10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 02 f9
  0x0ff7ea566e20: f9 f9 f9 f9 00 00 00 00 f9 f9 f9 f9 00 00 00 00
  0x0ff7ea566e30: 00 00 00 00 00 00 00 00 00 00 04 f9 f9 f9 f9 f9
  0x0ff7ea566e40: 00 00 04 f9 f9 f9 f9 f9 00 00 04 f9 f9 f9 f9 f9
  0x0ff7ea566e50: 00 00 04 f9 f9 f9 f9 f9 00 00 04 f9 f9 f9 f9 f9
=>0x0ff7ea566e60: 00 00 04 f9 f9 f9 f9 f9 00 00[04]f9 f9 f9 f9 f9
  0x0ff7ea566e70: 00 00 04 f9 f9 f9 f9 f9 00 00 03 f9 f9 f9 f9 f9
  0x0ff7ea566e80: 00 00 03 f9 f9 f9 f9 f9 00 00 03 f9 f9 f9 f9 f9
  0x0ff7ea566e90: 00 00 03 f9 f9 f9 f9 f9 00 00 04 f9 f9 f9 f9 f9
  0x0ff7ea566ea0: 00 00 03 f9 f9 f9 f9 f9 00 00 04 f9 f9 f9 f9 f9
  0x0ff7ea566eb0: 00 00 03 f9 f9 f9 f9 f9 00 00 02 f9 f9 f9 f9 f9
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
Thread T18 created by T9 here:
    #0 0x7fbb54594253 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36253)
    #1 0x7fbb5207d974  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107974)
    #2 0x7fbb5207e187 in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x108187)
    #3 0x7fbb52f29cc5  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x133cc5)
    #4 0x7fbb52e6f096  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x79096)
    #5 0x7fbb52e71cd0  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x7bcd0)
    #6 0x7fbb52f106d4  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x11a6d4)
    #7 0x7fbb5207dce1  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107ce1)
    #8 0x7fbb519966b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Thread T9 created by T1 here:
    #0 0x7fbb54594253 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36253)
    #1 0x7fbb5207d974  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107974)
    #2 0x7fbb5207e187 in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x108187)
    #3 0x7fbb52f14453  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0x11e453)
    #4 0x7fbb529f6d8b  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x14ad8b)
    #5 0x7fbb529f1a2a in freerdp_connect (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x145a2a)
    #6 0x442d74  (/opt/freerdp-nightly/bin/xfreerdp+0x442d74)
    #7 0x7fbb5207dce1  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107ce1)
    #8 0x7fbb519966b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)

Thread T1 created by T0 here:
    #0 0x7fbb54594253 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x36253)
    #1 0x7fbb5207d974  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x107974)
    #2 0x7fbb5207e187 in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x108187)
    #3 0x43dacf  (/opt/freerdp-nightly/bin/xfreerdp+0x43dacf)
    #4 0x4079b0  (/opt/freerdp-nightly/bin/xfreerdp+0x4079b0)
    #5 0x7fbb51bcc82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

==5919==ABORTING
```
