### ISSUE TITLE
ASAN:DEADLYSIGNAL when watching youtube video with gfx-h264

### ISSUE THREAD

**Issue by grufo** [FreeRDP/FreeRDP#5107]
When we start a freerdp session to a windows 10 computer with the following command line:

`/opt/freerdp-nightly/bin/xfreerdp /sec:rdp /cert-ignore /disp /gfx-h264 +gfx-thin-client /sound /kbd:0x00000407 /bpp:24 /network:auto /auto-reconnect /usb:auto /usb:rules:allow /d:pirlo /u: +fonts /nsc /rfx /f /monitors:0,1 /multimon:force +auto-reconnect +compression -floatbar /microphone /video /v:ts01
`
We start the firefox browser and youtube.com - try to watch any video, after some seconds freerdp crashes with the following error-message:

```
ASAN:DEADLYSIGNAL
=================================================================
==24851==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7f06d3af66e0 sp 0x7f06d3af6698 T20)
==24851==Hint: pc points to the zero page.
==24851==The signal is caused by a READ memory access.
==24851==Hint: address points to the zero page.

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
Thread T20 created by T1 here:
    #0 0x7f071e074d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f071ba777f4  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x1167f4)
    #2 0x7f071ba77fff in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116fff)
    #3 0x7f071c997dd6  (/opt/freerdp-nightly/bin/../lib/libfreerdp-client2.so.2+0xdddd6)
    #4 0x7f071c4a43f7  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x1613f7)
    #5 0x7f071c49e5e0 in freerdp_connect (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0x15b5e0)
    #6 0x55ce7d32c00b  (/opt/freerdp-nightly/bin/xfreerdp+0x5700b)
    #7 0x7f071ba77cb9  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116cb9)
    #8 0x7f071b1546da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)

Thread T1 created by T0 here:
    #0 0x7f071e074d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f071ba777f4  (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x1167f4)
    #2 0x7f071ba77fff in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr2.so.2+0x116fff)
    #3 0x55ce7d3264bf  (/opt/freerdp-nightly/bin/xfreerdp+0x514bf)
    #4 0x55ce7d2e57ca  (/opt/freerdp-nightly/bin/xfreerdp+0x107ca)
    #5 0x7f071b591b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)

```

freerdp version: This is FreeRDP version 2.0.0-dev5 (46ffa611c)
(freerdp-nightly_2.0.0+0~20181205024844.602~1.gbp46ffa6_amd64.deb)

freerdp-buildconfig:

```
This is FreeRDP version 2.0.0-dev5 (46ffa611c)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp-nightly-2.0.0+0~20181205024844.602~1.gbp46ffa6=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 7.3.0
Target architecture: x64


```

os: kubuntu/ubuntu 18.04 with alle the latest updates

when we start with this command (**without /gfx-h264 +gfx-thin-client**) :
`/opt/freerdp-nightly/bin/xfreerdp /sec:rdp /cert-ignore /disp /sound /kbd:0x00000407 /bpp:24 /network:auto /auto-reconnect /usb:auto /usb:rules:allow /d:pirlo /u: +fonts /nsc /rfx /f /monitors:0,1 /multimon:force +auto-reconnect +compression -floatbar /microphone /video /v:ts01`

everything works without crash!

**Comment by akallabeth** [comment]
Most likely already fixed with #5099: Missing thread sync with GFX routines

**Comment by grufo** [comment]
How can I test that fix - it's not included in the daily snapshot - is it?

**Comment by grufo** [comment]
Did a checkout and compile - works for me!
When will it be included in the nigthly build?
Thank you for fixing :-)

**Comment by akallabeth** [comment]
@grufo Good to know. As to when it will be included, that is up to the other members of the project, we try not to merge our own pull requests ;)

**Comment by akallabeth** [comment]
@grufo Ok, you're lucky and it was resolved today :)
