### ISSUE TITLE
Memory leak on every screen redraw

### ISSUE THREAD

**Issue by Ghost99** [FreeRDP/FreeRDP#5545]
I faced this issue on Linux Mint 18.3, with freerdp-nightly version `2.0.0+0~20190823014831.688~1.gbp8a8655`

Steps to reproduce:
1. Connect to Windows7 or WinXP (or probably any windows machine)
2. Do something which will cause screen redraw, for example open some page in browser and scroll up and down multiple times, or just open some video on any media player (tested with Firefox and VLC)
3. Watch how xfreerdp process will consume more and more memory, up to 1GB or more. More redraws - more memory will leak.

Command I'm using to connect:
`/opt/freerdp-nightly/bin/xfreerdp -sec-nla -clipboard -wallpaper /sound:sys:pulse /size:1600x820 /u:mylogin /v:myaddress`

LeakSanitizer will not detect this memory leak for some reason, but process itself will consume memory anyway. Here is processes output, it consumed more than 1GB of RAM when I closed it:

```
$ /opt/freerdp-nightly/bin/xfreerdp -sec-nla -clipboard -wallpaper /sound:sys:pulse /size:1600x820 /u:mylogin /v:myaddress
[22:30:09:155] [23390:23391] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[22:30:09:155] [23390:23391] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[22:30:09:384] [23390:23391] [WARN][com.freerdp.crypto] - Certificate verification failure 'unable to get local issuer certificate (20)' at stack position 0
[22:30:09:384] [23390:23391] [WARN][com.freerdp.crypto] - CN = WORK_PC
[22:30:10:699] [23390:23391] [ERROR][com.winpr.timezone] - Unable to get current timezone rule
[22:30:10:849] [23390:23391] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[22:30:10:849] [23390:23391] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[22:30:10:876] [23390:23391] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[22:30:10:918] [23390:23397] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd
[22:31:12:824] [23390:23391] [INFO][com.freerdp.client.x11] - Closed from X11

=================================================================
==23390==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 19 byte(s) in 1 object(s) allocated from:
    #0 0x7f8d0d90f79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7f8d0bc7534e  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0xdf34e)
    #2 0x7f8d0bc75457  (/opt/freerdp-nightly/bin/../lib/libfreerdp2.so.2+0xdf457)
    #3 0x7f8d06dc3e88 in X509_verify_cert (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0x156e88)

SUMMARY: AddressSanitizer: 19 byte(s) leaked in 1 allocation(s).
```

**Comment by akallabeth** [comment]
Sure this is a leak and not simple caching?
Address sanitizer uses more ram than normal builds, so for how long did your session run and does memory use peak at some time later?

**Comment by Ghost99** [comment]
At some point the leak rate slows down at about 800-900MB, but in any case I rarely see the process memory consumption decreasing, it is basically only increasing. In a 10-minute session it can rise to 900 MB and does not stop growing.
Is it normal address sanitizer behavior? If so, is there a way to disable it?

**Comment by akallabeth** [comment]
Yes, that is 'normal'.

As the name suggests, nightlies are for testing purposes,
so you need to compile yourself or use distro packages if you want one without.

Am August 23, 2019 9:45:06 PM UTC schrieb Ghost99 <notifications@github.com>:
>At some point the leak rate slows down at about 800-900MB, but in any
>case I rarely see the process memory consumption decreasing, it is
>basically only increasing. In a 10-minute session it can rise to 900 MB
>and does not stop growing.
>Is it normal address sanitizer behavior? If so, is there a way to
>disable it?

**Comment by Ghost99** [comment]
Ok, thanks. Sorry for disturbing.
