### ISSUE TITLE
Fullscreen only displays on 2 of 4 screens

### ISSUE THREAD

**Issue by rsclafani** [FreeRDP/FreeRDP#5572]
**Describe the bug**
Fullscreen mode only displays on 2 of 4 monitors, while returning to windowed mode via `ctrl+alt+enter` shows correct remote desktop geometry of 4 screens. In fullscreen mode, the remote desktop knows there are 4 screens and allows the user to expand/stretch windows into the unseen space.

This started happening when I switched from 4x 1600x1200 screens to 4x 1920x1080. Both configurations were 2x2 and on the same video card. In this configuration, fullscreen is only showing on left two monitors.

**To Reproduce**
command: `/opt/freerdp-nightly/bin/xfreerdp /from-stdin /multimon /v:xxx /u:xxx /d:xxx +clipboard /cert-ignore`

**Expected behavior**
Fullscreen covers all 4 monitors

**Screenshots**
Fullscreen (note excel title bar extended into unseen space):
![fullscreen](https://user-images.githubusercontent.com/17805184/64456821-b9b84f80-d0b6-11e9-985f-d4e024ea0726.jpg)

Windowed:
![windowed](https://user-images.githubusercontent.com/17805184/64457387-16683a00-d0b8-11e9-8f62-140c4c6d0c84.jpg)

**Application details**
* Version of FreeRDP: 2.0.0-dev5 (0ca70222b)
* output of `/buildconfig`:
```
$ /opt/freerdp-nightly/bin/xfreerdp /buildconfig
This is FreeRDP version 2.0.0-dev5 (0ca70222b)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp-nightly-2.0.0+0~20190905014832.695~1.gbp0ca702=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 7.3.0
Target architecture: x64
```
* OS version connecting to: Windows 10 Enterprise
* Output of monitor-list:
```
$ xfreerdp /monitor-list
      * [0] 1920x1080	+0+0
        [1] 1920x1080	+1920+1080
        [2] 1920x1080	+1920+0
        [3] 1920x1080	+0+1080

=================================================================
==7995==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 21152 byte(s) in 1 object(s) allocated from:
    #0 0x7fddcb83fd38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x7fddc84183c0 in xcb_connect_to_fd (/usr/lib/x86_64-linux-gnu/libxcb.so.1+0xb3c0)

Indirect leak of 16384 byte(s) in 1 object(s) allocated from:
    #0 0x7fddcb83fd38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x7fddcb457205 in XOpenDisplay (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x2e205)

Indirect leak of 12768 byte(s) in 2 object(s) allocated from:
    #0 0x7fddcb83fd38 in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xded38)
    #1 0x7fddcb457673 in XOpenDisplay (/usr/lib/x86_64-linux-gnu/libX11.so.6+0x2e673)
```
I don't know if those memory leaks are related or occurred with the old monitors.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - WM: GNOME Shell 3.28.3
 - Video card: NVIDIA Corporation GK107 [NVS 510] (rev a1)
 - Video driver: tried both nvidia-driver-430 and -390

Thanks in advance!

**Comment by rsclafani** [comment]
I physically changed the plug order on my monitors (then arranged the screens to match the physical layout in the host) and that solved the problem. The new monitor list is displayed below.
```
xfreerdp /monitor-list
      * [0] 1920x1080	+0+0
        [1] 1920x1080	+0+1080
        [2] 1920x1080	+1920+0
        [3] 1920x1080	+1920+1080
```
_Note: the memory leaks are still being reported so they were not the root cause_

```
$ xrandr --listmonitors
Monitors: 4
 0: +*DP-4 1920/598x1080/336+0+0  DP-4
 1: +DP-5 1920/598x1080/336+0+1080  DP-5
 2: +DP-6 1920/598x1080/336+1920+0  DP-6
 3: +DP-7 1920/598x1080/336+1920+1080  DP-7
```

I still consider this bug open. I am not sure how FreeRDP calculates what the fullscreen geometry  should be, but there may be some unexpected assumptions about 2-dimensional arrangements.

**Comment by akallabeth** [comment]
Thank you for the update on this.
Might be some bug in assumptions like you mentioned.

The leaks are false positives (x11 related) and can be ignored.
