### ISSUE TITLE
wlfreerdp segfaults

### ISSUE THREAD

**Issue by colemickens** [FreeRDP/FreeRDP#5700]
This should include all relevant info. You can see the version of freerdp, the command line args, and the backtrace.

```
$ coredumpctl gdb
           PID: 3335 (wlfreerdp)
           UID: 1000 (cole)
           GID: 1000 (cole)
        Signal: 11 (SEGV)
     Timestamp: Sat 2019-11-02 15:25:48 PDT (15s ago)
  Command Line: wlfreerdp /u:cole.mickens@gmail.com /p:******** /v:192.168.1.11 /rfx +fonts
    Executable: /nix/store/nhmg4nrjjdsxcg5mpz4rgyzmwlxqj7yc-freerdp-2.0.0-rc4/bin/wlfreerdp
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (cole)
       Boot ID: f24f7427aac14a1480dd32950dab7055
    Machine ID: a424ec43f0684d2090d7ca6fe22ebf8a
      Hostname: xeep
       Storage: /var/lib/systemd/coredump/core.wlfreerdp.1000.f24f7427aac14a1480dd32950dab7055.3335.1572733548000000000000.lz4
       Message: Process 3335 (wlfreerdp) of user 1000 dumped core.

btGNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...

Reading symbols from /nix/store/nhmg4nrjjdsxcg5mpz4rgyzmwlxqj7yc-freerdp-2.0.0-rc4/bin/wlfreerdp...
(No debugging symbols found in /nix/store/nhmg4nrjjdsxcg5mpz4rgyzmwlxqj7yc-freerdp-2.0.0-rc4/bin/wlfreerdp)
[New LWP 3335]
[New LWP 3338]
[New LWP 3337]
[New LWP 3339]
[New LWP 3340]
[New LWP 3336]
[New LWP 3341]
[New LWP 3342]
[New LWP 3343]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/qn76sklvyalzw9ilnxz6sh0020gl2qn6-glibc-2.27/lib/libthread_db.so.1".
Core was generated by `wlfreerdp /u:cole.mickens@gmail.com /p:******** /v:192.168.1.11 /rfx +fonts'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9214960be0 in raise () from /nix/store/qn76sklvyalzw9ilnxz6sh0020gl2qn6-glibc-2.27/lib/libc.so.6
[Current thread is 1 (Thread 0x7f92106bbac0 (LWP 3335))]
(gdb) bt
#0  0x00007f9214960be0 in raise () from /nix/store/qn76sklvyalzw9ilnxz6sh0020gl2qn6-glibc-2.27/lib/libc.so.6
#1  0x00007f9214c1af90 in fatal_handler () from /nix/store/nhmg4nrjjdsxcg5mpz4rgyzmwlxqj7yc-freerdp-2.0.0-rc4/bin/../lib/libfreerdp2.so.2
#2  <signal handler called>
#3  0x00007f9212cb7274 in wl_proxy_marshal_constructor ()
   from /nix/store/641prxh0dppg0d0cd1hkhcs83sq75g7b-wayland-1.17.0/lib/libwayland-client.so.0
#4  0x00007f9214d71eb1 in UwacCreateWindowShm () from /nix/store/nhmg4nrjjdsxcg5mpz4rgyzmwlxqj7yc-freerdp-2.0.0-rc4/bin/../lib/libuwac0.so.0
#5  0x0000000000402e70 in wl_post_connect ()
#6  0x00007f9214c735d9 in freerdp_connect () from /nix/store/nhmg4nrjjdsxcg5mpz4rgyzmwlxqj7yc-freerdp-2.0.0-rc4/bin/../lib/libfreerdp2.so.2
#7  0x00000000004024e5 in main ()
(gdb) 

```

**Comment by akallabeth** [comment]
Does this affect nightlies too? Wayland client got some attention since then

**Comment by colemickens** [comment]
Sorry, I wrote the comment several times but failed to send, I guess - this issue does not affect nightlies. We can go ahead and close it. I look forward to a new release. Thank you for your work on FreeRDP!

**Comment by colemickens** [comment]
@akallabeth Is there a release planned soon? I just realized I dropped my patched package for my system and I'm back to hitting this. It'd be great to have a new version to package.
