### ISSUE TITLE
[CONFORMANCE] RDPBCGR: In Client Core Data, RDP client version number should be one of: 00000000, 00080001, 00080004, 00080005, 00080006, 00080007, 00080008, 00080009, 0008000A, 0008000B.

### ISSUE THREAD

**Issue by ligurio** [FreeRDP/FreeRDP#5902]
**Describe the bug**

Some time ago Microsoft opened an RDP specifications and then published testsuites for testing RDP client implementations (conformance tests) - https://github.com/Microsoft/WindowsProtocolTestSuites. I ran tests in testsuite RDPBCGR against xfreerdp and many of them failed with similar errors:
```
2020-02-21 17:04:07.396 [CheckFailed] Assert.IsTrue failed. In Client Core Data, RDP client version number should be one of: 00000000, 00080001, 00080004, 00080005, 00080006, 00080007, 00080008, 00080009, 0008000A, 0008000B.

2020-02-21 17:04:07.396 [Comment] at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.VerifyStructure(TS_UD_CS_CORE core) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\ClientRoleCaptureCode.cs:line 630 at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.VerifyPdu(Client_MCS_Connect_Initial_Pdu_with_GCC_Conference_Create_Request connectInitialPdu) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\ClientRoleCaptureCode.cs:line 120 at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ReceiveMcsConnectInitialPdu(Client_MCS_Connect_Initial_Pdu_with_GCC_Conference_Create_Request initialPdu) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2794 at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ReceiveLoop(StackPacket request) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2669

at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ExpectPacket[T](RdpbcgrServerSessionContext session, TimeSpan waitTimeSpan) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2241

at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ExpectPacket[T](TimeSpan timeout) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2252

2020-02-21 17:04:07.396 [Debug] Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.IsTrue failed. In Client Core Data, RDP client version number should be one of: 00000000, 00080001, 00080004, 00080005, 00080006, 00080007, 00080008, 00080009, 0008000A, 0008000B.===== Stack Trace ===== at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.VerifyStructure(TS_UD_CS_CORE core) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\ClientRoleCaptureCode.cs:line 630 at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.VerifyPdu(Client_MCS_Connect_Initial_Pdu_with_GCC_Conference_Create_Request connectInitialPdu) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\ClientRoleCaptureCode.cs:line 120 at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ReceiveMcsConnectInitialPdu(Client_MCS_Connect_Initial_Pdu_with_GCC_Conference_Create_Request initialPdu) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2794 at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ReceiveLoop(StackPacket request) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2669

at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ExpectPacket[T](RdpbcgrServerSessionContext session, TimeSpan waitTimeSpan) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2241

at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ExpectPacket[T](TimeSpan timeout) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2252=== End of Stack Trace === at Microsoft.Protocols.TestTools.AsynchronousErrorProcessor.Process() at Microsoft.Protocols.TestTools.AsynchronousErrorProcessor.ReportAsyncException(Exception checkerException)

at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ExpectPacket[T](RdpbcgrServerSessionContext session, TimeSpan waitTimeSpan) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2239

at Microsoft.Protocols.TestSuites.Rdpbcgr.RdpbcgrAdapter.ExpectPacket[T](TimeSpan timeout) in C:\Jenkins\workspace\ESRPCodeSign-TestSuite-withRegression-Pipeline\build\TestSuites\RDP\Client\src\Adapter\RDPBCGR\RdpbcgrAdapter.cs:line 2251

2020-02-21 17:04:07.396 [Comment] Trigger client to close all RDP connections for clean up.

2020-02-21 17:04:07.771 [Comment] RDP SUT Control Protocol Adapter: CommandId is 2: Success, agent: 10.16.170.60:4488.

2020-02-21 17:04:07.771 [Debug] The result of TriggerClientDisconnectAll is 1.

2020-02-21 17:04:07.771 [Comment] Stop RDP listening.
```

**To Reproduce**
1. Setup test stand as described in documentation: https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/RDP_ClientUserGuide.md, https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/RDP_Overview_ClientTestDesignSpecification.md
2. Build XFreeRDP client and run [Python wrapper](https://github.com/microsoft/WindowsProtocolTestSuites/tree/staging/TestSuites/RDP/RDPSUTControlAgent/Python) on Linux machine. `settings.ini`:
```
[general]
bind_ip_adress = 0.0.0.0
bind_port = 4488
buffer_size = 1024

[client]
# The command to create a negotiate-based rdp session.
# {{address}} must be present, they will be replaced with the actual address and port by the agent.
Negotiate = /home/sergeyb/backup_sdb/FreeRDP/build/client/X11/xfreerdp /t:RDPClient /cert-ignore /rfx /u:Administrator /p:Password01! /v:{{ address }}
# The command to create a negotiate-based fullscreen rdp session.
# {{address}} must be present, they will be replaced with the actual address and port by the agent.
NegotiateFullScreen = /home/sergeyb/backup_sdb/FreeRDP/build/client/X11/xfreerdp /t:RDPClient /f /rfx /u:Administrator /p:Password01! /v:{{ address }}
# The command to create a CredSSP rdp session.
# {{address}} must be present, they will be replaced with the actual address and port by the agent
DirectCredSSP = /home/sergeyb/backup_sdb/FreeRDP/build/client/X11/xfreerdp /t:RDPClient /rfx /u:Administrator /p:Password01! /v:{{ address }}
# The command to create a CredSSP fullscreen rdp session.
# {{address}} must be present, they will be replaced with the actual address and port by the agent
DirectCredSSPFullScreen = /home/sergeyb/backup_sdb/FreeRDP/build/client/X11/xfreerdp /t:RDPClient /f /rfx /u:Administrator /p:Password01! /v:{{ address }}
```
3. Start testing on Windows machine
4. See failed tests in a report generated by Windows Test Manager

**Actual behavior**

**Expected behavior**
All tests are passed

**Application details**
* Version: FreeRDP dc89923f4a3db2c5ae5d169ea80ba4d0ad29e899
* output of `/buildconfig`:

```
This is FreeRDP version 2.0.0-dev5 (dc89923f4)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 7.4.0
Target architecture: x64
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux, Windows 7 Enterprise SP1 x86_64
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Additional context**

RDPBCGR specification
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/5073f4ed-1e93-45e1-b039-6e30c385867c

**Comment by akallabeth** [comment]
looks like this is a bug in the test suite, current `[MS-RDPBCGR]` contains 0x0008000C for 10.7 clients/servers as well.

**Comment by nfedera** [comment]
@ligurio please [attach](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests )your test config `C:\MicrosoftProtocolTests\RDP\Client-Endpoint\3.20.1.0\Bin\RDP_ClientTestSuite.deployment.ptfconfig` file.

**Comment by nfedera** [comment]
@ligurio it looks like you are using an outdated version of the test suite.
The current code in staging does already know the `0x0008000C` value:
https://github.com/microsoft/WindowsProtocolTestSuites/blob/staging/ProtoSDK/MS-RDPBCGR/Types.cs#L6971

```C#
    public enum TS_UD_CS_CORE_version_Values : uint
    {
         ...
        /// <summary>
        /// RDP 10.7 clients
        /// </summary>
        V10 = 0x0008000C,
    }
```

**Comment by nfedera** [comment]
@ligurio quite outdated actually. V10 was already added in April 2019:
https://github.com/microsoft/WindowsProtocolTestSuites/commit/c76dd7ed6fd05d5bb8889249ccee6ca9916b65c5#diff-1748bd62bc94f4d4ad77c9a78f019c1b
