### ISSUE TITLE
Network disconnects since TPKT commits on issue #5946

### ISSUE THREAD

**Issue by user-72632** [FreeRDP/FreeRDP#5951]
**Describe the bug**
After issue #5946 I am experiencing network disconnects.

**To Reproduce**
1. Start xfreerdp and connect to Windows 2012 R2 RDS server.
2. Bring up a file in  notepad or otherwise expose text to copy and paste. 
3. Highlight and copy the text.
4. Return back to the desktop session and try to paste.
5. Before you are allowed to paste, your session disappears.

**Expected behavior**
You return back to your session and paste the text.

**Screenshots**
N/A

**Application details**
* Version: latest nightly xfreerdp version
* Command line: any command line that defaults to use clipboard redirection.
* OS version connecting to: Windows 2012 R2 RDS Server
* If available the log output from a run with `/log-level:trace` 
[14:40:41:511] [4438:4488] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:40:41:511] [4438:4488] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:40:42:091] [4438:4488] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:40:42:095] [4438:4503] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:40:42:123] [4438:4503] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:40:42:129] [4438:4501] [WARN][com.freerdp.channels.cliprdr.common] - [cliprdr_packet_format_list_new] called with invalid type 00000000
[14:40:46:731] [4438:4488] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:40:51:371] [4438:4488] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:40:54:747] [4438:4503] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:40:54:747] [4438:4488] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:40:58:640] [4438:4488] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:41:00:129] [4438:4488] [ERROR][com.freerdp.core.rdp] - rdp_recv_tpkt_pdu: freerdp_channel_process() fail
[14:41:00:129] [4438:4488] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[14:41:00:129] [4438:4488] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[14:41:00:129] [4438:4488] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[14:40:39:199] [4438:4488] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[14:40:39:199] [4438:4488] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[14:40:39:200] [4438:4488] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[14:40:39:200] [4438:4488] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[14:40:39:200] [4438:4488] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[14:40:39:545] [4438:4488] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[14:40:39:553] [4438:4488] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[14:40:39:553] [4438:4488] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[14:40:41:113] [4438:4488] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[14:40:41:113] [4438:4488] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[14:40:41:149] [4438:4488] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[14:40:41:149] [4438:4488] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[14:40:41:150] [4438:4500] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [Temp] (static)
[14:40:41:150] [4438:4488] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[14:40:41:556] [4438:4488] [INFO][com.freerdp.core] - rdp_set_error_info:freerdp_set_last_error_ex resetting error state
[14:40:42:417] [4438:4500] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: Temp (type=8 id=1)
[14:41:00:129] [4438:4488] [INFO][com.freerdp.client.common] - Network disconnect!
[14:41:16:088] [4542:4554] [WARN][com.freerdp.channels.cliprdr.common] - [cliprdr_packet_format_list_new] called with invalid type 00000000
[14:41:16:675] [4542:4556] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:41:16:675] [4542:4548] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:41:25:233] [4542:4548] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:41:26:286] [4542:4548] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:41:26:290] [4542:4548] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:41:29:645] [4542:4548] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:41:29:648] [4542:4548] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:41:33:424] [4542:4548] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:41:33:427] [4542:4556] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:41:33:431] [4542:4548] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:41:33:431] [4542:4548] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:41:36:904] [4542:4548] [WARN][com.freerdp.client.x11] - X11 trying to lock although already locked!
[14:41:36:904] [4542:4548] [WARN][com.freerdp.client.x11] - X11: trying to unlock although not locked!
[14:41:43:863] [4542:4548] [ERROR][com.freerdp.core.rdp] - rdp_recv_tpkt_pdu: freerdp_channel_process() fail
[14:41:43:863] [4542:4548] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[14:41:43:863] [4542:4548] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[14:41:43:864] [4542:4548] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

=================================================================
==4542==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 136 byte(s) in 1 object(s) allocated from:
    #0 0x7f08f5273720 in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9720)
    #1 0x7f08f509f7a9  (/lib/x86_64-linux-gnu/libX11.so.6+0x567a9)

Indirect leak of 1360 byte(s) in 17 object(s) allocated from:
    #0 0x7f08f5273518 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9518)
    #1 0x7f08f509f77e  (/lib/x86_64-linux-gnu/libX11.so.6+0x5677e)

Indirect leak of 112 byte(s) in 14 object(s) allocated from:
    #0 0x7f08f5273330 in __interceptor_malloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9330)
    #1 0x7f08f50a0102  (/lib/x86_64-linux-gnu/libX11.so.6+0x57102)

Indirect leak of 80 byte(s) in 3 object(s) allocated from:
    #0 0x7f08f5273720 in __interceptor_realloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9720)
    #1 0x7f08f50a001f  (/lib/x86_64-linux-gnu/libX11.so.6+0x5701f)

SUMMARY: AddressSanitizer: 1688 byte(s) leaked in 35 allocation(s).

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian 10, Gnome, Wayland
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] N/A

**Comment by akallabeth** [comment]
Commandline and /buildconfig please

**Comment by akallabeth** [comment]
It might already be fixed, so be sure to check again with next nightly

**Comment by user-72632** [comment]
OK, I just built master and it appears to be fixed already as you mentioned, sorry. I still get a lot of those warnings about X11 locking/unlocking though. Not sure what that is all about.

**Comment by akallabeth** [comment]
Ok, thx. Good to know. The x11 one is still pending.
