### ISSUE TITLE
[android] Can't build native libraries on Mac

### ISSUE THREAD

**Issue by beersheba** [FreeRDP/FreeRDP#6104]
I'm trying to build native libraries for Android, [as described here](https://github.com/FreeRDP/FreeRDP/blob/master/docs/README.android).

I installed the latest NDK (r21) with Android Studio. 
Here are my paths:
```
export ANDROID_SDK=~/Library/Android/sdk
export ANDROID_NDK=~/Library/Android/sdk/ndk/ndk-bundle
```

I run the script like this
`./scripts/android-build-freerdp.sh --ndk $ANDROID_NDK --sdk $ANDROID_SDK`

 and getting this error in the end:

```
[RUN] cp libcrypto.so libssl.so /Users/andrey/playground/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a/
[RUN] cd /Users/andrey/playground/FreeRDP
[RUN] cp -L -R /Users/andrey/playground/FreeRDP/scripts/../build/openssl/include/openssl /Users/andrey/playground/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a/include/
[RUN] cd /Users/andrey/playground/FreeRDP
[RUN] mkdir -p /Users/andrey/playground/FreeRDP/scripts/../build/freerdp-build/armeabi-v7a
[RUN] cd /Users/andrey/playground/FreeRDP/scripts/../build/freerdp-build/armeabi-v7a
[RUN] export ANDROID_NDK=/Users/andrey/Library/Android/sdk/ndk-bundle
[RUN] -DANDROID_NDK=/Users/andrey/Library/Android/sdk/ndk-bundle -DANDROID_NATIVE_API_LEVEL=android-26 -DCMAKE_TOOLCHAIN_FILE=/Users/andrey/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=/Users/andrey/playground/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_MAKE_PROGRAM=make -DWITH_JPEG=OFF -DWITH_OPENH264=OFF -DANDROID_ABI=armeabi-v7a -DCMAKE_INSTALL_PREFIX=/Users/andrey/playground/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a -DCMAKE_INSTALL_LIBDIR=. /Users/andrey/playground/FreeRDP/scripts/..
./scripts/android-build-common.sh: line 71: -DANDROID_NDK=/Users/andrey/Library/Android/sdk/ndk-bundle: No such file or directory
[ERROR] -DANDROID_NDK=/Users/andrey/Library/Android/sdk/ndk-bundle -DANDROID_NATIVE_API_LEVEL=android-26 -DCMAKE_TOOLCHAIN_FILE=/Users/andrey/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=/Users/andrey/playground/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_MAKE_PROGRAM=make -DWITH_JPEG=OFF -DWITH_OPENH264=OFF -DANDROID_ABI=armeabi-v7a -DCMAKE_INSTALL_PREFIX=/Users/andrey/playground/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a -DCMAKE_INSTALL_LIBDIR=. /Users/andrey/playground/FreeRDP/scripts/.. retured 127
```

Some lib files are created in jniLibs directory inside Android project (libcrypto.so, libssl.so). 

But when I run the app and try to connect, it crashes on instantiating freerdp.

```
2020-04-22 12:23:08.630 25073-25073/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.freerdp.afreerdp, PID: 25073
    java.lang.UnsatisfiedLinkError: No implementation found for long com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new(android.content.Context) (tried Java_com_freerdp_freerdpcore_services_LibFreeRDP_freerdp_1new and Java_com_freerdp_freerdpcore_services_LibFreeRDP_freerdp_1new__Landroid_content_Context_2)
        at com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new(Native Method)
        at com.freerdp.freerdpcore.services.LibFreeRDP.newInstance(LibFreeRDP.java:113)
        at com.freerdp.freerdpcore.application.GlobalApp.createSession(GlobalApp.java:95)
        at com.freerdp.freerdpcore.presentation.SessionActivity.connect(SessionActivity.java:447)
        at com.freerdp.freerdpcore.presentation.SessionActivity.processIntent(SessionActivity.java:434)
        at com.freerdp.freerdpcore.presentation.SessionActivity.access$500(SessionActivity.java:67)
        at com.freerdp.freerdpcore.presentation.SessionActivity$5.onGlobalLayout(SessionActivity.java:247)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1056)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2690)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7751)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
        at android.view.Choreographer.doCallbacks(Choreographer.java:854)
        at android.view.Choreographer.doFrame(Choreographer.java:789)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-04-22 12:23:08.634 25073-25073/? E/MQSEventManagerDelegate: failed to get MQSService.
```

I tried to run the script with the other ndk releases (r15c, 16), but always getting the same error.
What I'm doing wrong?

**Comment by akallabeth** [comment]
Seems like I missed one export. Do `export ANDROID_NDK_HOME=$ANDROID_NDK` and it should work.

**Comment by beersheba** [comment]
@akallabeth thanks for the answer! 
it doesn't help. getting the same, on r15 too

```
export ANDROID_SDK=/Users/andrey/Library/Android/sdk
export ANDROID_NDK=/Users/andrey/Downloads/android-ndk-r15c
export ANDROID_NDK_HOME=$ANDROID_NDK

./scripts/android-build-common.sh: line 71: -DANDROID_NDK=/Users/andrey/Downloads/android-ndk-r15c: No such file or directory
```

**Comment by akallabeth** [comment]
@beersheba which os are you working on? Mac? you might want to check if you have `realpath` and `dirname` installed

**Comment by beersheba** [comment]
@akallabeth sorry, I didn't mention it. yes, I'm on Mac.
realpath and dirname installed

**Comment by floppym** [comment]
Seems like it is failing to find the `cmake` binary in the Android SDK, which causes `CMAKE_PROGRAM` to be empty.

https://github.com/FreeRDP/FreeRDP/blob/2.0.0/scripts/android-build-common.sh#L15

https://github.com/FreeRDP/FreeRDP/blob/2.0.0/scripts/android-build-freerdp.sh#L143

**Comment by beersheba** [comment]
@floppym what you suggest?

**Comment by floppym** [comment]
I suggest figuring out where the cmake binary went.

**Comment by akallabeth** [comment]
@beersheba Ah, @floppym did remind me, the latest version of the script explicitly uses the `CMake` shipped with android `NDK` and that may be an optional install (did not check, always have it installed anyway)

**Comment by beersheba** [comment]
@akallabeth @floppym 
i have cmake installed by brew

```
Andreys-MBP:FreeRDP andrey$ which cmake
/usr/local/bin/cmake
Andreys-MBP:FreeRDP andrey$ cmake --version
cmake version 3.17.1
```

also there's cmake inside android sdk directory, installed by Android Studio
what should I change in script to make it run?

**Comment by akallabeth** [comment]
@beersheba check if you have the `$ANDROID_NDK/build/cmake` folder.
I have a local installation with the side by side NDK and cmake from SDK and that installs that.

**Comment by akallabeth** [comment]
@beersheba the script should detect all `cmake` installations of the SDK if `ANDROID_SDK` is defined.

**Comment by beersheba** [comment]
@akallabeth 
yes i have, with toolchain only inside

```
Andreys-MBP:3.10.2.4988404 andrey$ ls -la /Users/andrey/Downloads/android-ndk-r15c/build/cmake/
total 64
drwxr-xr-x@  3 andrey  staff     96 Jul 21  2017 .
drwxr-xr-x@ 18 andrey  staff    576 Jul 21  2017 ..
-rw-r--r--@  1 andrey  staff  28999 Jul 21  2017 android.toolchain.cmake
```

**Comment by akallabeth** [comment]
@beersheba then check the value of `CMAKE_PROGRAM` or set it yorself to the `SDK` cmake binary (absolute path)
can be checked in `scripts/android-build-common.sh`

**Comment by beersheba** [comment]
Found the issue:

`find` command on Mac doesn't understand the `-executable` argument used in `scripts/android-build-common.sh`

So change
```
find $ANDROID_SDK/cmake -name cmake -type f -executable -print -quit
```
to
```
find $ANDROID_SDK/cmake -name cmake -type f -print -quit
```
make it work

**Comment by beersheba** [comment]
So here are the steps:

1. Install CMake and NDK using Android Studio (Tools - SDK manager)
2. Install [realpath](https://github.com/harto/realpath-osx)
3. Export path
```
export ANDROID_SDK=~/Library/Android/sdk
export ANDROID_NDK=~/Library/Android/sdk/ndk-bundle
export ANDROID_NDK_HOME=$ANDROID_NDK
```
4. [Edit](https://github.com/FreeRDP/FreeRDP/issues/6104#issuecomment-619400648) `android-build-common.sh` (if needed)
5. Run the script. 
```
./scripts/android-build-freerdp.sh --ndk $ANDROID_NDK --sdk $ANDROID_SDK
```
It will repeat a few times, generating libs for each architecture (armeabi-v7a, x86 etc) into `/FreeRDP/client/Android/Studio/freeRDPCore/src/main/jniLibs`.

**Comment by beersheba** [comment]
@akallabeth can you check this PR https://github.com/FreeRDP/FreeRDP/pull/6126?
