### ISSUE TITLE
memory leak in proxy code

### ISSUE THREAD

**Issue by sss123next** [FreeRDP/FreeRDP#6414]
```
Direct leak of 14 byte(s) in 1 object(s) allocated from:
    #0 0x4cc4f7 in calloc /var/tmp/paludis/build/dev-libs-compiler-rt-10.0.1/work/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x7f51d693ce90 in proxy_parse_uri /home/sss/install/git/work/FreeRDP/libfreerdp/core/proxy.c:356:28
    #2 0x7f51d6939a8c in proxy_read_environment /home/sss/install/git/work/FreeRDP/libfreerdp/core/proxy.c:284:4
    #3 0x7f51d69393c0 in proxy_prepare /home/sss/install/git/work/FreeRDP/libfreerdp/core/proxy.c:79:3
    #4 0x7f51d6950b27 in transport_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/transport.c:419:7
    #5 0x7f51d684d4cf in nego_tcp_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:302:25
    #6 0x7f51d684e874 in nego_transport_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:317:7
    #7 0x7f51d684ddd9 in nego_attempt_nla /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:457:7
    #8 0x7f51d68456c2 in nego_send /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:817:3
    #9 0x7f51d684469a in nego_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/nego.c:185:4
    #10 0x7f51d6905465 in rdp_client_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/connection.c:333:7
    #11 0x7f51d68c7e14 in freerdp_connect /home/sss/install/git/work/FreeRDP/libfreerdp/core/freerdp.c:197:11
    #12 0x592e84 in xf_client_thread /home/sss/install/git/work/FreeRDP/client/X11/xf_client.c:1524:11
    #13 0x7f51d62d893b in thread_launcher /home/sss/install/git/work/FreeRDP/winpr/libwinpr/thread/thread.c:327:7
    #14 0x7f51d608353e  (/usr/x86_64-pc-linux-gnu/lib/libpthread.so.0+0x953e)

SUMMARY: AddressSanitizer: 14 byte(s) leaked in 1 allocation(s).


```

**Comment by sss123next** [comment]
this happening only if disconnect occurs on early connection state.

**Comment by akallabeth** [comment]
@sss123next which version are you using?
