### ISSUE TITLE
Android App Crashes After Clicking On Newly Created Manual Connection

### ISSUE THREAD

**Issue by aliaiden** [FreeRDP/FreeRDP#6910]
I have cloned v2.3.2 release.
Opened the folder /client/Android/Studio in Android Studio.
With a little changes in build.gradle I managed to run the app on my phone. I created a manual connection but after tapping on it app crashed with below log.

2021-03-19 15:45:02.962 11198-11198/com.freerdp.afreerdp E/reerdp.afreerd: No implementation found for long com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new(android.content.Context) (tried Java_com_freerdp_freerdpcore_services_LibFreeRDP_freerdp_1new and Java_com_freerdp_freerdpcore_services_LibFreeRDP_freerdp_1new__Landroid_content_Context_2)
2021-03-19 15:45:02.964 11198-11198/com.freerdp.afreerdp E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.freerdp.afreerdp, PID: 11198
java.lang.UnsatisfiedLinkError: No implementation found for long com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new(android.content.Context) (tried Java_com_freerdp_freerdpcore_services_LibFreeRDP_freerdp_1new and Java_com_freerdp_freerdpcore_services_LibFreeRDP_freerdp_1new__Landroid_content_Context_2)
at com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new(Native Method)
at com.freerdp.freerdpcore.services.LibFreeRDP.newInstance(LibFreeRDP.java:113)
at com.freerdp.freerdpcore.application.GlobalApp.createSession(GlobalApp.java:95)
at com.freerdp.freerdpcore.presentation.SessionActivity.connect(SessionActivity.java:447)
at com.freerdp.freerdpcore.presentation.SessionActivity.processIntent(SessionActivity.java:434)
at com.freerdp.freerdpcore.presentation.SessionActivity.access$500(SessionActivity.java:67)
at com.freerdp.freerdpcore.presentation.SessionActivity$5.onGlobalLayout(SessionActivity.java:247)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1082)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3210)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2225)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9126)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
at android.view.Choreographer.doCallbacks(Choreographer.java:797)
at android.view.Choreographer.doFrame(Choreographer.java:732)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8167)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

Please tell me what is causing this crash and how can I fix and get it running and connecting to a desktop screen of a PC. Thanks.

**Comment by akallabeth** [comment]
Please read `docs/README.android`.
you need to build the native libraries before the gradle run

**Comment by shahkamranqader** [comment]
i didn't found solution over there, already build libraries before gradle run. same problem

**Comment by akallabeth** [comment]
@shahkamranqader you did not. check if the build was successful and the `.so` files are in the apk (that is just a zip file, so you can open it that way)
If not (that is exactly your issue) start from scratch and check the build was successful.
There is nothing more to do to get it build.

**Comment by aliaiden** [comment]
Thanks for docs/README.android reference. I installed Cygwin64 Terminal to run 'bash ./scripts/android-build-freerdp.sh --ndk <ANDROID_NDK> --sdk <ANDROID_SDK>'

it ran and gave me

**find: '/cmake': No such file or directory                                                                               which: no ccache in (/mingw64/bin:/usr/bin:/c/Users/w-t/bin:/c/Users/w-t/AppData/Local/Yarn/config/global/node_modules/.bin:/c/Users/w-t/AppData/Roaming/npm:/c/Users/w-t/AppData/Roaming/Composer/vendor/bin:/c/laragon/bin/laragon/utils:/c/laragon/bin/mysql/mysql-5.7.24-winx64/bin:/c/laragon/bin/php/php-7.2.19-Win32-VC15-x64:/c/laragon/bin/composer:/c/laragon/bin/apache/httpd-2.4.35-win64-VC15/bin:/c/laragon/bin/redis/redis-x64-3.2.100:/c/laragon/bin/nodejs/node-v12:/c/laragon/bin/nginx/nginx-1.16.0:/c/laragon/bin/notepad++:/c/laragon/bin/telnet:/c/laragon/bin/ngrok:/bin:/cmd:/usr/bin:/mingw64/bin:/c/laragon/bin:/c/laragon/usr/bin:/c/laragon/bin/putty:/c/laragon/bin/cmder/bin:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/ProgramData/chocolatey/bin:/c/Program Files/Java/jdk1.8.0_181:/c/Program Files/Git/cmd:/c/Program Files/MongoDB/Server/4.2/bin:/c/WINDOWS/System32/OpenSSH:/c/Program Files/openssl/bin:/c/Program Files/nodejs:/c/Program Files (x86)/Yarn/bin:/c/Users/w-t/AppData/Local/Microsoft/WindowsApps:/c/Users/w-t/AppData/Local/Android/Sdk/platform-tools:/c/Users/w-t/AppData/Local/Android/Sdk/platforms:/c/Users/w-t/AppData/Local/Android/Sdk/tools:/c/Users/w-t/AppData/Local/Android/Sdk/tools/bin:/c/Users/w-t/AppData/Local/Android/Sdk/emulator:/c/Program Files/Java/jdk1.8.0_181/bin:/c/Users/w-t/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/w-t/AppData/Roaming/npm:/c/Users/w-t/AppData/Local/Yarn/bin:/c/Program Files/Git/usr/bin:/c/Program Files/Git/usr/share/vim/vim74:/c/laragon/bin/cmder)                                               ./scripts/android-build-common.sh: line 30: [: too many arguments                                                       ./scripts/android-build-common.sh: line 34: [: too many arguments                                                       ./scripts/android-build-freerdp.sh: line 21: source: /d/alihaider/New: is a directory                                   ./scripts/android-build-freerdp.sh: line 75: [: too many arguments                                                      ./scripts/android-build-freerdp.sh: line 80: [: too many arguments                                                      [RUN] mkdir -p /d/alihaider/New folder/New folder/FreeRDP-master                                                        ./scripts/android-build-freerdp.sh: line 152: [: -eq: unary operator expected                                           ./scripts/android-build-freerdp.sh: line 152: [: -eq: unary operator expected                                           ./scripts/android-build-freerdp.sh: line 152: [: -eq: unary operator expected                                           ./scripts/android-build-freerdp.sh: line 152: [: -eq: unary operator expected                                           Successfully build library for architectures armeabi-v7a x86 x86_64 arm64-v8a** 



But I did not find directory client/Android/Studio/freeRDPCore/src/main/jniLibs and library builds. Also the app crashed just as mentioned above.
Can you tell me what is the problem here?
