### ISSUE TITLE
Connection to Windows 10 with Build 3.0.0-dev (e8d146be7) not possible anymore - certification validation rules seem to be to strict 

### ISSUE THREAD

**Issue by mmattes** [FreeRDP/FreeRDP#7045]
**Describe the bug**
Just updated to 3.0.0-dev (e8d146be7) which should be the latest nightly build and i am unable to connect to my workplace remote session. Before it worked fine. 

**To Reproduce**
xfreerdp /u:xxx /v:xxx.xx.de /f /floatbar /bpp:24 /multimon /monitors:0,2 /sound  

**Expected behavior**
Connection should work as with the build i had used before 

**Application details**
* FreeRDP version (`xfreerdp /version`)
3.0.0-dev (e8d146be7) 

* Command line used
xfreerdp /u:xxx /v:xxx.xx.de /f /floatbar /bpp:24 /multimon /monitors:0,2 /sound  

* Output of `xfreerdp /buildconfig`
```
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_STRNDUP=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_FUSE=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp-nightly-3.0.0+0~20210526014818.962~1.gbpe8d146=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope -DWINPR_DLL
Compiler:            GNU, 7.3.0
Target architecture: x64
```

* OS version connecting to (server side)
Windows 10 

* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
```
[21:33:01:658] [8074:8074] [DEBUG][com.freerdp.client.common] - This is 3.0.0-dev Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_STRNDUP=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_FUSE=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp-nightly-3.0.0+0~20210526014818.962~1.gbpe8d146=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope -DWINPR_DLL
Compiler:            GNU, 7.3.0
Target architecture: x64

[21:33:01:659] [8074:8076] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[21:33:01:659] [8074:8076] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[21:33:01:659] [8074:8076] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[21:33:01:659] [8074:8076] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[21:33:01:659] [8074:8076] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[21:33:01:659] [8074:8076] [DEBUG][com.fr[21:33:02:102] [8074:8076] [ERROR][com.freerdp.crypto] - certificate does not have a subject!
[21:33:02:102] [8074:8076] [WARN][com.freerdp.crypto] - Certificate verification failure 'unable to get local issuer certificate (20)' at stack position 0
[21:33:02:102] [8074:8076] [WARN][com.freerdp.crypto] - (nil)
[21:33:02:102] [8074:8076] [ERROR][com.freerdp.crypto] - certificate does not have a subject!
[21:33:02:102] [8074:8076] [ERROR][com.freerdp.crypto] - certificate does not have a subject!
ASAN:DEADLYSIGNAL
=================================================================
==8074==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f5893054e20 bp 0x7f587889bd50 sp 0x7f587889b4b0 T1)
==8074==The signal is caused by a READ memory access.
==8074==Hint: address points to the zero page.
    #0 0x7f5893054e1f  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x59e1f)
    #1 0x7f58914c52f9  (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x1332f9)
    #2 0x7f58914c64fe in certificate_store_contains_data (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x1344fe)
    #3 0x7f58914cdda8  (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x13bda8)
    #4 0x7f589157c95f  (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x1ea95f)
    #5 0x7f589157e04b  (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x1ec04b)
    #6 0x7f58914f25dc  (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x1605dc)
    #7 0x7f58914f4781  (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x162781)
    #8 0x7f58915556b0  (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x1c36b0)
    #9 0x7f589153506a in freerdp_connect (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x1a306a)
    #10 0x560144b268e2  (/opt/freerdp-nightly/bin/xfreerdp+0x608e2)
    #11 0x7f5890a4de4e  (/opt/freerdp-nightly/bin/../lib/libwinpr3.so.3+0x163e4e)
    #12 0x7f58900dd6da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
    #13 0x7f589061a71e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12171e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x59e1f) 
Thread T1 created by T0 here:
    #0 0x7f5893032d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
    #1 0x7f5890a4d8ce  (/opt/freerdp-nightly/bin/../lib/libwinpr3.so.3+0x1638ce)
    #2 0x7f5890a4e3aa in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr3.so.3+0x1643aa)
    #3 0x560144b1d51f  (/opt/freerdp-nightly/bin/xfreerdp+0x5751f)
    #4 0x560144ada6d1  (/opt/freerdp-nightly/bin/xfreerdp+0x146d1)
    #5 0x7f589051abf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)

==8074==ABORTING

```

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Mint
 - Architecture: AMD64

**Comment by mmattes** [comment]
Did some research, as i need a working freerdp tomorrow, this commit broke it: https://github.com/FreeRDP/FreeRDP/commit/b494a193db5bba20dfc476d08690655210a6a7fb

A local build with the commit before this one works fine for me. 

Subject and Common Name on the certificate of my workplace Windows 10 system seems to be empty. This is as far as I know a default Win 10 installation. Here is the output of a working xfreerdp version. 

```
Certificate details for xxx.xxxx.de:3389 (RDP-Server):
	Common Name: (null)
	Subject:     (null)
	Issuer:      DC = de, DC = xxxx, CN = XXXX GmbH
	Thumbprint:  8d:f5:2d:22:7c:3f:5b:92:3d:1d:2b:95:09:b3:49:d9:1c:dc:dd:92:44:69:36:11:3a:32:c9:0b:9f:c6:c8:87
The above X.509 certificate could not be verified, possibly because you do not have
the CA certificate in your certificate store, or the certificate has expired.
Please look at the OpenSSL documentation on how to add a private CA to the store.
Do you trust the above certificate? (Y/T/N) y
```

**Comment by akallabeth** [comment]
@mmattes thanks for the report, updated the unit tests and fixed NULL checks.
