### ISSUE TITLE
wlfreerdp crash in 

### ISSUE THREAD

**Issue by dagbdagb** [FreeRDP/FreeRDP#7279]
**Found a bug? - We would like to help you and smash the bug away.**
1. __Please don't "report" questions as bugs. For these (questions/build instructions/...) please use one of the following means of contact:__
   * We are reachable via:
    * Matrix room : #FreeRDP:matrix.org (main)
    * XMPP channel: #FreeRDP#matrix.org@matrix.org (bridged)
    * IRC channel : #freerdp @ irc.oftc.net (bridged)
   * We are reachable via mailing list <freerdp-devel@lists.sourceforge.net>
   * Try our mailing list for discussions/questions
1. Before reporting a bug have a look into our issue tracker to see if the bug was already reported and you can add some additional information.
1. If it's a __new__ bug - create a new issue.
1. For more details see https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Describe the bug**
Using wlfreerdp, switching away from the active desktop will very frequently cause the client to crash.

**To Reproduce**
Start wlfreerdp, get remote desktop, switch away from active desktop with designated keyboard combo, client crashes.

**Expected behavior**
Start wlfreerdp, get remote desktop, switch away from active desktop with designated keyboard combo, client doesn't crash.

**Screenshots**

**Application details**
* FreeRDP version: wlfreerdp 2.4.0 and 3.0.0-dev (a0421)
* Command line used : -v host -u user -h height -w width
* Output of `wlfreerdp /buildconfig`
This is FreeRDP version 3.0.0-dev (ba0da0421)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_PIXMAN_REGION=OFF HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_STRNDUP=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_FREERDP_DEPRECATED=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=OFF WITH_SERVER_INTERFACE=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=ON WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_X11=OFF WITH_X264=OFF WITH_XCURSOR=OFF WITH_XEXT=OFF WITH_XFIXES=OFF WITH_XI=OFF WITH_XINERAMA=OFF WITH_XKBFILE=OFF WITH_XRANDR=OFF WITH_XRENDER=OFF WITH_XSHM=OFF WITH_XV=OFF WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope
Compiler:            GNU, 10.3.0
Target architecture: x64

* OS version connecting to (server side)
Windows Server 2019

* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
I was not able to come up with something that worked, based on the above suggestion. But I have a stacktrace:

==24099==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000039de0 at pc 0x7f74aad9d6cf bp 0x7ffc851f8720 sp 0x7ffc851f8710
READ of size 4 at 0x602000039de0 thread T0
    #0 0x7f74aad9d6ce in keyboard_handle_key (/usr/local/bin/../lib64/libuwac0.so.0+0x116ce)
    #1 0x7f74a8585e09  (/usr/lib64/libffi.so.8+0x6e09)
    #2 0x7f74a8585398  (/usr/lib64/libffi.so.8+0x6398)
    #3 0x7f74a9f5f121  (/usr/lib64/libwayland-client.so.0+0x9121)
    #4 0x7f74a9f5b979  (/usr/lib64/libwayland-client.so.0+0x5979)
    #5 0x7f74a9f5d02b in wl_display_dispatch_queue_pending (/usr/lib64/libwayland-client.so.0+0x702b)
    #6 0x7f74aad96d87 in display_dispatch_events (/usr/local/bin/../lib64/libuwac0.so.0+0xad87)
    #7 0x7f74aad98d8e in UwacDisplayDispatch (/usr/local/bin/../lib64/libuwac0.so.0+0xcd8e)
    #8 0x55aa820c6d85 in main (/usr/local/bin/wlfreerdp+0x6d85)
    #9 0x7f74aa3407fc in __libc_start_main (/lib64/libc.so.6+0x237fc)
    #10 0x55aa820c7b89 in _start (/usr/local/bin/wlfreerdp+0x7b89)

0x602000039de0 is located 0 bytes to the right of 16-byte region [0x602000039dd0,0x602000039de0)
allocated by thread T0 here:
    #0 0x7f74ab03fac7 in __interceptor_malloc (/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/libasan.so.6+0xb3ac7)
    #1 0x7f74a9f5fcaa in wl_array_add (/usr/lib64/libwayland-client.so.0+0x9caa)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/local/bin/../lib64/libuwac0.so.0+0x116ce) in keyboard_handle_key
Shadow bytes around the buggy address:
  0x0c047ffff360: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fd
  0x0c047ffff370: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047ffff380: fa fa fd fd fa fa fd fd fa fa 00 04 fa fa fd fa
  0x0c047ffff390: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x0c047ffff3a0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x0c047ffff3b0: fa fa fd fa fa fa fd fa fa fa 00 00[fa]fa fa fa
  0x0c047ffff3c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047ffff3d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047ffff3e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047ffff3f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c047ffff400: fa fa fd fa fa fa fd fd fa fa fd fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==24099==ABORTING

* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and compiler can help
exact git commit shown above. 
-DWITH_SANITIZE_ADDRESS=ON

**Environment (please complete the following information):**
Gentoo Linux, AMD gfx, wayland+wayfire, no exotic compiler flags, gcc 10.3

**Additional context**
I notice that wlfreerdp.c has not been touched in ~30 months. Code may be out of date.

I'll provide specific details on request.

**Comment by mbakhoff** [comment]
I also started getting crashes after switching from X to wayland when using alt-tab. Using freerdp 2.8.0. Caught a few crashes in gdb, see the logs here https://gist.github.com/mbakhoff/ba466bc530d5e50528abebc90c6c362d

**Comment by peterhoeg** [comment]
My workaround in a KDE Plasma Wayland  session is simply to use xfreerdp instead. `wlfreerdp` has proven extremely unstable for me.

**Comment by akallabeth** [comment]
@mbakhoff 2 of your 3 crash logs look like a bug in `memcpy` (maybe too aggressive optimization flags?)

**Comment by hardening** [comment]
@mbakhoff in crash3 either it's a memory corruption or the UwacWindow has its buffer released (that's the only explanation for a region with `data==NULL`)
