### ISSUE TITLE
Memory leak in rdpsnd

### ISSUE THREAD

**Issue by ignazp** [FreeRDP/FreeRDP#7411]
We built freerdp on Linux with following parameters 

```
-DWITH_CLIENT=OFF -DWITH_SERVER=OFF -DWITH_ALSA=OFF -DWITH_CAIRO=OFF -DWITH_CUPS=OFF -DWITH_CHANNELS=ON -DBUILTIN_CHANNELS=ON -DWITH_FFMPEG=OFF -DWITH_IPP=OFF -DWITH_JPEG=ON -DWITH_LAME=OFF -DWITH_MANPAGES=OFF -DWITH_PCSC=OFF -DWITH_PULSE=OFF -DWITH_ZLIB=ON -DWITH_X264=OFF -DWITH_OPENSSL=ON -DCHANNEL_URBDRC=OFF
```

and we are seeing the following leak using ASAN
```
Direct leak of 2576 byte(s) in 46 object(s) allocated from:
    #0 0x7f59567a857d in malloc (/lib64/libasan.so.4+0xd857d)
    #1 0x7f594bf5f485 in Stream_New winpr/libwinpr/utils/stream.c:85
    #2 0x7f594bf6582d in StreamPool_Take winpr/libwinpr/utils/collections/StreamPool.c:173
    #3 0x7f594c259621 in rdpsnd_on_data_received channels/rdpsnd/client/rdpsnd_main.c:1488
    #4 0x7f594c2538ae in dvcman_receive_channel_data channels/drdynvc/client/drdynvc_main.c:728
    #5 0x7f594c2547d1 in drdynvc_process_data channels/drdynvc/client/drdynvc_main.c:1169
    #6 0x7f594c2547d1 in drdynvc_order_recv channels/drdynvc/client/drdynvc_main.c:1235
    #7 0x7f594c2547d1 in drdynvc_virtual_channel_client_thread channels/drdynvc/client/drdynvc_main.c:1389
    #8 0x7f594bf85756 in thread_launcher winpr/libwinpr/thread/thread.c:316
    #9 0x7f595497940a in start_thread (/lib64/libpthread.so.0+0x740a)
    #10 0x7f59546b440e in __GI___clone (/lib64/libc.so.6+0xed40e)

Direct leak of 56 byte(s) in 1 object(s) allocated from:
    #0 0x7f59567a857d in malloc (/lib64/libasan.so.4+0xd857d)
    #1 0x7f594bf5f485 in Stream_New winpr/libwinpr/utils/stream.c:85
    #2 0x7f594bf6582d in StreamPool_Take winpr/libwinpr/utils/collections/StreamPool.c:173
    #3 0x7f594c259621 in rdpsnd_on_data_received channels/rdpsnd/client/rdpsnd_main.c:1488
    #4 0x7f594c2547d1 in drdynvc_process_data channels/drdynvc/client/drdynvc_main.c:1169
    #5 0x7f594c2547d1 in drdynvc_order_recv channels/drdynvc/client/drdynvc_main.c:1235
    #6 0x7f594c2547d1 in drdynvc_virtual_channel_client_thread channels/drdynvc/client/drdynvc_main.c:1389
    #7 0x7f594bf85756 in thread_launcher winpr/libwinpr/thread/thread.c:316
    #8 0x7f595497940a in start_thread (/lib64/libpthread.so.0+0x740a)
    #9 0x7f59546b440e in __GI___clone (/lib64/libc.so.6+0xed40e)
```

Let me know if you need any other information

**Comment by akallabeth** [comment]
@ignazp yes, what are you doing before you get this?

**Comment by ignazp** [comment]
@akallabeth The issue has been raised while playing a video on youtube on the remote instance.
If I connect to the instance without playing a video no leak has been detected.

**Comment by akallabeth** [comment]
and you are using? (versions, command line, ...)

**Comment by ignazp** [comment]
I'm closing this issue since I'm not able to reproduce it anymore, both valgrind and asan are not reporting any leak now. It is possible that the issue was related to our custom code.
We are using custom code based on libfreerdp on 2.4.1.
