### ISSUE TITLE
Segfault after some time when using AVC444 with libavcodec

### ISSUE THREAD

**Issue by anhammer** [FreeRDP/FreeRDP#7837]
**Describe the bug**
After displaying highly dynamic content (e.g. a fullscreen video in endless loop) for a long time (3 hours to 5 days), freerdp crashes in libavcodec.

**To Reproduce**
1. Connect to a windows machine via FreeRDP (use AVC444 with FFMPEG)
2. Open a video, e.g. in VLC, looping endlessly
3. Wait 1-5 days
4. FreeRDP crashes

**Expected behavior**
FreeRDP does not crash.

**Screenshots**
n/a

**Application details**
* FreeRDP version (`xfreerdp /version`)
  2.0.0 (dev version, Git commit: 5fc2290c03c2f716eac1a68c581e05b6127f7a10)
* Command line used
  - /log-filters:com.freerdp.crypto:OFF
  - /dynamic-resolution
  - /gfx-h264:AVC444
  - -clipboard
  - -aero
  - -fonts
  - -themes
  - -menu-anims
  - -window-drag
  - -wallpaper
  - +multitouch
  - /bpp:32
  - /h:1200
  - /w:1920
  - /d:****
  - /p:****
  - /u:****
  - /port:34497
  - /v:****
* Output of `xfreerdp /buildconfig`
  n/a
* OS version connecting to (server side)
  Tested with Windows Server 2019, Windows 10 20H2
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`
  n/a
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help
  - git master, commit 5fc2290c03c2f716eac1a68c581e05b6127f7a10
  - compiler: gcc 4:6.3.0-4
  - cmake params:
    - WITH_FFMPEG=ON
    - WITH_JPEG=ON
    - WITH_X264=OFF
    - WITH_OPENH264=OFF
    - WITH_MEDIA_FOUNDATION=OFF
    - WITH_GSTREAMER_0_10=OFF
    - WITH_GSTREAMER_1_0=OFF

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Debian 9
 - Architecture: amd64
 - libavcodec version: libavcodec57:amd64  7:3.2.16-1+deb9u1

**Additional context**

* Crashdump 1:
```
#0  0x00007f9d30a06ff6 in  () at /usr/lib/x86_64-linux-gnu/libavcodec.so.57
#1  0x00007f9d30a0754b in  () at /usr/lib/x86_64-linux-gnu/libavcodec.so.57
#2  0x00007f9d30a5db50 in  () at /usr/lib/x86_64-linux-gnu/libavcodec.so.57
#3  0x00007f9d30dbb092 in avcodec_decode_video2 () at /usr/lib/x86_64-linux-gnu/libavcodec.so.57
#4  0x00007f9d30dbbde0 in  () at /usr/lib/x86_64-linux-gnu/libavcodec.so.57
#5  0x00007f9d30dc1138 in avcodec_send_packet () at /usr/lib/x86_64-linux-gnu/libavcodec.so.57
#6  0x00007f9d320eca31 in libavcodec_decompress (h264=0x32761508d780, pSrcData=0x327618f6d02b "", SrcSize=98261) at ./freerdp/libfreerdp/codec/h264_ffmpeg.c:199
#7  0x00007f9d320e6c9a in avc444_process_rects (h264=h264@entry=0x32761508d780, pSrcData=<optimized out>, SrcSize=<optimized out>, pDstData=0x3275fe07d020 "\004\003\a", DstFormat=537168008, nDstStep=7680, nDstHeight=1088, rects=0x327607ea5970, nrRects=1, type=AVC444_LUMA,            nDstWidth=1920) at ./freerdp/libfreerdp/codec/h264.c:441
#8  0x00007f9d320e760a in avc444_decompress (h264=0x32761508d780, op=<optimized out>, regionRects=<optimized out>, numRegionRects=<optimized out>, pSrcData=<optimized out>, SrcSize=<optimized out>, auxRegionRects=0x0, numAuxRegionRect=0, pAuxSrcData=0x0, AuxSrcSize=0,                pDstData=0x3275fe07d020 "\004\003\a", DstFormat=537168008, nDstStep=7680, nDstWidth=1920, nDstHeight=1088, codecId=15) at ./freerdp/libfreerdp/codec/h264.c:507
#9  0x00007f9d3207a3eb in gdi_SurfaceCommand_AVC444 (gdi=0x3275f44f8400, cmd=0x7f9cee2a99b0, context=0x3275fe06e160) at ./freerdp/libfreerdp/gdi/gfx.c:575
#10 0x00007f9d3207a3eb in gdi_SurfaceCommand (context=0x3275fe06e160, cmd=0x7f9cee2a99b0) at ./freerdp/libfreerdp/gdi/gfx.c:906
#11 0x00007f9d3217ac7d in rdpgfx_decode_AVC444 (gfx=0x3275fe06e160, cmd=0x7f9cee2a99b0) at ./freerdp/channels/rdpgfx/client/rdpgfx_codec.c:250
#12 0x00007f9d3217ac7d in rdpgfx_decode (gfx=gfx@entry=0x32760efd8000, cmd=cmd@entry=0x7f9cee2a99b0) at ./freerdp/channels/rdpgfx/client/rdpgfx_codec.c:284
#13 0x00007f9d3217811a in rdpgfx_recv_wire_to_surface_1_pdu (callback=0x3275fe021900, s=0x3276125b9800) at ./freerdp/channels/rdpgfx/client/rdpgfx_main.c:1005
#14 0x00007f9d3217811a in rdpgfx_recv_pdu (s=0x3276125b9800, callback=0x3275fe021900) at ./freerdp/channels/rdpgfx/client/rdpgfx_main.c:1572
#15 0x00007f9d3217811a in rdpgfx_on_data_received (pChannelCallback=0x3275fe021900, data=<optimized out>) at ./freerdp/channels/rdpgfx/client/rdpgfx_main.c:1776
#16 0x00007f9d32155389 in dvcman_receive_channel_data (pChannelMgr=<optimized out>, ChannelId=<optimized out>, data=0x327612b8b800, drdynvc=<optimized out>) at ./freerdp/channels/drdynvc/client/drdynvc_main.c:726
#17 0x00007f9d32155a0c in drdynvc_process_data (s=<optimized out>, cbChId=<optimized out>, Sp=<optimized out>, drdynvc=<optimized out>) at ./freerdp/channels/drdynvc/client/drdynvc_main.c:1167
#18 0x00007f9d32155a0c in drdynvc_order_recv (s=0x327612b8b800, drdynvc=0x3275f1460a80) at ./freerdp/channels/drdynvc/client/drdynvc_main.c:1233
#19 0x00007f9d32155a0c in drdynvc_virtual_channel_client_thread (arg=<optimized out>) at ./freerdp/channels/drdynvc/client/drdynvc_main.c:1387
#20 0x00007f9d321d70f7 in thread_launcher (arg=0x32760f6cb9a0) at ./freerdp/winpr/libwinpr/thread/thread.c:327
#21 0x00007f9d4559b4a4 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#22 0x00007f9d3f4ded0f in clone () at /lib/x86_64-linux-gnu/libc.so.6
******line info******
No line number information available.
******locals info******
No symbol table info available.
******Registers info******
rax            0x2e00▸11776
rbx            0x327618f821fb▸55482806444539
rcx            0x0▸ 0
rdx            0x2e01▸11777
rsi            0x327618f84ffb▸55482806456315
rdi            0x800080080008080▸-9223231297218903936
rbp            0x327618f821fb▸0x327618f821fb
rsp            0x7f9cee2a9200▸0x7f9cee2a9200
r8             0xfefffefffefffeff▸-72058693566333185
r9             0x40000▸ 262144
r10            0xe48ef0e87bf876a3▸-1977378305066109277
r11            0x17fe7▸ 98279
r12            0x9▸ 9
r13            0x327618f85000▸55482806456320
r14            0x2e05▸11781
r15            0x32760ed595a0▸55482636408224
rip            0x7f9d30a06ff6▸0x7f9d30a06ff6
eflags         0x10202▸ [ IF RF ]
cs             0x33▸51
ss             0x2b▸43
ds             0x0▸ 0
es             0x0▸ 0
fs             0x0▸ 0
gs             0x0▸ 00
```

* Crashdump 2:
```
[Thread debugging using libthread_db enabled]

Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
c0x00007fa5136b117f in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) c
Continuing.

Thread 71 "chrome" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fa4d03cc700 (LWP 15264)]
0x00007fa4fe72d4a0 in ff_h2645_extract_rbsp (src=0x11a4247e2682 "a", length=6525, nal=0x11a2ed51e1a0, small_padding=0) at src/libavcodec/h2645_parse.c:56
56 src/libavcodec/h2645_parse.c: No such file or directory.
(gdb) bt
#0 0x00007fa4fe72d4a0 in ff_h2645_extract_rbsp (src=0x11a4247e2682 "a", length=6525, nal=0x11a2ed51e1a0, small_padding=0) at src/libavcodec/h2645_parse.c:56
#1 0x00007fa4fe72e0c1 in ff_h2645_packet_split (pkt=0x11a2fd45b2c8, buf=0x11a4247e2682 "a", length=6525, logctx=0x11a2fb975480, is_nalff=0, nal_length_size=0, codec_id=AV_CODEC_ID_H264, small_padding=0) at src/libavcodec/h2645_parse.c:329
#2 0x00007fa4fe82719a in decode_nal_units (h=0x11a2fd454000, buf=0x11a4247d402b "", buf_size=65492) at src/libavcodec/h264dec.c:751
#3 0x00007fa4fe828615 in h264_decode_frame (avctx=0x11a2fb975480, data=0x11a2fd461000, got_frame=0x7fa4d03cb4cc, avpkt=0x7fa4d03cb440) at src/libavcodec/h264dec.c:1118
#4 0x00007fa4fece0abf in avcodec_decode_video2 (avctx=0x11a2fb975480, picture=0x11a2fd461000, got_picture_ptr=0x7fa4d03cb4cc, avpkt=0x11a2fc806ae0) at src/libavcodec/utils.c:2295
#5 0x00007fa4fece2be0 in do_decode (avctx=0x11a2fb975480, pkt=0x11a2fc806ae0) at src/libavcodec/utils.c:2826
#6 0x00007fa4fece2ff3 in avcodec_send_packet (avctx=0x11a2fb975480, avpkt=0x11a2fc806ae0) at src/libavcodec/utils.c:2915
#7 0x00007fa5001e1a31 in libavcodec_decompress (h264=0x11a2fd469f00, pSrcData=0x11a4247d402b "", SrcSize=65492) at ./freerdp/libfreerdp/codec/h264_ffmpeg.c:199
#8 0x00007fa5001dbc9a in avc444_process_rects (h264=h264@entry=0x11a2fd469f00, pSrcData=<optimized out>, SrcSize=<optimized out>, pDstData=0x11a2ffe47020 "\377\374\377", DstFormat=537168008, nDstStep=7680, nDstHeight=1200, rects=0x11a4159d6020, nrRects=1, type=AVC444_LUMA, nDstWidth=1920)
{{ at ./freerdp/libfreerdp/codec/h264.c:441}}
#9 0x00007fa5001dc60a in avc444_decompress (h264=0x11a2fd469f00, op=<optimized out>, regionRects=<optimized out>, numRegionRects=<optimized out>, pSrcData=<optimized out>, SrcSize=<optimized out>, auxRegionRects=0x0, numAuxRegionRect=0, pAuxSrcData=0x0, AuxSrcSize=0, pDstData=0x11a2ffe47020 "\377\374\377", DstFormat=537168008, n
DstStep=7680, nDstWidth=1920, nDstHeight=1200, codecId=15) at ./freerdp/libfreerdp/codec/h264.c:507
#10 0x00007fa50016f3eb in gdi_SurfaceCommand_AVC444 (gdi=0x11a2ee69b300, cmd=0x7fa4d03cb9b0, context=0x11a2f5c882c0) at ./freerdp/libfreerdp/gdi/gfx.c:575
#11 0x00007fa50016f3eb in gdi_SurfaceCommand (context=0x11a2f5c882c0, cmd=0x7fa4d03cb9b0) at ./freerdp/libfreerdp/gdi/gfx.c:906
#12 0x00007fa50026fc8d in rdpgfx_decode_AVC444 (gfx=0x11a2f5c882c0, cmd=0x7fa4d03cb9b0) at ./freerdp/channels/rdpgfx/client/rdpgfx_codec.c:250
#13 0x00007fa50026fc8d in rdpgfx_decode (gfx=gfx@entry=0x11a2fc440000, cmd=cmd@entry=0x7fa4d03cb9b0) at ./freerdp/channels/rdpgfx/client/rdpgfx_codec.c:284
#14 0x00007fa50026d1ba in rdpgfx_recv_wire_to_surface_1_pdu (callback=0x11a2f8833060, s=0x11a42430c500) at ./freerdp/channels/rdpgfx/client/rdpgfx_main.c:1008
#15 0x00007fa50026d1ba in rdpgfx_recv_pdu (s=0x11a42430c500, callback=0x11a2f8833060) at ./freerdp/channels/rdpgfx/client/rdpgfx_main.c:1575
#16 0x00007fa50026d1ba in rdpgfx_on_data_received (pChannelCallback=0x11a2f8833060, data=<optimized out>) at ./freerdp/channels/rdpgfx/client/rdpgfx_main.c:1779
#17 0x00007fa50024a389 in dvcman_receive_channel_data (pChannelMgr=<optimized out>, ChannelId=<optimized out>, data=0x11a39120e880, drdynvc=<optimized out>) at ./freerdp/channels/drdynvc/client/drdynvc_main.c:726
#18 0x00007fa50024aa0c in drdynvc_process_data (s=<optimized out>, cbChId=<optimized out>, Sp=<optimized out>, drdynvc=<optimized out>) at ./freerdp/channels/drdynvc/client/drdynvc_main.c:1167
#19 0x00007fa50024aa0c in drdynvc_order_recv (s=0x11a39120e880, drdynvc=0x11a2f62213c0) at ./freerdp/channels/drdynvc/client/drdynvc_main.c:1233
#20 0x00007fa50024aa0c in drdynvc_virtual_channel_client_thread (arg=<optimized out>) at ./freerdp/channels/drdynvc/client/drdynvc_main.c:1387
#21 0x00007fa5002cc0b7 in thread_launcher (arg=0x11a2f6218700) at ./freerdp/winpr/libwinpr/thread/thread.c:327
#22 0x00007fa5136ab4a4 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#23 0x00007fa50d5eed0f in clone () at /lib/x86_64-linux-gnu/libc.so
```

I think it crashes inside libavcodec because some buffer requirements were not met, particularly:
http://ffmpeg.org/doxygen/3.2/group__lavc__decoding.html#ga58bc4bf1e0ac59e27362597e467efff3
> The input buffer, avpkt->data must be AV_INPUT_BUFFER_PADDING_SIZE larger than the actual read bytes because some optimized bitstream readers read 32 or 64 bits at once and could read over the end.

https://ffmpeg.org/doxygen/3.3/group__lavc__decoding.html#ga8f5b632a03ce83ac8e025894b1fc307a
> #define AV_INPUT_BUFFER_PADDING_SIZE   32
> Required number of additionally allocated bytes at the end of the input bitstream for decoding.
>
> This is mainly needed because some optimized bitstream readers read 32 or 64 bit at once and could read over the end.
> Note: If the first 23 bits of the additional bytes are not 0, then damaged MPEG bitstreams could cause overread and segfault.

I think what is happening is that some buffer is missing the padding, and libavcodec's optimized code is reading a few bytes too much. These additional bytes are not used for decoding, so normally, reading them does not do any harm. But if the buffer ends close to the end of a memory page, these few additional bytes may reach into the next page, causing a SIGSEGV. This would also explain why the crash is not deterministic.

Looked a bit around in the source code... The buffers seem to be allocated in `libfreerdp/codec/zgfx.c` in the function `zgfx_decompress()`. At least here, I don't see any extra handling for buffer padding or the like.
These buffers seem to be used later in `libfreerdp/codec/h264_ffmpeg.c` by func `libavcodec_decompress()`.

Did a quick hack with adding 32 bytes of zeroed padding to the buffers allocated here. I started a test again, that is already running for 14 days without crash.

Note that I didn't use the most recent version of FreeRDP. But I checked the code on latest master, and to me it seems no changes regarding this buffer allocation were done in the meantime, so I think the bug still exists.

I don't have an overview over other buffers that also might need a padding, or what kind of configurations result in what kind of padding (when not using ffmpeg)... But I hope this information is sufficient. If not then just ask, I'll see what I can do :)

**Comment by akallabeth** [comment]
@anhammer thank you for the hint.
Since you already seem to have some working code, could you create a pull request for that?

**Comment by anhammer** [comment]
> @anhammer thank you for the hint. Since you already seem to have some working code, could you create a pull request for that?

@akallabeth Wow, that fix was quick - thanks! Guess my hacky code PR is not needed anymore :)

A quick question just out of curiosity: The libavcodec docs state that the first 23 bits should be zeroed in case of damaged MPEG streams. Is this not needed because we can expect the stream to not be damaged? (Because FreeRDP uses TCP?)

**Comment by akallabeth** [comment]
@anhammer yes, did have the mood yesterday, did quite a lot of fixes.
As for the stream, the data we feed has already been through error checking of various layers (RDP also has one above TCP or UDP), so if the data is still damaged then the server is malicious (and then zeroing does not help anyway as these get overwritten)
