### ISSUE TITLE
Error reporting using armeabi-v7a

### ISSUE THREAD

**Issue by FengYuanBiao** [FreeRDP/FreeRDP#8138]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__atomic_store" referenced by "/data/app/com.itc.control-HBXzQaVlIqKnuqkKqiz6Tg==/lib/arm/libssl.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at com.freerdp.freerdpcore.services.LibFreeRDP.<clinit>(LibFreeRDP.java:80)
        at com.freerdp.freerdpcore.services.LibFreeRDP.setEventListener(LibFreeRDP.java:150)

**version：2.7.0**

**Comment by mfleisz** [comment]
@FengYuanBiao have you read the issue template? We need more context (environment, build settings, etc).
