### ISSUE TITLE
 [core,arm] Detected memory leaks

### ISSUE THREAD

**Issue by progxaker** [FreeRDP/FreeRDP#9416]
**Describe the bug**
`SUMMARY: AddressSanitizer: 789112 byte(s) leaked in 1941 allocation(s).`

<details>

```
=================================================================
==133193==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1620 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f5c385748ab in freerdp_certificate_get_public_key ../libfreerdp/crypto/certificate.c:1510
    #2 0x7f5c3857ae11 in freerdp_tls_handshake ../libfreerdp/crypto/tls.c:880
    #3 0x7f5c3857ae11 in freerdp_tls_handshake ../libfreerdp/crypto/tls.c:848
    #4 0x7f5c3857dfdf in pollAndHandshake ../libfreerdp/crypto/tls.c:939
    #5 0x7f5c3857dfdf in pollAndHandshake ../libfreerdp/crypto/tls.c:907
    #6 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #7 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #8 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #9 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #10 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #11 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #12 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Direct leak of 720 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c3725fc0d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x17bc0d)
    #2 0x7f5c3857e250 in freerdp_tls_connect_ex ../libfreerdp/crypto/tls.c:838
    #3 0x7f5c3857e250 in freerdp_tls_connect ../libfreerdp/crypto/tls.c:959
    #4 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #5 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #6 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #7 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #8 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #9 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #10 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Direct leak of 96 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f5c3857acbd in tls_get_channel_bindings ../libfreerdp/crypto/tls.c:644
    #2 0x7f5c3857acbd in freerdp_tls_handshake ../libfreerdp/crypto/tls.c:873
    #3 0x7f5c3857acbd in freerdp_tls_handshake ../libfreerdp/crypto/tls.c:848
    #4 0x7f5c3857dfdf in pollAndHandshake ../libfreerdp/crypto/tls.c:939
    #5 0x7f5c3857dfdf in pollAndHandshake ../libfreerdp/crypto/tls.c:907
    #6 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #7 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #8 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #9 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #10 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #11 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #12 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 393216 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c386226fe in ringbuffer_init ../libfreerdp/utils/ringbuffer.c:44
    #2 0x7f5c38487b64 in transport_bio_buffered_new ../libfreerdp/core/tcp.c:621
    #3 0x7f5c3718c7b6 in BIO_new (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xa87b6)
    #4 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #5 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #6 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 100272 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c373e130f  (/lib/x86_64-linux-gnu/libssl.so.1.1+0x2730f)

Indirect leak of 98832 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c373e1421  (/lib/x86_64-linux-gnu/libssl.so.1.1+0x27421)

Indirect leak of 84536 byte(s) in 1238 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c3725fc0d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x17bc0d)

Indirect leak of 45168 byte(s) in 30 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c3725fc0d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x17bc0d)
    #2 0x7f5c3857e250 in freerdp_tls_connect_ex ../libfreerdp/crypto/tls.c:838
    #3 0x7f5c3857e250 in freerdp_tls_connect ../libfreerdp/crypto/tls.c:959
    #4 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #5 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #6 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #7 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #8 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #9 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #10 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 17124 byte(s) in 12 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c371831ed  (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x9f1ed)

Indirect leak of 11094 byte(s) in 312 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c37176ce9 in ASN1_STRING_set (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x92ce9)

Indirect leak of 9384 byte(s) in 24 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c3716d42c  (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x8942c)

Indirect leak of 4368 byte(s) in 24 object(s) allocated from:
    #0 0x7f5c38d99c3e in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:163
    #1 0x7f5c372c2774  (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1de774)

Indirect leak of 3888 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c373fbe28  (/lib/x86_64-linux-gnu/libssl.so.1.1+0x41e28)

Indirect leak of 3408 byte(s) in 18 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c372c2d58 in OPENSSL_sk_dup (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1ded58)

Indirect leak of 3192 byte(s) in 24 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c371afcdf in BUF_MEM_grow (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xcbcdf)

Indirect leak of 2286 byte(s) in 24 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c372e1c4b  (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1fdc4b)

Indirect leak of 2112 byte(s) in 24 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c3725fc0d in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x17bc0d)
    #2 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #3 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #4 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 1976 byte(s) in 19 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c371a034b in BN_MONT_CTX_new (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xbc34b)

Indirect leak of 1656 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c3740dcf9  (/lib/x86_64-linux-gnu/libssl.so.1.1+0x53cf9)

Indirect leak of 576 byte(s) in 18 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c372c2d03 in OPENSSL_sk_dup (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1ded03)

Indirect leak of 576 byte(s) in 36 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c3718181d  (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x9d81d)
    #2 0x50afa628b1879ff  (<unknown module>)

Indirect leak of 510 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f5c3857ad00 in tls_get_channel_bindings ../libfreerdp/crypto/tls.c:650
    #2 0x7f5c3857ad00 in freerdp_tls_handshake ../libfreerdp/crypto/tls.c:873
    #3 0x7f5c3857ad00 in freerdp_tls_handshake ../libfreerdp/crypto/tls.c:848
    #4 0x7f5c3857dfdf in pollAndHandshake ../libfreerdp/crypto/tls.c:939
    #5 0x7f5c3857dfdf in pollAndHandshake ../libfreerdp/crypto/tls.c:907
    #6 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #7 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #8 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #9 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #10 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #11 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #12 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 444 byte(s) in 12 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c3726931a in CRYPTO_strdup (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x18531a)

Indirect leak of 384 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f5c38487b43 in transport_bio_buffered_new ../libfreerdp/core/tcp.c:614
    #2 0x7f5c3718c7b6 in BIO_new (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xa87b6)
    #3 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #4 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #5 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 288 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f5c3856d477 in bio_rdp_tls_new ../libfreerdp/crypto/tls.c:457
    #2 0x7f5c3718c7b6 in BIO_new (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xa87b6)
    #3 0x7f5c3857e250 in freerdp_tls_connect_ex ../libfreerdp/crypto/tls.c:838
    #4 0x7f5c3857e250 in freerdp_tls_connect ../libfreerdp/crypto/tls.c:959
    #5 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #6 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #7 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #8 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #9 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #10 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #11 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 240 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f5c37f72bbe in CreateEventA ../winpr/libwinpr/synch/event.c:290
    #2 0x7f5c38475fe3 in transport_bio_simple_init ../libfreerdp/core/tcp.c:355
    #3 0x7f5c38476401 in transport_bio_simple_ctrl ../libfreerdp/core/tcp.c:306
    #4 0x7f5c3718d019 in BIO_ctrl (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xa9019)

Indirect leak of 192 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c37233bda  (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x14fbda)

Indirect leak of 192 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c372c2d58 in OPENSSL_sk_dup (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1ded58)
    #2 0x7f5c3857e250 in freerdp_tls_connect_ex ../libfreerdp/crypto/tls.c:838
    #3 0x7f5c3857e250 in freerdp_tls_connect ../libfreerdp/crypto/tls.c:959
    #4 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #5 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #6 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #7 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #8 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #9 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #10 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 192 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c372c2d03 in OPENSSL_sk_dup (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x1ded03)
    #2 0x7f5c3857e250 in freerdp_tls_connect_ex ../libfreerdp/crypto/tls.c:838
    #3 0x7f5c3857e250 in freerdp_tls_connect ../libfreerdp/crypto/tls.c:959
    #4 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #5 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #6 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #7 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #8 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #9 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #10 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 192 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c37f730c4 in InitializeCriticalSectionEx ../winpr/libwinpr/synch/critical.c:76
    #2 0x7f5c3856d48d in bio_rdp_tls_new ../libfreerdp/crypto/tls.c:460
    #3 0x7f5c3718c7b6 in BIO_new (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xa87b6)
    #4 0x7f5c3857e250 in freerdp_tls_connect_ex ../libfreerdp/crypto/tls.c:838
    #5 0x7f5c3857e250 in freerdp_tls_connect ../libfreerdp/crypto/tls.c:959
    #6 0x7f5c384bbc8a in arm_tls_connect ../libfreerdp/core/gateway/arm.c:145
    #7 0x7f5c384bbc8a in arm_handle_request ../libfreerdp/core/gateway/arm.c:879
    #8 0x7f5c384bbc8a in arm_resolve_endpoint ../libfreerdp/core/gateway/arm.c:962
    #9 0x7f5c384bbc8a in rdp_client_connect ../libfreerdp/core/connection.c:333
    #10 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #11 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #12 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

Indirect leak of 162 byte(s) in 18 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c37170a0a  (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x8ca0a)

Indirect leak of 120 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f5c371edf29 in EC_GROUP_copy (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0x109f29)

Indirect leak of 96 byte(s) in 6 object(s) allocated from:
    #0 0x7f5c38d99a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
    #1 0x7f5c38475bd9 in transport_bio_simple_new ../libfreerdp/core/tcp.c:399
    #2 0x7f5c3718c7b6 in BIO_new (/lib/x86_64-linux-gnu/libcrypto.so.1.1+0xa87b6)
    #3 0x7f5c384fb71e in freerdp_connect_begin ../libfreerdp/core/freerdp.c:160
    #4 0x7f5c384fb71e in freerdp_connect ../libfreerdp/core/freerdp.c:178
    #5 0x56041f1c5554 in sdl_client_thread_proc ../client/SDL/sdl_freerdp.cpp:1040

SUMMARY: AddressSanitizer: 789112 byte(s) leaked in 1941 allocation(s).
```

</details>

**To Reproduce**
1. Run the following command with a disabled AVD instance.
    `sdl-freerdp ./SessionDesktop.rdpw /gateway:type:arm /f /size:1366x768 /u:<email> /p:'<password>' /mic:sys:pulse,format:1 /network:auto /auto-reconnect`
2. After successful connection, close the program.

**Expected behavior**
No memory leaks.

**Application details**
* FreeRDP version (`xfreerdp /version`)
This is FreeRDP version 3.0.0-dev4 (5a7a1c159d2c7af3df2e85f9516446710a505494)
* Output of `xfreerdp /buildconfig`
<details>
<summary>Build config</summary>

```
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=ON WITH_DEBUG_CAPABILITIES=ON WITH_DEBUG_CERTIFICATE=ON WITH_DEBUG_CHANNELS=ON WITH_DEBUG_CLIPRDR=ON WITH_DEBUG_CODECS=ON WITH_DEBUG_DVC=ON WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=ON WITH_DEBUG_LICENSE=ON WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=ON WITH_DEBUG_NLA=ON WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=ON WITH_DEBUG_RDP=ON WITH_DEBUG_RDPDR=ON WITH_DEBUG_RDPEI=ON WITH_DEBUG_RDPGFX=ON WITH_DEBUG_REDIR=ON WITH_DEBUG_RFX=ON WITH_DEBUG_RINGBUFFER=ON WITH_DEBUG_SCARD=ON WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=ON WITH_DEBUG_SVC=ON WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=ON WITH_DEBUG_TRANSPORT=ON WITH_DEBUG_TSG=ON WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=ON WITH_DEBUG_X11=ON WITH_DEBUG_X11_LOCAL_MOVESIZE=ON WITH_DEBUG_XV=ON WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=ON WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:               -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope
Compiler:            GNU, 9.4.0
Target architecture: x64
```

</details>

* OS version connecting to (server side) - Windows 11

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: xUbuntu 20.06 LTS
 - Architecture: amd64

**Additional context**

No memory leaks when FreeRDP is successfully connected to a *running* AVD instance.

**Comment by akallabeth** [comment]
@progxaker nice, slowly getting this stable one bug a time ^^

**Comment by progxaker** [comment]
Yeah, in small steps to make it better :)
