### ISSUE TITLE
Cannot connect to AVD: Failed to load addins [%08X]

### ISSUE THREAD

**Issue by DasHammett** [FreeRDP/FreeRDP#9591]
**Describe the bug**
When trying to connect to an AVD following the FAQ entry, I get the following error:
```
[19:08:08:221] [24822:000060f6] [WARN][com.freerdp.client.common] - [freerdp_client_populate_settings_from_rdp_file]: This build does not support [MS-RDPECAM] camera redirection channel. Ignoring 'camerastoredirect'
[19:08:08:221] [24822:000060f7] [INFO][com.freerdp.client.x11] - [xf_setup_x11]: Enabling X11 debug mode.
[19:08:08:252] [24822:000060f7] [ERROR][com.freerdp.client.common] - [freerdp_client_load_channels]: Failed to load addins [%08X]
[19:08:08:252] [24822:000060f6] [ERROR][com.freerdp.core] - [freerdp_abort_connect_context]: ERRCONNECT_CONNECT_CANCELLED [0x0002000B]
```

**To Reproduce**
1. Compile freerdp from git
2. Download the rpdw file
3. Try to connect with: `xfreerdp <rpdw file.rpdw> /gateway:type:arm`

**Expected behavior**
To be presented with the url to paste to continue the process

**Application details**
* Freerdp version: `This is FreeRDP version 3.0.0-dev5 (50d05d921)`
* Coompiled from Gentoo with the following flags: `net-misc/freerdp-9999:0/2::gentoo  USE="X aad alsa cups ffmpeg icu jpeg openh264 pulseaudio sdl usb xinerama -debug -doc -gstreamer -kerberos -server -smartcard -systemd -test -valgrind -wayland -xv"` 
* buildconfig:
```
This is FreeRDP version 3.0.0-dev5 (50d05d921)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSTREAMER_1_0=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=OFF WITH_PCSC=OFF WITH_PKCS11=OFF WITH_POLL=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_SYSTEMD=OFF WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WEBVIEW=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=OFF
Build type:          RelWithDebInfo
CFLAGS:              -fgraphite-identity -floop-interchange -floop-strip-mine -floop-block -floop-nest-optimize -march=znver2 -O2 -pipe -Wall -Wpedantic -Wno-padded -Wno-cast-align
-Wno-declaration-after-statement -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer
Compiler:            GNU, 13.2.1
Target architecture: x64
```
* Target: Windows 10 (AVD)

**Environment (please complete the following information):**
 - OS: Gentoo Linux
 - Kernel: 6.6.2
 - x64

**Additional context**
Tried also with `/sec:aad` but did not help. Connecting to a local virtual machine works with also Windows 10 works fine. Am I missing an option to compile?

Let me know anything else you need

Thanks

**Comment by akallabeth** [comment]
@DasHammett this looks like unsupported stuff is in the rdp file (camera redirection), try to comment that and retry.
as for `[19:08:08:252] [24822:000060f7] [ERROR][com.freerdp.client.common] - [freerdp_client_load_channels]: Failed to load addins [%08X]` fixed that in #9573

**Comment by DasHammett** [comment]
Hi akallabeth

Apologies for bringing this up again, but with the latest master (after merging #9573 to master), I still have the same issue with the addings:
```
[16:01:12:676] [20647:000050a8] [INFO][com.freerdp.client.x11] - [xf_setup_x11]: Enabling X11 debug mode.
[16:01:12:708] [20647:000050a8] [ERROR][com.freerdp.client.common] - [freerdp_client_load_channels]: Failed to load addins [00000000]
[16:01:12:709] [20647:000050a7] [ERROR][com.freerdp.core] - [freerdp_abort_connect_context]: ERRCONNECT_CONNECT_CANCELLED [0x0002000B]
```
I am unsure what I might be missing?

**Comment by akallabeth** [comment]
@DasHammett your build is still broken, it lacks some plugins at the proper location.
enable `/log-level:debug`, maybe you get more details.

**Comment by DasHammett** [comment]
Added `/log-level:debug` but it does not seem to be helpful (or at least to me to see what I am missing).

```
[18:23:55:158] [10822:00002a47] [DEBUG][com.freerdp.core] - [freerdp_connect_begin]: resetting error state
[18:23:55:158] [10822:00002a47] [INFO][com.freerdp.client.x11] - [xf_setup_x11]: Enabling X11 debug mode.
[18:23:55:161] [10822:00002a47] [DEBUG][com.freerdp.client.x11] - [xf_GetWindowProperty]: Property 310 does not exist
[18:23:55:190] [10822:00002a47] [ERROR][com.freerdp.client.common] - [freerdp_client_load_channels]: Failed to load addins [00000000]
[18:23:55:191] [10822:00002a47] [DEBUG][com.freerdp.core.rdp] - [rdp_finalize_reset_flags][0x5606f1d15ad0]: [CONNECTION_STATE_INITIAL]
reset finalize_sc_pdus
[18:23:55:191] [10822:00002a47] [DEBUG][com.freerdp.core.rdp] - [rdp_client_transition_to_state][0x5606f1d15ad0]: CONNECTION_STATE_INITIAL --> CONNECTION_STATE_INITIAL
[18:23:55:192] [10822:00002a46] [ERROR][com.freerdp.core] - [freerdp_abort_connect_context]: ERRCONNECT_CONNECT_CANCELLED [0x0002000B]
```
Can you perhaps point me into the right direction of what might be missing from the buildlog posted in the previous posts? The fact that I can compile `freerdp`without issues but this is not working is puzzling me as I have no idea where to look

Kindly appreciate your help
Thanks

**Comment by loligans** [comment]
So I was having similar issues related to this caused by my `redirectlocation` property being enabled in the rdp config. I fixed it by commenting it out, however now I consistently get a crash

`./xfreerdp ~/Downloads/rdp/test.rdp /u:"omitted" /p:"Omitted"`

```
[08:03:52:238] [114614:0001bfb7] [WARN][com.freerdp.core.license] - [license_read_binary_blob_data]: license binary blob::type BB_ERROR_BLOB, length=0, skipping.
[08:03:52:238] [114614:0001bfb7] [WARN][com.freerdp.core.multitransport] - [multitransport_recv_request]: reserved is 1 instead of 0, skipping 3658bytes of unknown data
```

```
==114614==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7b1e972d1248 at pc 0x59fd0d3ecec7 bp 0x7b1e972d1120 sp 0x7b1e972d1110
READ of size 1 at 0x7b1e972d1248 thread T1
    #0 0x59fd0d3ecec6  (/opt/freerdp-nightly/bin/xfreerdp+0x2cec6)
    #1 0x59fd0d40682e  (/opt/freerdp-nightly/bin/xfreerdp+0x4682e)
    #2 0x59fd0d40cc3c  (/opt/freerdp-nightly/bin/xfreerdp+0x4cc3c)
    #3 0x7b1ea62af161 in freerdp_connect (/opt/freerdp-nightly/bin/../lib/libfreerdp3.so.3+0x2af161)
    #4 0x59fd0d41c9e6  (/opt/freerdp-nightly/bin/xfreerdp+0x5c9e6)
    #5 0x7b1ea5d8bc5d  (/opt/freerdp-nightly/bin/../lib/libwinpr3.so.3+0x18bc5d)
    #6 0x7b1ea5894ac2  (/lib/x86_64-linux-gnu/libc.so.6+0x94ac2)
    #7 0x7b1ea5926a3f  (/lib/x86_64-linux-gnu/libc.so.6+0x126a3f)

Address 0x7b1e972d1248 is located in stack of thread T1 at offset 104 in frame
    #0 0x59fd0d3ebf7f  (/opt/freerdp-nightly/bin/xfreerdp+0x2bf7f)

  This frame has 4 object(s):
    [48, 52) 'ndevices' (line 72)
    [64, 104) 'masks' (line 75) <== Memory access at offset 104 overflows this variable
    [144, 344) 'devName' (line 145)
    [416, 1440) 'evmasks' (line 74)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
Thread T1 created by T0 here:
    #0 0x7b1ea6c58685 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:216
    #1 0x7b1ea5d8addd  (/opt/freerdp-nightly/bin/../lib/libwinpr3.so.3+0x18addd)
    #2 0x7b1ea5d8f0b7 in CreateThread (/opt/freerdp-nightly/bin/../lib/libwinpr3.so.3+0x18f0b7)
    #3 0x59fd0d400f00  (/opt/freerdp-nightly/bin/xfreerdp+0x40f00)
    #4 0x59fd0d3dd33a  (/opt/freerdp-nightly/bin/xfreerdp+0x1d33a)
    #5 0x7b1ea5829d8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)

SUMMARY: AddressSanitizer: stack-buffer-overflow (/opt/freerdp-nightly/bin/xfreerdp+0x2cec6) 
Shadow bytes around the buggy address:
  0x0f6452e521f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0f6452e52200: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0f6452e52210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0f6452e52220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0f6452e52230: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
=>0x0f6452e52240: f1 f1 04 f2 00 00 00 00 00[f2]f2 f2 f2 f2 f8 f8
  0x0f6452e52250: f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x0f6452e52260: f8 f8 f8 f8 f8 f8 f8 f2 f2 f2 f2 f2 f2 f2 f2 f2
  0x0f6452e52270: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0f6452e52280: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0f6452e52290: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==114614==ABORTING
```
