### ISSUE TITLE
sdl-freerdp crashes on master (~3.0.0-rc) during window resizing with dynamic resolution

### ISSUE THREAD

**Issue by pnowack** [FreeRDP/FreeRDP#9627]
Affected version: current master (build was afair against commit https://github.com/FreeRDP/FreeRDP/commit/2b1aae02380a6fd59a27e5c1c44b1f0d0e564034)

Server side: gnome-remote-desktop (g-r-d) (using with virtual monitors here)
Used cmdline for sdl-freerdp: `sdl-freerdp /v:[::1] /u:<user> /p:<pw> /dynamic-resolution /size:1920x1080`

Not sure how, but during resizing the sdl-freerdp window, sdl-freerdp crashed somehow. So far, I only was able to run into this issue once (not sure (yet) how to reproduce it).

Stacktrace: 
[sdl-freerdp bt full.txt](https://github.com/FreeRDP/FreeRDP/files/13632479/sdl-freerdp.bt.full.txt)

**Comment by pnowack** [comment]
I did a rebuild of the SDL2 pkg to include debug symbols. Unfortunately, `gdb` now does not include the FreeRDP part anymore, but this here should be the SDL part (apparently, I ran into this crash twice, not sure, which does correspond to the trace above):

```c
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb856cac83c in ?? () from /usr/bin/../lib/libc.so.6
[Current thread is 1 (Thread 0x7fb842ffc680 (LWP 329695))]
(gdb) bt full
#0  0x00007fb856cac83c in  () at /usr/bin/../lib/libc.so.6
#1  0x00007fb856c5c668 in raise () at /usr/bin/../lib/libc.so.6
#2  0x00007fb85e441856 in fatal_handler (signum=11) at /usr/src/debug/freerdp3/FreeRDP/libfreerdp/utils/signal.c:130
        default_sigaction = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {18446744067267100671, 5716, 0, 0, 0, 0, 0, 0, 0, 0, 4901675614348505088, 0, 0, 0, 0, 0}}, sa_flags = 0, sa_restorer = 0x0}
        this_mask = {__val = {1024, 0 <repeats 13 times>, 1, 192}}
        recursive = 1
        _log_cached_ptr = 0x5566b18a99c0
        __func__ = "fatal_handler"
#3  0x00007fb856c5c710 in <signal handler called> () at /usr/bin/../lib/libc.so.6
#4  0x00007fb85e2ceeac in Blit_RGB888_index8 (info=<optimized out>) at /usr/src/debug/sdl2/SDL2-2.28.5/src/video/SDL_blit_N.c:984
        n = 1035
        width = <optimized out>
        height = <optimized out>
        src = <optimized out>
        map = <optimized out>
        dst = 0x0
        srcskip = <optimized out>
        dstskip = 8
#5  0x00007fb82001a470 in  ()
```

```c
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f9d91aac83c in ?? () from /usr/bin/../lib/libc.so.6
[Current thread is 1 (Thread 0x7f9d7dd70680 (LWP 329580))]
(gdb) bt full
#0  0x00007f9d91aac83c in  () at /usr/bin/../lib/libc.so.6
#1  0x00007f9d91a5c668 in raise () at /usr/bin/../lib/libc.so.6
#2  0x00007f9d99241856 in fatal_handler (signum=11) at /usr/src/debug/freerdp3/FreeRDP/libfreerdp/utils/signal.c:130
        default_sigaction = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {18446744067267100671, 5716, 0, 0, 0, 0, 0, 0, 0, 0, 4901781167464763392, 0, 0, 0, 0, 0}}, sa_flags = 0, sa_restorer = 0x0}
        this_mask = {__val = {1024, 0 <repeats 13 times>, 1, 192}}
        recursive = 1
        _log_cached_ptr = 0x564523fa09c0
        __func__ = "fatal_handler"
#3  0x00007f9d91a5c710 in <signal handler called> () at /usr/bin/../lib/libc.so.6
#4  0x00007f9d990ceef4 in Blit_RGB101010_index8 (info=0xea) at /usr/src/debug/sdl2/SDL2-2.28.5/src/video/SDL_blit_N.c:1089
        width = <optimized out>
        height = <optimized out>
        src = <optimized out>
        map = <optimized out>
        dst = <optimized out>
        srcskip = <optimized out>
        dstskip = <optimized out>
#5  0x00007f9d5c01a4d0 in  ()
```
